//! C ABI over the ArmoniK Rust transport, for host applications that cannot link Rust directly.
//!
//! # Scope
//!
//! This crate speaks HTTP, not gRPC. A request is opened with a set of headers, bytes are streamed
//! in both directions, and headers, data and trailers come back. There is no notion here of a call
//! shape, of a `grpc-status`, of message framing or of retry: those belong to whatever gRPC stack
//! the host application already has, and this crate is the transport underneath it. Configuration
//! parsing, TLS, mTLS and proxy handling all live in
//! [`armonik_transport`](https://docs.rs/armonik-transport); this crate only adapts that connection
//! layer to a C ABI.
//!
//! # The reactor contract
//!
//! One event callback per request, invoked by this crate. Three rules, and everything else follows
//! from them:
//!
//! 1. **Nothing arrives unarmed.** [`ak_request_read`] arms exactly one read, which produces
//!    exactly one event: `READ_DONE` with the bytes, or `COMPLETED`. [`ak_request_write`] arms
//!    exactly one write, which produces `WRITE_DONE`. At most one read and one write may be armed
//!    at a time on a request; arming a second returns [`status::INVALID_STATE`].
//! 2. **`COMPLETED` exactly once, and last.** If [`ak_request_start`] returns [`status::OK`], a
//!    `COMPLETED` event always follows, whatever happens - cancellation, a connection failure, a
//!    panic inside this crate. If `start` returns an error, no event ever arrives. After
//!    `COMPLETED` no callback is ever made again for that request, so that is where - and only
//!    there - the caller releases whatever it rooted for `ctx`. Releasing the handle does not end
//!    that obligation; the terminal event does.
//! 3. **No callback during an inbound call.** Every function here posts a command and returns;
//!    events are emitted from this crate's own runtime threads. There is no re-entrance, and
//!    delivery is serialised per request, so a caller demultiplexing events needs no lock of its
//!    own.
//!
//! The event payload is **borrowed** for the duration of the invocation: copy what you need before
//! returning. Nothing on the event path is ever freed by the caller.
//!
//! See `include/armonik_transport_ffi.h` for the full contract, generated by `cbindgen` from the
//! `pub extern "C"` items below and committed so an ABI change shows up in review.
//!
//! # Safety discipline
//!
//! - Every `extern "C"` entry point is wrapped by one of this crate's internal
//!   `catch_unwind_status`/`catch_unwind_status_only`/`catch_unwind_void` helpers, so a panic can
//!   never cross the ABI boundary.
//! - Every allocation handed to the caller travels as an [`error::ak_bytes`] and must be released
//!   through [`error::ak_bytes_free`] exactly once. Only synchronous out-parameters produce one;
//!   the event path never does.
//! - Every opaque handle ([`client::ak_client`], [`request::ak_request`]) is reference-counted.
//!   `_release` gives up one reference; the object lives until the last one goes, so releasing a
//!   handle while another thread is mid-call is well-defined. What is never allowed is using a
//!   handle after your own `_release`.

#![deny(missing_docs)]
#![allow(non_camel_case_types)] // the FFI type names mirror the C header, e.g. `ak_bytes`.

mod blob;
mod client;
mod error;
mod guard;
mod handle;
mod request;
#[cfg(test)]
mod test_support;
// Public, and hidden, for exactly one reason: `runtime::alive_tasks` lets the integration tests
// assert the runtime comes back to rest. Nothing in it is `extern "C"`, so none of it reaches the
// generated header, and so none of it is part of the ABI.
#[doc(hidden)]
pub mod runtime;

pub use client::{ak_client, ak_client_create, ak_client_release};
pub use error::{ak_bytes, ak_bytes_free, ak_bytes_in};
pub use request::{ak_request, ak_request_cancel, ak_request_close_send, ak_request_release};
pub use request::{ak_request_on_event, ak_request_read, ak_request_start, ak_request_write};

/// Result codes returned by every entry point in this crate.
///
/// `0` is success; everything else is negative. There is no positive space: this ABI carries no
/// gRPC status, and an HTTP status is a response header, not a result code.
pub mod status {
    /// The operation succeeded.
    pub const OK: i32 = 0;
    /// A pointer argument that must not be null was null.
    pub const NULL_ARGUMENT: i32 = -1;
    /// A byte buffer was not valid UTF-8 where UTF-8 was required.
    pub const INVALID_UTF8: i32 = -2;
    /// The client configuration was rejected; see the returned error message.
    pub const INVALID_CONFIG: i32 = -3;
    /// The request never reached the server: no connection, or the connection failed before any
    /// response header arrived. See the message on the `COMPLETED` event.
    pub const CONNECTION_FAILED: i32 = -4;
    /// The handle passed to a call has already been freed, or was never valid.
    pub const INVALID_HANDLE: i32 = -5;
    /// The request is not in a state that allows the operation: a second read or write armed while
    /// one is still outstanding, a write after `ak_request_close_send`, or an operation on a
    /// request that has already completed.
    pub const INVALID_STATE: i32 = -6;
    /// Something inside this crate failed in a way that is not the caller's doing; see the message.
    pub const INTERNAL: i32 = -8;
    /// A panic was caught at the FFI boundary, or inside the task driving a request. This is always
    /// a bug in this crate; the message carries whatever the panic payload could be turned into.
    pub const INTERNAL_PANIC: i32 = -9;
    /// The request was cancelled through [`crate::ak_request_cancel`], or by
    /// [`crate::ak_request_release`] before it had completed.
    pub const CANCELLED: i32 = -10;
    /// The configured `Timeout` elapsed while the request was still in flight.
    pub const TIMEOUT: i32 = -11;
    /// The connection failed after the response headers had arrived: a reset stream, a broken
    /// connection, a protocol error. See the message on the `COMPLETED` event.
    pub const TRANSPORT: i32 = -12;
}

/// The `kind` argument of [`ak_request_on_event`].
///
/// [`ak_request_on_event`]: crate::request::ak_request_on_event
pub mod event {
    /// The response headers arrived. `payload` is a key/value blob; the HTTP status is in it under
    /// the `:status` key, as decimal ASCII. `code` is [`crate::status::OK`].
    ///
    /// Always the first event of a successful request, and never emitted more than once.
    pub const RESPONSE_HEADERS: i32 = 1;
    /// The chunk armed by [`crate::ak_request_write`] has been handed to the connection. `payload`
    /// is empty, `code` is [`crate::status::OK`]. It does not mean the bytes reached the server,
    /// only that this crate no longer needs the caller's buffer and one more write may be armed.
    pub const WRITE_DONE: i32 = 2;
    /// The read armed by [`crate::ak_request_read`] produced body bytes. `payload` is the chunk,
    /// borrowed for the duration of the call; `code` is [`crate::status::OK`].
    ///
    /// A chunk is whatever the connection delivered as one DATA frame's worth of body, not a
    /// message: there is no framing at this level, so a reader must handle any split.
    pub const READ_DONE: i32 = 3;
    /// The request is over, and no further callback will be made for it.
    ///
    /// `code` is [`crate::status::OK`] when the response ended cleanly, and `payload` is then the
    /// trailers as a key/value blob - possibly empty, which is what a clean early end of stream
    /// looks like. Otherwise `code` is one of the negative statuses and `payload` is the failure,
    /// rendered as a UTF-8 message with its whole cause chain flattened into it.
    pub const COMPLETED: i32 = 4;
}
