//! C ABI over the ArmoniK Rust transport, for host applications that cannot link Rust directly.
//!
//! # Scope
//!
//! This crate is deliberately thin. It knows nothing about ArmoniK's services or RPCs — every call
//! is addressed by an opaque method path and moves opaque bytes. Configuration parsing, TLS, proxy
//! handling and retry policy all live in
//! [`armonik_transport`](https://docs.rs/armonik-transport); this crate only adapts that connection
//! layer to a C ABI. It is never published to a registry: it is built as a `cdylib` and shipped
//! alongside whatever binds to it.
//!
//! # Design
//!
//! Nothing here calls back into the caller's code — no function pointer ever crosses the boundary
//! inwards. This crate buffers messages, logs and the final status into bounded queues that the
//! caller drains by polling, and signals an OS event when there is something new to read. That
//! removes every hazard that would come with a foreign runtime having to attach one of its threads
//! to answer a call from here, and with a caller-supplied callback being required not to panic,
//! block or re-enter.
//!
//! See `include/armonik_transport_ffi.h` for the full contract, generated by `cbindgen` from the
//! `pub extern "C"` items below and committed so an ABI change shows up in review.
//!
//! # Safety discipline
//!
//! - Every `extern "C"` entry point is wrapped by one of this crate's internal
//!   `catch_unwind_status`/`catch_unwind_status_only`/`catch_unwind_void` helpers, so a panic can
//!   never cross the ABI boundary.
//! - Every allocation handed to the caller travels as an [`error::ak_bytes`] and must be released
//!   through [`error::ak_bytes_free`] exactly once.
//! - Every opaque handle ([`client::ak_client`], [`call::ak_call`]) is only ever touched behind a
//!   raw pointer that the caller must not alias or use after the matching `_free` call; see each
//!   type's documentation for its exact contract.

#![deny(missing_docs)]
#![allow(non_camel_case_types)] // the FFI type names mirror the C header, e.g. `ak_bytes`.

mod blob;
mod call;
mod client;
mod codec;
mod config;
mod error;
mod event;
mod guard;
mod handle;
mod log;
mod metadata;
#[cfg(test)]
mod test_support;
// Public, and hidden, for exactly one reason: `runtime::alive_tasks` lets the integration tests
// assert the runtime comes back to rest. Nothing in it is `extern "C"`, so none of it reaches the
// generated header, and so none of it is part of the ABI.
#[doc(hidden)]
pub mod runtime;

pub use call::{ak_call, ak_call_cancel, ak_call_close_send};
pub use call::{ak_call_free, ak_call_start, ak_call_status, ak_call_try_headers};
pub use call::{ak_call_try_recv, ak_call_try_send, ak_call_wait_handle};
pub use client::{ak_client, ak_client_create, ak_client_free};
pub use error::{ak_bytes, ak_bytes_free, ak_bytes_in};
pub use log::{ak_log_drain, ak_log_init};

/// Result codes returned by every entry point in this crate.
///
/// `0` is success. A positive value is an [`armonik_transport::reexports::tonic::Code`] as defined
/// by gRPC, returned when the failure came from the RPC itself. A negative value is local to this
/// crate — a problem in the FFI layer itself, before or outside of any gRPC status.
pub mod status {
    /// The call succeeded.
    pub const OK: i32 = 0;
    /// A pointer argument that must not be null was null.
    pub const NULL_ARGUMENT: i32 = -1;
    /// A byte buffer was not valid UTF-8 where UTF-8 was required.
    pub const INVALID_UTF8: i32 = -2;
    /// The client configuration was rejected; see the returned error message.
    pub const INVALID_CONFIG: i32 = -3;
    /// Connecting to the endpoint failed; see the returned error message.
    pub const CONNECTION_FAILED: i32 = -4;
    /// The handle passed to a call has already been freed, or was never valid.
    pub const INVALID_HANDLE: i32 = -5;
    /// The call is not in a state that allows the requested operation, e.g. sending after
    /// [`crate::ak_call_close_send`], or a second concurrent call to a function that is not safe
    /// to call concurrently with itself.
    pub const INVALID_STATE: i32 = -6;
    /// A send queue is full; retry after the event handle is signalled.
    pub const WOULD_BLOCK: i32 = -7;
    /// An operating-system resource this crate needed could not be obtained; see the returned error
    /// message.
    pub const INTERNAL: i32 = -8;
    /// A panic was caught at the FFI boundary. This is always a bug in this crate; the message
    /// carries whatever the panic payload could be turned into.
    pub const INTERNAL_PANIC: i32 = -9;

    /// Turn a gRPC status code into the positive status this crate reports for it.
    pub(crate) fn from_grpc(code: armonik_transport::reexports::tonic::Code) -> i32 {
        code as i32
    }
}
