// This file is part of the ArmoniK project
//
// Copyright (C) ANEO, 2021-2026. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License")
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Rendered by csbindgen from armonik-transport-ffi's src/abi.rs and src/lib.rs. Edits here are
// lost: change the Rust, then run `cargo run -p armonik-transport-ffi-bindgen`. The build fails
// while the two differ.

// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace ArmoniK.Api.Client.RustGrpcChannel.Interop
{
    internal static unsafe partial class NativeMethods
    {


        internal const int AK_ABI_VERSION = 1;
        /// <summary>
        ///  The largest worker_threads a runtime is created with; above it, AK_STATUS_INVALID_ARG.
        ///
        ///  A worker is an OS thread, so the useful range is the machine's core count and this is far past
        ///  any of them. The bound exists because the failures past it are not reportable: the runtime
        ///  sizes a per-worker table before creating anything, and near UINT32_MAX that allocation ends the
        ///  process - the one failure no status can report.
        /// </summary>
        internal const uint AK_MAX_WORKER_THREADS = 1024;


        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        internal delegate void ak_runtime_create_callback_delegate(void* runtime_ctx, void* call_ctx, ak_event* @event);



        /// <summary>
        ///  Creates a runtime, synchronously; it starts in AK_RUNTIME_RUNNING. One exists at a time: a
        ///  second create before the first is destroyed is refused with AK_STATUS_INVALID_STATE.
        ///
        ///  # Safety
        ///
        ///  `config` and `out` must be valid for their types, and `callback` must stay callable with
        ///  `runtime_ctx` until the runtime's last event.
        ///  `out_error` must be null or writable for an `ak_error`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ak_runtime_create", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ak_status ak_runtime_create(ak_runtime_config* config, ak_runtime_create_callback_delegate callback, void* runtime_ctx, ulong* @out, ak_error* out_error);

        /// <summary>
        ///  The runtime's state. Synchronous, non-blocking, and callable from any thread, including from
        ///  inside a callback.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ak_runtime_status", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ak_runtime_state ak_runtime_status(ulong runtime);

        /// <summary>
        ///  Closes the start gate and drains. AK_EVENT_SHUTDOWN_COMPLETE follows. Idempotent.
        ///
        ///  # Safety
        ///
        ///  `out_error` must be null or writable for an `ak_error`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ak_runtime_begin_shutdown", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ak_status ak_runtime_begin_shutdown(ulong runtime, ak_error* out_error);

        /// <summary>
        ///  Frees the runtime. Refused before AK_RUNTIME_QUIESCENT, and that is the only reason.
        ///
        ///  Live call and channel handles do not block it: destroy stales every handle of this runtime at
        ///  once, and a later downcall on one returns AK_STATUS_HANDLE_STALE. A handle names runtime-owned
        ///  state, so the runtime may reclaim it; a payload or a lent buffer is memory the host may still
        ///  be reading or writing, so only the host can end it.
        ///
        ///  # Safety
        ///
        ///  `out_error` must be null or writable for an `ak_error`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ak_runtime_destroy", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ak_status ak_runtime_destroy(ulong runtime, ak_error* out_error);

        /// <summary>
        ///  What the runtime-wide byte ceiling is holding. Synchronous, non-blocking and observational: it
        ///  changes nothing.
        ///
        ///  # Safety
        ///
        ///  `out` must be writable.
        ///  `out_error` must be null or writable for an `ak_error`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ak_runtime_memory_usage", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ak_status ak_runtime_memory_usage(ulong runtime, ak_memory_usage* @out, ak_error* out_error);

        /// <summary>
        ///  Creates a channel on an endpoint, configured by a JSON document. Synchronous and performs no
        ///  I/O: no name is resolved and no socket opened until the channel's first call. A bad endpoint or
        ///  a bad document is AK_STATUS_INVALID_ARG, and so is a null out or a null slice with a non-zero
        ///  length; a runtime handle that names nothing is AK_STATUS_HANDLE_STALE, and one that is shutting
        ///  down is AK_STATUS_INVALID_STATE.
        ///
        ///  The endpoint is its own argument, as UTF-8 - "http://host:port". It is the one value a channel
        ///  cannot be created without, so it is not an option that happens to be mandatory: every option of
        ///  the document has a default, and `{}` is a valid configuration.
        ///
        ///  The document is structured and typed, and a JSON schema states it: objects nest, a number is a
        ///  number and not a string spelled like one, and an option spelled wrong is refused rather than
        ///  ignored. It carries UserAgent, MaxReceiveMessageSize, DeliveryCredits, MaxSendsInFlight, and
        ///  a Transport object holding ConnectTimeoutSeconds.
        ///
        ///  The two windows mirror each other. DeliveryCredits bounds the payloads of one call outstanding
        ///  at once - the terminal status takes no credit, so a host holds at most one more - and the host
        ///  chooses it because the host is what has to hold them; MaxSendsInFlight bounds the buffers one
        ///  call may have out, counting those being filled and those awaiting their WRITE_DONE. Both
        ///  default to 1, and the schema states the range either may take.
        ///
        ///  A call whose payloads the host does not consume reads a few messages past its spent credits,
        ///  which the engine holds outside what the credits count, and then stops reading its stream; what
        ///  its peer sends meanwhile holds the connection's HTTP/2 window. Every call of the channel shares
        ///  that window, so enough unread calls stop the others receiving.
        ///
        ///  # Safety
        ///
        ///  `config_json` must point at its bytes for the duration of the call, and `out` must be
        ///  writable.
        ///  `out_error` must be null or writable for an `ak_error`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ak_channel_create", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ak_status ak_channel_create(ulong runtime, ak_bytes_in endpoint, ak_bytes_in config_json, ulong* @out, ak_error* out_error);

        /// <summary>
        ///  Frees the channel, cancelling its calls first.
        ///
        ///  The cancellation is not a courtesy: the channel is closing from this moment and no closing
        ///  channel may have an active call, so the latch is what makes the drain this library's business
        ///  rather than something the host must provoke. A call parked on a delivery credit is the case
        ///  that needs it - it is not watching the transport, so closing the session alone would never
        ///  reach it.
        ///
        ///  Idempotent. The channel goes to AK_CHANNEL_CLOSING, and once its last call has reached its
        ///  terminal the handle is reclaimed: from then on ak_channel_status answers AK_CHANNEL_NONE and
        ///  ak_call_start AK_STATUS_HANDLE_STALE. Until then the channel starts no further call -
        ///  ak_call_start on it answers AK_STATUS_INVALID_STATE - and a host following the drain reads
        ///  CLOSING and then NONE, with CLOSED at most in passing. An idle channel is reclaimed before this
        ///  returns.
        ///
        ///  A channel the runtime's shutdown closed is not reclaimed: it stays AK_CHANNEL_CLOSED, and
        ///  nameable, until this is called or the runtime is destroyed.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ak_channel_release", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void ak_channel_release(ulong channel);

        /// <summary>
        ///  How far along a channel's closing is. Answers NONE for a handle this library does not know,
        ///  which a released channel is once its last call has ended.
        ///
        ///  What ends CLOSING is this library's own bookkeeping - the last call of the channel reaching
        ///  its terminal - so a host watching the drain has nothing to do but read. In particular CLOSED
        ///  does not wait for the host to consume what it has been given: a call past its terminal still
        ///  owes its payloads, and the channel is closed regardless.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ak_channel_status", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ak_channel_state ak_channel_status(ulong channel);

        /// <summary>
        ///  Starts a call on a channel.
        ///
        ///  There is no ak_call_release, on purpose. Every resource a call lends out is given back through
        ///  something the runtime already observes, so it knows when a terminal call owes nothing and takes
        ///  the handle back itself. Two consequences: the handle goes stale at a moment the host does not
        ///  choose, and abandoning a call is still ak_call_cancel followed by consuming through to the
        ///  terminal - dropping a payload on the floor keeps the runtime alive.
        ///
        ///  # Safety
        ///
        ///  `options` must be valid for its type and its byte views, and `out` must be writable.
        ///  `out_error` must be null or writable for an `ak_error`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ak_call_start", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ak_status ak_call_start(ulong channel, ak_call_start_options* options, void* call_ctx, ulong* @out, ak_error* out_error);

        /// <summary>
        ///  Lends a buffer out of the call's arena to serialize into. The exact length is known before the
        ///  first byte is written, so no growable writer is needed.
        ///
        ///  One unfilled buffer at a time, whatever max_sends_in_flight says: asking for a second while
        ///  still holding one is AK_STATUS_INVALID_STATE, a host bug rather than backpressure. The window
        ///  counts those being filled and those committed and awaiting their WRITE_DONE; when it is full
        ///  the refusal is AK_STATUS_SLOT_BUSY, whose wake-up is this call's next WRITE_DONE. That wake-up
        ///  is only meaningful because a host eligible to ask holds nothing. AK_STATUS_BUDGET_BUSY is the
        ///  runtime-wide ceiling, and has no single event announcing room: poll ak_runtime_memory_usage.
        ///  AK_STATUS_MESSAGE_TOO_LARGE is permanent. An allocator failure for the buffer is
        ///  AK_STATUS_INTERNAL: that lend is refused, and nothing else fails. A call that is over, or whose
        ///  cancellation has been requested, lends nothing: AK_STATUS_INVALID_STATE. On every refusal no
        ///  buffer is lent and `*out` is untouched.
        ///
        ///  # Safety
        ///
        ///  `out` must be writable.
        ///  `out_error` must be null or writable for an `ak_error`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ak_get_call_buffer", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ak_status ak_get_call_buffer(ulong call, nuint len, ak_buffer* @out, ak_error* out_error);

        /// <summary>
        ///  Commits a lent buffer as the next message. Ownership passes back to this library.
        ///
        ///  AK_EVENT_WRITE_DONE settles an accepted send and frees its slot from the moment the event is
        ///  emitted, not when the callback returns - so a host woken by it may ask for a buffer from inside
        ///  the callback. It says nothing about the network: the message may have been written, or
        ///  abandoned because the call was cancelled. It arrives exactly once per accepted send, in send
        ///  order, and always before the terminal.
        ///
        ///  Refused with AK_STATUS_INVALID_STATE once the call is over or its cancellation has been
        ///  requested, and after ak_call_end_send. The buffer then stays the host's, to give back with
        ///  ak_return_call_buffer.
        ///
        ///  # Safety
        ///
        ///  `buffer` must be one this call lent and the host has not given back.
        ///  `out_error` must be null or writable for an `ak_error`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ak_call_send_message", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ak_status ak_call_send_message(ulong call, ak_buffer buffer, ak_error* out_error);

        /// <summary>
        ///  Gives a lent buffer back unused. Legal on a cancelled or terminal call: it is the only exit for
        ///  a buffer whose send is refused, and the call is not reclaimed until it happens.
        ///
        ///  Takes no call handle: the buffer determines its call. A refused ak_call_send_message therefore
        ///  leaves the buffer with the host, exactly as it was lent.
        ///
        ///  # Safety
        ///
        ///  `buffer` must be one this call lent and the host has not given back.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ak_return_call_buffer", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void ak_return_call_buffer(ak_buffer buffer);

        /// <summary>
        ///  Signals end of sending. No ak_call_send_message after this: a send that comes after the end,
        ///  and a second end, answer AK_STATUS_INVALID_STATE.
        ///
        ///  An end that comes while an ak_call_send_message has not yet returned on another thread - from
        ///  inside that send's own AK_EVENT_WRITE_DONE, which may arrive first - waits for it to return, so
        ///  it never goes ahead of a message the host has been told left.
        ///
        ///  # Safety
        ///
        ///  `out_error` must be null or writable for an `ak_error`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ak_call_end_send", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ak_status ak_call_end_send(ulong call, ak_error* out_error);

        /// <summary>
        ///  Cancels the call, which then reaches a terminal - carrying CANCELLED, unless the peer's own
        ///  status was already in.
        ///
        ///  Asynchronous: the request takes effect when the call's task observes it, so callbacks already
        ///  committed may still arrive after this returns, and a status the peer had already sent is the
        ///  one delivered. INITIAL_METADATA is never skipped.
        ///
        ///  # Safety
        ///
        ///  `out_error` must be null or writable for an `ak_error`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ak_call_cancel", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ak_status ak_call_cancel(ulong call, ak_error* out_error);

        /// <summary>
        ///  What the call still owes. Purely observational; it is legal never to call it. It exists because
        ///  without a release downcall nothing reports a forgotten ak_return_call_buffer synchronously.
        ///
        ///  # Safety
        ///
        ///  `out` must be writable.
        ///  `out_error` must be null or writable for an `ak_error`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ak_call_debt_of", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ak_status ak_call_debt_of(ulong call, ak_call_debt* @out, ak_error* out_error);

        [DllImport(__DllName, EntryPoint = "ak_abi_version", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int ak_abi_version();

        /// <summary>
        ///  Signals that the host has consumed an event's payload. Two things at once:
        ///
        ///  1. frees the native memory;
        ///  2. arms reception of the next event for that call.
        ///
        ///  At most one non-consumed payload per call by default: while the host owes it, the runtime
        ///  withholds the next data callback. Only a terminal still goes out with the credit spent.
        ///
        ///  The host MUST give a call's payloads back in delivery order: with several outstanding, the
        ///  oldest is the next one consumed. Another order is not refused - this library frees whichever
        ///  owner it is given - but the guarantees this header states are proved for this order alone.
        ///
        ///  Remains legal, and required, after the terminal: the call is not reclaimed until it happens.
        ///
        ///  # Safety
        ///
        ///  `payload` must be one this library delivered and the host has not consumed.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ak_event_consumed", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void ak_event_consumed(ak_bytes payload);

        /// <summary>
        ///  Frees an ak_error's detail. A no-op when detail.owner is NULL, so a host may route every error
        ///  through it. Legal in any runtime state, and after ak_runtime_destroy.
        ///
        ///  # Safety
        ///
        ///  `detail` must be one this library wrote into an ak_error and the host has not released.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ak_error_release", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void ak_error_release(ak_bytes detail);


    }

    /// <summary>
    ///  Bytes the host lends this library for the duration of one downcall.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct ak_bytes_in
    {
        public byte* ptr;
        public nuint len;
    }

    /// <summary>
    ///  Owned by the host after reception, until ak_event_consumed.
    ///
    ///  owner, not ptr, identifies the allocation: the view may be a slice of a larger one. owner ==
    ///  NULL means unowned, never "empty" - a zero-length payload that took a delivery credit carries a
    ///  real owner and MUST be consumed, because the credit comes back with the acquittal and not with
    ///  the bytes.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct ak_bytes
    {
        public byte* ptr;
        public nuint len;
        public void* owner;
    }

    /// <summary>
    ///  Lent by ak_get_call_buffer out of the call's arena. The host writes len bytes and gives it back
    ///  exactly once, by ak_call_send_message or ak_return_call_buffer. This library never reclaims a
    ///  lent buffer on its own - not on cancellation, not on channel close - which is what removes the
    ///  race between a writing thread and a cancelling one.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct ak_buffer
    {
        public byte* ptr;
        public nuint len;
        public void* owner;
    }

    /// <summary>
    ///  On the callback's stack; no lifecycle of its own. The payload is owned when owner is not NULL.
    ///
    ///  WRITE_DONE, SHUTDOWN_COMPLETE and RESOURCES_RELEASED carry no payload: ptr == NULL, len == 0,
    ///  owner == NULL. ak_event_consumed on such a payload is a no-op, so a host may route every event
    ///  through one path.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct ak_event
    {
        public ak_event_kind kind;
        public ak_bytes payload;
        /// <summary>
        ///  gRPC status for AK_EVENT_STATUS, ak_head_origin for AK_EVENT_INITIAL_METADATA, zero on
        ///  every other event.
        /// </summary>
        public int status_code;
        /// <summary>
        ///  AK_EVENT_SHUTDOWN_COMPLETE only.
        /// </summary>
        public ak_host_debt host_debt;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct ak_runtime_config
    {
        public uint struct_size;
        /// <summary>
        ///  Zero leaves the choice to the runtime; at most AK_MAX_WORKER_THREADS.
        /// </summary>
        public uint worker_threads;
        /// <summary>
        ///  Bytes lent buffers may occupy at once. Zero, or more than this library can lend, asks for
        ///  its own ceiling: four gigabytes, or half the address space where that is smaller - the gRPC
        ///  length prefix and the allocator between them admit no more, so a budget above it is one no
        ///  single lend could draw on.
        /// </summary>
        public ulong memory_ceiling;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct ak_memory_usage
    {
        /// <summary>
        ///  Occupied against the ceiling, atomic snapshot.
        /// </summary>
        public ulong bytes_used;
        /// <summary>
        ///  The limit in force, which is what was configured or this library's own where that is
        ///  smaller. Never zero.
        /// </summary>
        public ulong ceiling;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct ak_call_start_options
    {
        public uint struct_size;
        /// <summary>
        ///  "/Service/Method", not NUL-terminated.
        /// </summary>
        public ak_bytes_in method;
        /// <summary>
        ///  A metadata blob - a uint32_t count, then each key and each value as a uint32_t length and
        ///  its bytes; may be empty.
        /// </summary>
        public ak_bytes_in metadata;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct ak_call_debt
    {
        /// <summary>
        ///  Delivered, not yet ak_event_consumed.
        /// </summary>
        public uint payloads_owed;
        /// <summary>
        ///  Out of the arena, not yet given back.
        /// </summary>
        public uint buffers_lent;
        /// <summary>
        ///  The runtime's own, informational.
        /// </summary>
        public uint callbacks_in_flight;
        /// <summary>
        ///  0 or 1.
        /// </summary>
        public int terminal_delivered;
    }

    /// <summary>
    ///  Filled by this library, read by the host, and written only when the status is not
    ///  AK_STATUS_OK. Fixed layout, with no size prefix: ak_abi_version() is the agreement.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct ak_error
    {
        public ak_error_kind kind;
        /// <summary>
        ///  UTF-8, the cause chain flattened into one message. detail.owner == NULL means there is
        ///  nothing to free. Released by ak_error_release, never by ak_event_consumed.
        /// </summary>
        public ak_bytes detail;
    }


    /// <summary>
    ///  Returned by every entry point that can fail. ak_event_consumed, ak_return_call_buffer and
    ///  ak_channel_release are void because a wrong token is a host bug the ABI cannot report anywhere
    ///  useful; ak_runtime_status, ak_channel_status and ak_abi_version return their answer.
    /// </summary>
    internal enum ak_status : int
    {
        AK_STATUS_OK = 0,
        /// <summary>
        ///  The object is gone; the token names nothing.
        /// </summary>
        AK_STATUS_HANDLE_STALE = 1,
        /// <summary>
        ///  This call's send window is full - backpressure, not an error; retry when a WRITE_DONE
        ///  arrives. That acquittal says this library has taken the message and the host's buffer is
        ///  free; it says nothing about the peer, and does not wait on one - the wake-up is promised,
        ///  its timing is not.
        /// </summary>
        AK_STATUS_SLOT_BUSY = 2,
        /// <summary>
        ///  A null pointer, or a struct whose size prefix does not match any known version.
        /// </summary>
        AK_STATUS_INVALID_ARG = 3,
        /// <summary>
        ///  A fault the ABI cannot attribute.
        /// </summary>
        AK_STATUS_INTERNAL = 4,
        /// <summary>
        ///  The runtime-wide byte ceiling is reached - poll ak_runtime_memory_usage and retry.
        /// </summary>
        AK_STATUS_BUDGET_BUSY = 5,
        /// <summary>
        ///  A valid handle at the wrong moment: a send after the terminal, a start while stopping, a
        ///  destroy before quiescence. A guard refused, which is not a fault.
        /// </summary>
        AK_STATUS_INVALID_STATE = 6,
        /// <summary>
        ///  The length exceeds the ceiling itself, so no return by anyone will ever make room.
        ///  Permanent; do not retry.
        /// </summary>
        AK_STATUS_MESSAGE_TOO_LARGE = 7,
    }

    /// <summary>
    ///  Only QUIESCENT permits ak_runtime_destroy or unloading the library. The host reaches it by
    ///  acting, not by waiting: while it still holds something the status stays STOPPED, and the
    ///  AK_EVENT_SHUTDOWN_COMPLETE callback says so through its host_debt field. Polling for QUIESCENT
    ///  before returning what it holds is therefore a deadlock.
    ///
    ///  NONE is what keeps a handle a token rather than a pointer: a handle this library does not
    ///  know - never created, or reclaimed by ak_runtime_destroy - is reported, not resolved.
    ///  It is not QUIESCENT, which would tell a host that passed a channel handle by mistake that it
    ///  may destroy the runtime and unload the library while one is running.
    /// </summary>
    internal enum ak_runtime_state : int
    {
        /// <summary>
        ///  This library knows no such runtime.
        /// </summary>
        AK_RUNTIME_NONE = 0,
        /// <summary>
        ///  Operational, accepts channels and calls.
        /// </summary>
        AK_RUNTIME_RUNNING = 1,
        /// <summary>
        ///  Start gate closed, channels closing.
        /// </summary>
        AK_RUNTIME_GRPC_STOPPING = 2,
        /// <summary>
        ///  The gRPC side is done; the host may still hold memory.
        /// </summary>
        AK_RUNTIME_GRPC_STOPPED = 3,
        /// <summary>
        ///  And nothing of it is outstanding either.
        /// </summary>
        AK_RUNTIME_QUIESCENT = 4,
        /// <summary>
        ///  Quiescence impossible, destroy refused. Reported when the status itself cannot be read,
        ///  when the task driving the shutdown dies, and when that shutdown cannot get a thread of its
        ///  own: the three ways the step to QUIESCENT stops being reachable. A shutdown that is merely
        ///  slow stays GRPC_STOPPING.
        /// </summary>
        AK_RUNTIME_FAILED_UNQUIESCED = 5,
    }

    internal enum ak_event_kind : int
    {
        /// <summary>
        ///  payload = metadata blob (owned), status_code = its origin.
        /// </summary>
        AK_EVENT_INITIAL_METADATA = 1,
        /// <summary>
        ///  payload = message bytes (owned).
        /// </summary>
        AK_EVENT_MESSAGE = 2,
        /// <summary>
        ///  Terminal - payload = reason + trailers (owned).
        /// </summary>
        AK_EVENT_STATUS = 3,
        /// <summary>
        ///  An accepted send is settled; its slot is already free.
        /// </summary>
        AK_EVENT_WRITE_DONE = 4,
        /// <summary>
        ///  The runtime has stopped running.
        /// </summary>
        AK_EVENT_SHUTDOWN_COMPLETE = 5,
        /// <summary>
        ///  And now nothing of it is outstanding.
        /// </summary>
        AK_EVENT_RESOURCES_RELEASED = 6,
    }

    /// <summary>
    ///  Carried by AK_EVENT_INITIAL_METADATA in status_code: where the head came from. The event comes
    ///  first on every call, and its metadata is empty unless the peer's headers were delivered. Zero
    ///  is the peer's headers, so a host that ignores the field takes every head for the peer's.
    /// </summary>
    internal enum ak_head_origin : int
    {
        /// <summary>
        ///  The peer's response headers.
        /// </summary>
        AK_HEAD_RECEIVED = 0,
        /// <summary>
        ///  A response came and delivered no head - the Trailers-Only shape, or an answer refused
        ///  before its body; the terminal is the call's status, the peer's unless the call was stopped
        ///  here first.
        /// </summary>
        AK_HEAD_TRAILERS_ONLY = 1,
        /// <summary>
        ///  No response reached the call.
        /// </summary>
        AK_HEAD_NO_RESPONSE = 2,
    }

    /// <summary>
    ///  Carried by AK_EVENT_SHUTDOWN_COMPLETE and by nothing else.
    /// </summary>
    internal enum ak_host_debt : int
    {
        /// <summary>
        ///  Nothing of ours is in your hands; no second event.
        /// </summary>
        AK_HOST_NOTHING_TO_RETURN = 0,
        /// <summary>
        ///  Consume the payloads, return the buffers; AK_EVENT_RESOURCES_RELEASED follows.
        /// </summary>
        AK_HOST_MUST_RETURN = 1,
    }

    /// <summary>
    ///  How far along a channel's closing is. A handle this library no longer knows reads as NONE,
    ///  which is also what an unopened one reads as: neither names a channel.
    /// </summary>
    internal enum ak_channel_state : int
    {
        AK_CHANNEL_NONE = 0,
        /// <summary>
        ///  Takes calls.
        /// </summary>
        AK_CHANNEL_OPEN = 1,
        /// <summary>
        ///  Released, its calls draining.
        /// </summary>
        AK_CHANNEL_CLOSING = 2,
        /// <summary>
        ///  And nothing of it is active any more.
        /// </summary>
        AK_CHANNEL_CLOSED = 3,
    }

    /// <summary>
    ///  Why a fallible entry point refused, beyond what its status says.
    /// </summary>
    internal enum ak_error_kind : int
    {
        /// <summary>
        ///  No family: the status says what happened - backpressure, a request too large for the
        ///  ceiling, a fault this library cannot attribute. Zero, so a zero-initialized ak_error reads
        ///  as nothing more to say.
        /// </summary>
        AK_ERROR_NONE = 0,
        /// <summary>
        ///  The configuration document or the endpoint, before any socket.
        /// </summary>
        AK_ERROR_CONFIG = 1,
        /// <summary>
        ///  DNS, TCP, TLS handshake.
        /// </summary>
        AK_ERROR_CONNECTION = 2,
        /// <summary>
        ///  HTTP/2 or gRPC framing, after a connection.
        /// </summary>
        AK_ERROR_TRANSPORT = 3,
        AK_ERROR_TIMEOUT = 4,
        AK_ERROR_CANCELLED = 5,
        /// <summary>
        ///  The host used the ABI in a way it does not admit: a null pointer, a handle that names
        ///  nothing, a downcall at a moment its object refuses it.
        /// </summary>
        AK_ERROR_USAGE = 6,
    }


}
