// This file is part of the ArmoniK project
//
// Copyright (C) ANEO, 2021-2026. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License")
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Rendered by csbindgen from armonik-transport-ffi's src/abi.rs and src/lib.rs. Edits here are
// lost: change the Rust, then run `cargo run -p armonik-transport-ffi-bindgen`. The build fails
// while the two differ.

// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace ArmoniK.Api.Client.RustGrpcChannel.Interop
{
    internal static unsafe partial class NativeMethods
    {


        /// <summary>
        ///  In ak_log_record.level: 1 is the most severe and 5 the most verbose. A host maps them to its
        ///  own, and has no use for a value it does not know.
        /// </summary>
        internal const uint AK_LOG_ERROR = 1;
        internal const uint AK_LOG_WARN = 2;
        internal const uint AK_LOG_INFO = 3;
        internal const uint AK_LOG_DEBUG = 4;
        internal const uint AK_LOG_TRACE = 5;
        /// <summary>
        ///  In ak_call_start_options.flags: timeout_ns states the call's deadline.
        /// </summary>
        internal const uint AK_CALL_HAS_DEADLINE = 1;
        /// <summary>
        ///  In ak_call_start_options.flags: the response is at most one message, as on a unary or a
        ///  client-streaming method. A server that sends a second one ends the call with the gRPC status
        ///  INTERNAL, and the second is neither delivered nor charged to the runtime's memory. The status
        ///  that follows the message is read whatever the runtime's first memory threshold says, so a host
        ///  may hold the message until the status is in.
        /// </summary>
        internal const uint AK_CALL_ONE_RESPONSE = 2;
        /// <summary>
        ///  In ak_call_start_options.flags: the request is exactly one message, as on a unary or a
        ///  server-streaming method. ak_call_send_message also ends the sending, ak_call_end_send is
        ///  refused with AK_STATUS_INVALID_STATE, and no AK_EVENT_WRITE_DONE comes: the send is settled
        ///  when it is committed, and an ak_get_call_buffer after it answers AK_STATUS_INVALID_STATE. The
        ///  call sends nothing until its commit, and nothing watches its deadline before: a commit past it
        ///  is accepted and the call ends DEADLINE_EXCEEDED, and a call never committed ends at its
        ///  cancellation.
        /// </summary>
        internal const uint AK_CALL_ONE_REQUEST = 4;
        /// <summary>
        ///  In ak_call_start_options.flags: the call waits for the channel to open a connection rather than
        ///  end UNAVAILABLE when it cannot reach its server, as gRPC's wait-for-ready has it. The channel
        ///  dials again, backing off as gRPC's connection backoff does, and the call goes out on the first
        ///  connection it opens. The wait ends at the call's deadline (DEADLINE_EXCEEDED), on its
        ///  cancellation, or when its channel is released; otherwise it lasts as long as the server stays
        ///  out of reach. A call that reached a connection is not helped: what breaks it after that ends it
        ///  as it ends any other.
        /// </summary>
        internal const uint AK_CALL_WAIT_FOR_READY = 8;
        internal const int AK_ABI_VERSION = 1;


        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        internal delegate void ak_runtime_create_callback_delegate(void* runtime_ctx, void* call_ctx, ak_event* events, nuint count);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        internal delegate void ak_runtime_create_from_callback_delegate(void* runtime_ctx, void* call_ctx, ak_event* events, nuint count);



        /// <summary>
        ///  Creates a runtime, synchronously; it starts in AK_RUNTIME_RUNNING. One exists at a time: a
        ///  second create before the first is destroyed is refused with AK_STATUS_INVALID_STATE. Each
        ///  channel created on it runs on a thread of its own, so that a call never moves between threads.
        ///  AK_RUNTIME_QUIESCENT means those threads are gone too.
        ///
        ///  # Safety
        ///
        ///  `config` and `out` must be valid for their types, and `callback` must stay callable with
        ///  `runtime_ctx` until the runtime's last event. `config.log_callback`, when it is set, must stay
        ///  callable with `config.log_ctx` until `ak_runtime_destroy` returns, or until this call returns
        ///  when it refuses.
        ///  `out_error` must be null or writable for an `ak_error`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ak_runtime_create", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ak_status ak_runtime_create(ak_runtime_config* config, ak_runtime_create_callback_delegate callback, void* runtime_ctx, ulong* @out, ak_error* out_error);

        /// <summary>
        ///  Creates a runtime, as ak_runtime_create does, from the sources `config` lists: read in order,
        ///  a later one over an earlier one option by option, into the vocabulary of runtime.schema.json -
        ///  the endpoint, the memory ceilings, and the channel defaults every channel's own document is
        ///  merged over.
        ///
        ///  What is malformed in `config` itself - a kind it does not name, a reserved field or a flag it
        ///  does not know, a value on an environment source, a byte view that is null with a length or not
        ///  UTF-8 - is AK_STATUS_INVALID_ARG before any source is read. A source
        ///  that is refused is AK_STATUS_INVALID_ARG too, its message naming the source and the key's path,
        ///  never the value; so is a loaded option the runtime cannot be created with: a ceiling of zero,
        ///  an Endpoint that is not a URI, or channel defaults a channel's own document would be refused
        ///  for.
        ///
        ///  # Safety
        ///
        ///  `config` and `out` must be valid for their types, `config.sources` must point at
        ///  `source_count` sources unless that is zero, and every byte view at its length. `callback` must
        ///  stay callable with `runtime_ctx` until the runtime's last event. `config.log_callback`, when it
        ///  is set, must stay callable with `config.log_ctx` until `ak_runtime_destroy` returns, or until
        ///  this call returns when it refuses.
        ///  `out_error` must be null or writable for an `ak_error`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ak_runtime_create_from", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ak_status ak_runtime_create_from(ak_config* config, ak_runtime_create_from_callback_delegate callback, void* runtime_ctx, ulong* @out, ak_error* out_error);

        /// <summary>
        ///  The runtime's state. Synchronous, non-blocking, and callable from any thread, including from
        ///  inside a callback.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ak_runtime_status", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ak_runtime_state ak_runtime_status(ulong runtime);

        /// <summary>
        ///  Closes the start gate and drains. AK_EVENT_SHUTDOWN_COMPLETE follows. Idempotent.
        ///
        ///  # Safety
        ///
        ///  `out_error` must be null or writable for an `ak_error`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ak_runtime_begin_shutdown", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ak_status ak_runtime_begin_shutdown(ulong runtime, ak_error* out_error);

        /// <summary>
        ///  Frees the runtime. Refused before AK_RUNTIME_QUIESCENT, and that is the only reason.
        ///
        ///  Live call and channel handles do not block it: destroy stales every handle of this runtime at
        ///  once, and a later downcall on one returns AK_STATUS_HANDLE_STALE. A handle names runtime-owned
        ///  state, so the runtime may reclaim it; a payload or a lent buffer is memory the host may still
        ///  be reading or writing, so only the host can end it.
        ///
        ///  # Safety
        ///
        ///  `out_error` must be null or writable for an `ak_error`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ak_runtime_destroy", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ak_status ak_runtime_destroy(ulong runtime, ak_error* out_error);

        /// <summary>
        ///  What the runtime-wide byte ceiling is holding. Synchronous, non-blocking and observational: it
        ///  changes nothing.
        ///
        ///  # Safety
        ///
        ///  `out` must be writable.
        ///  `out_error` must be null or writable for an `ak_error`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ak_runtime_memory_usage", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ak_status ak_runtime_memory_usage(ulong runtime, ak_memory_usage* @out, ak_error* out_error);

        /// <summary>
        ///  Creates a channel on an endpoint, configured by a JSON document. Synchronous: it reads the
        ///  certificate files the document names, and resolves no name and opens no socket until the
        ///  channel's first call. A bad endpoint or a bad document is AK_STATUS_INVALID_ARG, a file that
        ///  cannot be read or holds nothing usable included, and so is a null out or a null slice with a
        ///  non-zero length; a runtime handle that names nothing is AK_STATUS_HANDLE_STALE, and one that is
        ///  shutting down is AK_STATUS_INVALID_STATE.
        ///
        ///  The endpoint is its own argument, as UTF-8 - "http://host:port" in the clear, or
        ///  "https://host:port" over TLS. An empty one is the Endpoint of the runtime's configuration, and
        ///  is AK_STATUS_INVALID_ARG when that names none. Every option of the document has a default, and
        ///  `{}` is a valid configuration.
        ///
        ///  The document is structured and typed, and a JSON schema states it: objects nest, and a number is
        ///  a number and not a string spelled like one. A key no option declares is refused by its path,
        ///  at the root of the document as below it. That schema, `options.schema.json`, names each option
        ///  with its type and, where it has them, its range and default.
        ///
        ///  ak_channel_delivery_window reads back the delivery window the channel ended up with.
        ///
        ///  The two windows mirror each other. Grpc.Host.Receive.Window bounds the payloads of one call
        ///  outstanding at once, each taking one credit, one place of the window - the terminal status takes
        ///  none, so a host holds at most one more - and the host chooses it because the host is what has
        ///  to hold them. Grpc.Host.Send.Window
        ///  bounds the buffers one call may have out, counting those being filled and those awaiting their
        ///  WRITE_DONE. Grpc.Host.Receive.Window defaults to 4 and Grpc.Host.Send.Window to 1, and
        ///  the schema states the range either may take.
        ///
        ///  A call whose payloads the host does not consume reads a few messages past its spent credits,
        ///  which the engine holds outside what the credits count, and then stops reading its stream; what
        ///  its peer sends meanwhile holds the connection's HTTP/2 window. Every call of the channel shares
        ///  that window, so enough unread calls stop the others receiving.
        ///
        ///  # Safety
        ///
        ///  `config_json` must point at its bytes for the duration of the call, and `out` must be
        ///  writable.
        ///  `out_error` must be null or writable for an `ak_error`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ak_channel_create", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ak_status ak_channel_create(ulong runtime, ak_bytes_in endpoint, ak_bytes_in config_json, ulong* @out, ak_error* out_error);

        /// <summary>
        ///  Frees the channel, cancelling its calls first.
        ///
        ///  The cancellation is not a courtesy: the channel is closing from this moment and no closing
        ///  channel may have an active call, so the latch is what makes the drain this library's business
        ///  rather than something the host must provoke. A call parked on a delivery credit is the case
        ///  that needs it - it is not watching the transport, so closing the session alone would never
        ///  reach it.
        ///
        ///  Idempotent. The channel goes to AK_CHANNEL_CLOSING, and once its last call has reached its
        ///  terminal the handle is reclaimed: from then on ak_channel_status answers AK_CHANNEL_NONE and
        ///  ak_call_start AK_STATUS_HANDLE_STALE. Until then the channel starts no further call -
        ///  ak_call_start on it answers AK_STATUS_INVALID_STATE - and a host following the drain reads
        ///  CLOSING and then NONE, with CLOSED at most in passing. An idle channel is reclaimed before this
        ///  returns.
        ///
        ///  A channel the runtime's shutdown closed is not reclaimed: it stays AK_CHANNEL_CLOSED, and
        ///  nameable, until this is called or the runtime is destroyed.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ak_channel_release", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void ak_channel_release(ulong channel);

        /// <summary>
        ///  How far along a channel's closing is. Answers NONE for a handle this library does not know,
        ///  which a released channel is once its last call has ended.
        ///
        ///  What ends CLOSING is this library's own bookkeeping - the last call of the channel reaching
        ///  its terminal - so a host watching the drain has nothing to do but read. In particular CLOSED
        ///  does not wait for the host to consume what it has been given: a call past its terminal still
        ///  owes its payloads, and the channel is closed regardless.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ak_channel_status", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ak_channel_state ak_channel_status(ulong channel);

        /// <summary>
        ///  The delivery window a channel was created with: Grpc.Host.Receive.Window as the channel's own
        ///  document, the runtime's channel defaults or this library's default settled it. Fixed for the
        ///  life of the channel.
        ///
        ///  A handle this library does not know is AK_STATUS_HANDLE_STALE, and a null out
        ///  AK_STATUS_INVALID_ARG.
        ///
        ///  # Safety
        ///
        ///  `out` must be writable.
        ///  `out_error` must be null or writable for an `ak_error`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ak_channel_delivery_window", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ak_status ak_channel_delivery_window(ulong channel, uint* @out, ak_error* out_error);

        /// <summary>
        ///  Starts a call on a channel.
        ///
        ///  There is no ak_call_release, on purpose. Every resource a call lends out is given back through
        ///  something the runtime already observes, so it knows when a terminal call owes nothing and takes
        ///  the handle back itself. Two consequences: the handle goes stale at a moment the host does not
        ///  choose, and abandoning a call is still ak_call_cancel followed by consuming through to the
        ///  terminal - dropping a payload on the floor keeps the runtime alive.
        ///
        ///  # Safety
        ///
        ///  `options` must be valid for its type and its byte views, and `out` must be writable.
        ///  `out_error` must be null or writable for an `ak_error`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ak_call_start", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ak_status ak_call_start(ulong channel, ak_call_start_options* options, void* call_ctx, ulong* @out, ak_error* out_error);

        /// <summary>
        ///  Lends a buffer out of the call's arena to serialize into, of `len` bytes at most: the host
        ///  writes from its start and says how many bytes it wrote when it commits it. The buffer holds
        ///  whatever the allocator, or the last message the channel lent it for, left there, never read:
        ///  only the bytes the host says it wrote are sent.
        ///  Writing past `len` is an overrun, which the commit or the return may detect by the bytes this
        ///  library put after the end: a write that changes them is AK_STATUS_CORRUPTED, and the runtime
        ///  shuts down. A write that leaves them as they were goes unseen.
        ///
        ///  One unfilled buffer at a time, whatever Grpc.Host.Send.Window says: asking for a second while
        ///  still holding one, or while an earlier lend of the call has not returned, is
        ///  AK_STATUS_INVALID_STATE, a host bug rather than backpressure. The window
        ///  counts those being filled and those committed and awaiting their WRITE_DONE; when it is full
        ///  the refusal is AK_STATUS_SLOT_BUSY, whose wake-up is this call's next WRITE_DONE. That wake-up
        ///  is only meaningful because a host eligible to ask holds nothing. AK_STATUS_BUDGET_BUSY is the
        ///  runtime-wide ceiling, whose wake-up is the call's next AK_EVENT_BUDGET_WAKE. A host retries
        ///  only after the refused lend has returned: until then a retry can meet AK_STATUS_INVALID_STATE.
        ///  AK_STATUS_MESSAGE_TOO_LARGE is permanent. A length of zero is AK_STATUS_INVALID_ARG: an empty
        ///  message needs no buffer, and ak_call_send_message sends one with none. An allocator failure for
        ///  the buffer is AK_STATUS_INTERNAL: that lend is refused, and nothing else fails. So is a panic the
        ///  library contains, which can only come before the host holds the buffer: the lend is refused as
        ///  any other, with nothing charged, no slot of the window spent, the call's one buffer free and no
        ///  wait for room recorded, so the host may ask again. A call that is over, or whose cancellation
        ///  has been requested, lends nothing: AK_STATUS_INVALID_STATE; nor does a call that declared
        ///  AK_CALL_ONE_REQUEST once its request is committed, no WRITE_DONE coming for a SLOT_BUSY to wait
        ///  on. On every refusal no buffer is lent and `*out` is untouched.
        ///
        ///  # Safety
        ///
        ///  `out` must be writable.
        ///  `out_error` must be null or writable for an `ak_error`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ak_get_call_buffer", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ak_status ak_get_call_buffer(ulong call, nuint len, ak_buffer* @out, ak_error* out_error);

        /// <summary>
        ///  Commits a lent buffer as the next message, the `written` bytes the host wrote from its start.
        ///  Ownership passes back to this library.
        ///
        ///  More than the buffer's length, or a write past its end that changed the bytes after it, is
        ///  AK_STATUS_CORRUPTED: the memory around the buffer may be corrupted, so the buffer is taken
        ///  back without being freed, nothing of it is sent, and the runtime shuts down. The buffer is then
        ///  this library's: giving it back again is a use of memory the host no longer owns.
        ///
        ///  An empty message takes no buffer: `buffer` is then the empty one, owner NULL and len 0, with
        ///  `written` 0, and the send takes a slot of the window as any other, AK_STATUS_SLOT_BUSY when
        ///  there is none. A zeroed `ak_buffer` is that empty one, so committing the zeroed `*out` of a
        ///  refused ak_get_call_buffer, which the refusal leaves untouched, sends an empty message.
        ///
        ///  AK_EVENT_WRITE_DONE settles an accepted send and frees its slot from the moment the event is
        ///  emitted, not when the callback returns - so a host woken by it may ask for a buffer from inside
        ///  the callback. It says nothing about the network: the message may have been written, or
        ///  abandoned because the call was cancelled. It arrives exactly once per accepted send, in send
        ///  order, and always before the terminal - but on a call that declared AK_CALL_ONE_REQUEST, whose
        ///  commit also ends the sending and settles the send: no WRITE_DONE comes for it.
        ///
        ///  Refused with AK_STATUS_INVALID_STATE once the call is over or its cancellation has been
        ///  requested, after ak_call_end_send, and after a one-request call's commit. The buffer then stays
        ///  the host's, to give back with ak_return_call_buffer.
        ///
        ///  A panic the library contains is answered by what the commit had done. Before the buffer is taken
        ///  to be the message it is AK_STATUS_INTERNAL, a refusal like the others: the buffer stays lent and
        ///  the host's, to commit again or give back. Once the message is queued it is AK_STATUS_OK. Between
        ///  the two the buffer is gone and the answer is AK_STATUS_CORRUPTED: it is taken back and the
        ///  runtime shuts down.
        ///
        ///  # Safety
        ///
        ///  `buffer` must be one this call lent and the host has not given back, and the host must have
        ///  written its first `written` bytes: they are sent as they are.
        ///  `out_error` must be null or writable for an `ak_error`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ak_call_send_message", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ak_status ak_call_send_message(ulong call, ak_buffer buffer, nuint written, ak_error* out_error);

        /// <summary>
        ///  Gives a lent buffer back unused. Legal on a cancelled or terminal call: it is the only exit for
        ///  a buffer whose send is refused, and the call is not reclaimed until it happens.
        ///
        ///  Takes no call handle: the buffer determines its call. A refused ak_call_send_message therefore
        ///  leaves the buffer with the host, except for AK_STATUS_CORRUPTED, which takes it back. A buffer
        ///  given back with the bytes after its end changed is an overrun, as at the commit: it is taken
        ///  back without being freed and the runtime shuts down, with no status to say so but the shutdown.
        ///  So is a buffer whose bytes after its end could not be read for a contained panic. Any other
        ///  panic leaves the return made: the buffer is given back and its debt paid.
        ///
        ///  # Safety
        ///
        ///  `buffer` must be one this call lent and the host has not given back.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ak_return_call_buffer", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void ak_return_call_buffer(ak_buffer buffer);

        /// <summary>
        ///  Exchanges a lent buffer for one of `new_len` bytes, larger or smaller, carrying over the first
        ///  `keep` bytes the host wrote: a host that finds its buffer too small asks for another size
        ///  without giving the message up. It is a lend of the new length and a return of the old one, and
        ///  the ceiling sees one step: the charge moves by the difference, and a growth is admitted as a
        ///  lend of that difference would be. The ceiling counts the charge, not the instant: the old
        ///  arena is still allocated while the bytes are copied.
        ///
        ///  On success `*out` is the new buffer, whose first `keep` bytes are the old one's and whose
        ///  others are as a lend leaves them. The host gives back `*out`, in its turn, and never `buffer`:
        ///  the old memory may be reused at once. The host's one buffer and its slot of the send window
        ///  are the new buffer's.
        ///
        ///  On every refusal but AK_STATUS_CORRUPTED the old buffer is still lent and the host's, as it
        ///  was, and `*out` is untouched. AK_STATUS_BUDGET_BUSY says the ceiling has no room for the new
        ///  size now: it records no wait and owes no AK_EVENT_BUDGET_WAKE, and a host that waits for room
        ///  gives the buffer back and lends the new length, as one that waits holds none.
        ///  AK_STATUS_MESSAGE_TOO_LARGE is permanent. A call that is over, or whose cancellation has been
        ///  requested, resizes nothing, nor does one that declared AK_CALL_ONE_REQUEST and has committed
        ///  it: AK_STATUS_INVALID_STATE. A `new_len` of zero, a `keep` past
        ///  `new_len`, a null `out` and a `buffer` that is not lent are AK_STATUS_INVALID_ARG. An
        ///  allocator failure is AK_STATUS_INTERNAL, and so is a panic before the exchange is made, the
        ///  ceiling's charge included, which is made whole or not at all: it is a refusal like the others,
        ///  with the old buffer lent and charged, so the host may retry or give it back. A panic after it,
        ///  while the old memory is set aside, does not undo it: the answer is AK_STATUS_OK. A panic while
        ///  taking back an overrun is AK_STATUS_CORRUPTED.
        ///
        ///  A `keep` past the length the buffer was lent at, or a write past its end that changed the bytes
        ///  after it, is an overrun, as it is at the commit: AK_STATUS_CORRUPTED, the buffer taken back
        ///  without being freed, nothing carried over, and the runtime shutting down.
        ///
        ///  # Safety
        ///
        ///  `buffer` must be one this call lent and the host has not given back, and the host must have
        ///  written its first `keep` bytes: they are carried over as they are.
        ///  `out` must be writable.
        ///  `out_error` must be null or writable for an `ak_error`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ak_resize_call_buffer", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ak_status ak_resize_call_buffer(ak_buffer buffer, nuint new_len, nuint keep, ak_buffer* @out, ak_error* out_error);

        /// <summary>
        ///  Signals end of sending. No ak_call_send_message after this: a send that comes after the end,
        ///  and a second end, answer AK_STATUS_INVALID_STATE. So does any end on a call that declared
        ///  AK_CALL_ONE_REQUEST, whose commit ends the sending, and which a host that wants no request
        ///  cancels.
        ///
        ///  An end that comes while an ak_call_send_message has not yet returned on another thread - from
        ///  inside that send's own AK_EVENT_WRITE_DONE, which may arrive first - waits for it to return, so
        ///  it never goes ahead of a message the host has been told left.
        ///
        ///  # Safety
        ///
        ///  `out_error` must be null or writable for an `ak_error`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ak_call_end_send", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ak_status ak_call_end_send(ulong call, ak_error* out_error);

        /// <summary>
        ///  Cancels the call, which then reaches a terminal - carrying CANCELLED, unless the peer's own
        ///  status was already in.
        ///
        ///  Asynchronous: the request takes effect when the call's task observes it, so callbacks already
        ///  committed may still arrive after this returns, and a status the peer had already sent is the
        ///  one delivered. INITIAL_METADATA is never skipped.
        ///
        ///  # Safety
        ///
        ///  `out_error` must be null or writable for an `ak_error`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ak_call_cancel", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ak_status ak_call_cancel(ulong call, ak_error* out_error);

        /// <summary>
        ///  What the call still owes. Purely observational; it is legal never to call it. It exists because
        ///  without a release downcall nothing reports a forgotten ak_return_call_buffer synchronously.
        ///
        ///  # Safety
        ///
        ///  `out` must be writable.
        ///  `out_error` must be null or writable for an `ak_error`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ak_call_debt_of", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ak_status ak_call_debt_of(ulong call, ak_call_debt* @out, ak_error* out_error);

        [DllImport(__DllName, EntryPoint = "ak_abi_version", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int ak_abi_version();

        /// <summary>
        ///  Signals that the host has consumed an event's payload. Two things at once:
        ///
        ///  1. frees the native memory;
        ///  2. arms reception of the next event for that call.
        ///
        ///  At most Grpc.Host.Receive.Window non-consumed payloads per call, four by default: while the
        ///  host owes them, the runtime withholds the next data event. Only a terminal still goes out with
        ///  every credit - every place of the window - spent.
        ///
        ///  The host MUST give a call's payloads back in delivery order: with several outstanding, the
        ///  oldest is the next one consumed. Another order is not refused - this library frees whichever
        ///  owner it is given - but the guarantees this header states are proved for this order alone.
        ///
        ///  Remains legal, and required, after the terminal: the call is not reclaimed until it happens.
        ///
        ///  # Safety
        ///
        ///  `payload` must be one this library delivered and the host has not consumed.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ak_event_consumed", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void ak_event_consumed(ak_bytes payload);

        /// <summary>
        ///  Gives back several payloads in one downcall, in delivery order, each as ak_event_consumed gives
        ///  back one: an unowned payload, owner NULL, is a no-op, and a zero-length payload with an owner is
        ///  given back with its credit. `payloads` may be NULL when `count` is zero.
        ///
        ///  # Safety
        ///
        ///  `payloads` must point at `count` payloads this library delivered and the host has not
        ///  consumed.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ak_events_consumed", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void ak_events_consumed(ak_bytes* payloads, nuint count);

        /// <summary>
        ///  Frees an ak_error's detail. A no-op when detail.owner is NULL, so a host may route every error
        ///  through it. Legal in any runtime state, and after ak_runtime_destroy.
        ///
        ///  # Safety
        ///
        ///  `detail` must be one this library wrote into an ak_error and the host has not released.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ak_error_release", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void ak_error_release(ak_bytes detail);


    }

    /// <summary>
    ///  Bytes the host lends this library for the duration of one downcall.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct ak_bytes_in
    {
        public byte* ptr;
        public nuint len;
    }

    /// <summary>
    ///  Owned by the host after reception, until ak_event_consumed.
    ///
    ///  owner, not ptr, identifies the allocation: the view may be a slice of a larger one. owner ==
    ///  NULL means unowned, never "empty" - a zero-length payload that took a delivery credit carries a
    ///  real owner and MUST be consumed, because the credit comes back with the acquittal and not with
    ///  the bytes.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct ak_bytes
    {
        public byte* ptr;
        public nuint len;
        public void* owner;
    }

    /// <summary>
    ///  Lent by ak_get_call_buffer out of the call's arena. The host writes at most len bytes from its
    ///  start and gives it back exactly once, by ak_call_send_message, which says how many it wrote,
    ///  or ak_return_call_buffer. ak_resize_call_buffer exchanges it for another and does not end the
    ///  obligation: the one it hands back is the host's to give back in its turn. This library never
    ///  reclaims a lent buffer on its own - not on cancellation, not on channel close - which is what
    ///  removes the race between a writing thread and a cancelling one.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct ak_buffer
    {
        public byte* ptr;
        public nuint len;
        public void* owner;
    }

    /// <summary>
    ///  On the callback's stack; no lifecycle of its own. The payload is owned when owner is not NULL.
    ///
    ///  WRITE_DONE, BUDGET_WAKE, SHUTDOWN_COMPLETE and RESOURCES_RELEASED carry no payload: ptr ==
    ///  NULL, len == 0, owner == NULL. ak_event_consumed on such a payload is a no-op, so a host may
    ///  route every event through one path.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct ak_event
    {
        public ak_event_kind kind;
        public ak_bytes payload;
        /// <summary>
        ///  gRPC status for AK_EVENT_STATUS, ak_head_origin for AK_EVENT_INITIAL_METADATA, zero on
        ///  every other event.
        /// </summary>
        public int status_code;
        /// <summary>
        ///  AK_EVENT_SHUTDOWN_COMPLETE only.
        /// </summary>
        public ak_host_debt host_debt;
    }

    /// <summary>
    ///  One field of a logged event: the name the engine gave it, and its value rendered as text. Both
    ///  views are valid for the callback alone.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct ak_log_field
    {
        public ak_bytes_in key;
        public ak_bytes_in value;
    }

    /// <summary>
    ///  An event the engine logs, as the log callback receives it. Everything it points at is valid for
    ///  the callback's duration only, and nothing of it is the host's to give back: a host that keeps
    ///  a record copies it.
    ///
    ///  Starts with struct_size, the size of the record this library built: a host reads only the
    ///  fields that lie within it. The text is UTF-8, and carries neither a source location nor a
    ///  time, which the host's own logger stamps.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct ak_log_record
    {
        /// <summary>
        ///  sizeof this record as this library defines it.
        /// </summary>
        public uint struct_size;
        /// <summary>
        ///  An AK_LOG_ level.
        /// </summary>
        public uint level;
        /// <summary>
        ///  What emitted it: the Rust module path, such as armonik_transport::grpc::channel, or h2.
        /// </summary>
        public ak_bytes_in target;
        /// <summary>
        ///  The event's text.
        /// </summary>
        public ak_bytes_in message;
        /// <summary>
        ///  How many fields `fields` points at.
        /// </summary>
        public nuint field_count;
        /// <summary>
        ///  The event's other values, in the order it names them. NULL when field_count is zero.
        /// </summary>
        public ak_log_field* fields;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct ak_runtime_config
    {
        public uint struct_size;
        /// <summary>
        ///  Zero, the one revision of this record there is.
        /// </summary>
        public uint version;
        /// <summary>
        ///  Zero: no flag is defined, and a set one is refused rather than ignored.
        /// </summary>
        public uint flags;
        /// <summary>
        ///  Zero.
        /// </summary>
        public uint reserved;
        /// <summary>
        ///  Bytes past which work waits, counting the buffers lent, the messages received until
        ///  the host consumes them, and the compressed copies the engine holds while a message holds
        ///  them: a
        ///  call stops reading, a copy that does not fit is not made and its message goes out
        ///  uncompressed, and a lend is refused with
        ///  AK_STATUS_BUDGET_BUSY. Zero, or more than this library can lend, asks for its own: four
        ///  gigabytes, or half the address space where that is smaller - the gRPC length prefix and the
        ///  allocator between them admit no more, so a budget above it is one no single lend could draw
        ///  on.
        /// </summary>
        public ulong memory_ceiling;
        /// <summary>
        ///  Bytes past which the engine stops: a received message that would take the count past it
        ///  ends its call with RESOURCE_EXHAUSTED. Calls admitted to read below memory_ceiling may pass
        ///  it together, by a message each, and this bounds them. Zero is a quarter above the first
        ///  threshold in force, memory_ceiling or this library's own; a value below that threshold is
        ///  AK_STATUS_INVALID_ARG.
        /// </summary>
        public ulong memory_hard_ceiling;
        /// <summary>
        ///  A channel document, in the vocabulary of ak_channel_create's config_json, whose options
        ///  every channel of the runtime takes where its own document states none: the two are merged
        ///  option by option, a struct's options within it, and the channel's win; a group of options
        ///  with a mandatory field is stated whole and replaces the default's, and an alternative - how
        ///  the server is verified, who the client is, which proxy - merges as its payload does over the
        ///  same alternative and is taken whole over another. Empty states none.
        ///  Refused with AK_STATUS_INVALID_ARG where ak_channel_create would refuse it.
        /// </summary>
        public ak_bytes_in channel_defaults_json;
        /// <summary>
        ///  Receives the engine's logs, filtered by `*=warn,armonik_transport*=info`: the runtime option
        ///  Logging.Filter, which only ak_runtime_create_from loads, is the one way to another. NULL for
        ///  none.
        /// </summary>
        public void* log_callback;
        /// <summary>
        ///  Handed to `log_callback` with each record.
        /// </summary>
        public void* log_ctx;
    }

    /// <summary>
    ///  One source of a configuration.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct ak_config_source
    {
        /// <summary>
        ///  An ak_source_kind; another is AK_STATUS_INVALID_ARG.
        /// </summary>
        public uint kind;
        /// <summary>
        ///  Zero; another is AK_STATUS_INVALID_ARG.
        /// </summary>
        public uint reserved;
        /// <summary>
        ///  What the kind says, UTF-8; one that is not is AK_STATUS_INVALID_ARG.
        /// </summary>
        public ak_bytes_in value;
    }

    /// <summary>
    ///  Where a runtime's configuration comes from: sources, read in order when the runtime is created,
    ///  a later one over an earlier one option by option. Every source is a document, judged whole
    ///  against the schema: a key the vocabulary does not declare, the root's included, is refused by
    ///  its path, and so is a value that does not fit its key or its bounds, with its source, never
    ///  quoted.
    ///
    ///  Versioned as the options structs are, but for its fourth field, which is source_count rather
    ///  than reserved.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct ak_config
    {
        public uint struct_size;
        /// <summary>
        ///  Zero, the one revision of this record there is.
        /// </summary>
        public uint version;
        /// <summary>
        ///  None is defined: any flag is refused rather than ignored.
        /// </summary>
        public uint flags;
        /// <summary>
        ///  How many sources `sources` points at.
        /// </summary>
        public uint source_count;
        /// <summary>
        ///  The sources, in order, a later one over an earlier one. May be NULL when source_count is
        ///  zero.
        /// </summary>
        public ak_config_source* sources;
        /// <summary>
        ///  The prefix, UTF-8, always the one given: the section of a file or of a document, and the
        ///  start of the name of an environment variable or of a pair, that is the engine's. A host that
        ///  keeps the engine's options beside its own gives `ArmoniK__Client__Grpc`. Empty takes
        ///  everything: the whole of a file or of a document is the engine's, and every key of it has to
        ///  be one the schema declares.
        /// </summary>
        public ak_bytes_in prefix;
        /// <summary>
        ///  Receives the engine's logs, filtered by the runtime's option Logging.Filter; NULL for none.
        ///  NULL when the host's struct_size ends before this field.
        /// </summary>
        public void* log_callback;
        /// <summary>
        ///  Handed to `log_callback` with each record.
        /// </summary>
        public void* log_ctx;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct ak_memory_usage
    {
        /// <summary>
        ///  The buffers lent and the messages received and not yet given back, and the compressed
        ///  copies the engine holds, atomic snapshot. Past
        ///  `ceiling` by up to a message per call admitted to read, and never past the second
        ///  threshold. The spare arenas channels keep to lend again are not in it: they fit under
        ///  `ceiling` beside it, give their room to any charge that needs it, and are kept until then
        ///  or until their channel closes.
        /// </summary>
        public ulong bytes_used;
        /// <summary>
        ///  The limit in force, which is what was configured or this library's own where that is
        ///  smaller. Never zero.
        /// </summary>
        public ulong ceiling;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct ak_call_start_options
    {
        /// <summary>
        ///  At least the offset of timeout_ns: a host built before that field passes no deadline.
        /// </summary>
        public uint struct_size;
        /// <summary>
        ///  Zero, the one revision of this record there is.
        /// </summary>
        public uint version;
        /// <summary>
        ///  AK_CALL_HAS_DEADLINE, AK_CALL_ONE_RESPONSE, AK_CALL_ONE_REQUEST and AK_CALL_WAIT_FOR_READY,
        ///  any of them or none. Any other flag is refused rather than ignored.
        /// </summary>
        public uint flags;
        /// <summary>
        ///  Zero.
        /// </summary>
        public uint reserved;
        /// <summary>
        ///  "/Service/Method", not NUL-terminated.
        /// </summary>
        public ak_bytes_in method;
        /// <summary>
        ///  A metadata blob - a uint32_t count, then each key and each value as a uint32_t length and
        ///  its bytes; may be empty.
        /// </summary>
        public ak_bytes_in metadata;
        /// <summary>
        ///  With AK_CALL_HAS_DEADLINE, the nanoseconds from ak_call_start to the call's deadline, which
        ///  ends it DEADLINE_EXCEEDED and is sent to the server as grpc-timeout. Zero is a deadline
        ///  already passed: the call ends without reaching the server. Without the flag, the
        ///  channel's default deadline applies, and the field is ignored.
        /// </summary>
        public ulong timeout_ns;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct ak_call_debt
    {
        /// <summary>
        ///  Delivered, not yet ak_event_consumed.
        /// </summary>
        public uint payloads_owed;
        /// <summary>
        ///  Out of the arena, not yet given back.
        /// </summary>
        public uint buffers_lent;
        /// <summary>
        ///  The runtime's own, informational.
        /// </summary>
        public uint callbacks_in_flight;
        /// <summary>
        ///  0 or 1.
        /// </summary>
        public int terminal_delivered;
    }

    /// <summary>
    ///  Filled by this library, read by the host, and written only when the status is not
    ///  AK_STATUS_OK. Fixed layout, with no size prefix: ak_abi_version() is the agreement.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct ak_error
    {
        public ak_error_kind kind;
        /// <summary>
        ///  UTF-8, the cause chain flattened into one message. detail.owner == NULL means there is
        ///  nothing to free. Released by ak_error_release, never by ak_event_consumed.
        /// </summary>
        public ak_bytes detail;
    }


    /// <summary>
    ///  Returned by every entry point that can fail. ak_event_consumed, ak_return_call_buffer and
    ///  ak_channel_release are void because a wrong token is a host bug the ABI cannot report anywhere
    ///  useful; ak_runtime_status, ak_channel_status and ak_abi_version return their answer.
    /// </summary>
    internal enum ak_status : int
    {
        AK_STATUS_OK = 0,
        /// <summary>
        ///  The object is gone; the token names nothing.
        /// </summary>
        AK_STATUS_HANDLE_STALE = 1,
        /// <summary>
        ///  This call's send window is full - backpressure, not an error; retry when a WRITE_DONE
        ///  arrives. That acquittal says this library has taken the message and the host's buffer is
        ///  free; it says nothing about the peer, and does not wait on one - the wake-up is promised,
        ///  its timing is not.
        /// </summary>
        AK_STATUS_SLOT_BUSY = 2,
        /// <summary>
        ///  A null pointer, or an options struct that is too short or sets a version, a flag or a
        ///  reserved field.
        /// </summary>
        AK_STATUS_INVALID_ARG = 3,
        /// <summary>
        ///  A fault the ABI cannot attribute.
        /// </summary>
        AK_STATUS_INTERNAL = 4,
        /// <summary>
        ///  The runtime-wide byte ceiling is reached - retry at the call's next AK_EVENT_BUDGET_WAKE,
        ///  once the refused lend has returned. Until the send is served or the call ends, reads are
        ///  held back for it across the whole runtime, so a host woken must try again or cancel the
        ///  call. A refused ak_resize_call_buffer is none of this: it records no wait, and a host that
        ///  waits lends again.
        /// </summary>
        AK_STATUS_BUDGET_BUSY = 5,
        /// <summary>
        ///  A valid handle at the wrong moment: a send after the terminal, a start while stopping, a
        ///  destroy before quiescence, a lend while the call's one buffer is held or being paid back.
        ///  A guard refused, which is not a fault.
        /// </summary>
        AK_STATUS_INVALID_STATE = 6,
        /// <summary>
        ///  The length exceeds the ceiling itself, so no return by anyone will ever make room.
        ///  Permanent; do not retry.
        /// </summary>
        AK_STATUS_MESSAGE_TOO_LARGE = 7,
        /// <summary>
        ///  The host wrote past a buffer it was lent, or committed or kept more bytes than it was
        ///  lent. The memory around the buffer may be corrupted: the buffer is taken back without
        ///  being freed, and the runtime shuts down. Permanent.
        /// </summary>
        AK_STATUS_CORRUPTED = 8,
    }

    /// <summary>
    ///  Only QUIESCENT permits ak_runtime_destroy or unloading the library. The host reaches it by
    ///  acting, not by waiting: while it still holds something the status stays STOPPED, and the
    ///  AK_EVENT_SHUTDOWN_COMPLETE callback says so through its host_debt field. Polling for QUIESCENT
    ///  before returning what it holds is therefore a deadlock.
    ///
    ///  NONE is what keeps a handle a token rather than a pointer: a handle this library does not
    ///  know - never created, or reclaimed by ak_runtime_destroy - is reported, not resolved.
    ///  It is not QUIESCENT, which would tell a host that passed a channel handle by mistake that it
    ///  may destroy the runtime and unload the library while one is running.
    /// </summary>
    internal enum ak_runtime_state : int
    {
        /// <summary>
        ///  This library knows no such runtime.
        /// </summary>
        AK_RUNTIME_NONE = 0,
        /// <summary>
        ///  Operational, accepts channels and calls.
        /// </summary>
        AK_RUNTIME_RUNNING = 1,
        /// <summary>
        ///  Start gate closed, channels closing.
        /// </summary>
        AK_RUNTIME_GRPC_STOPPING = 2,
        /// <summary>
        ///  The gRPC side is done; the host may still hold memory.
        /// </summary>
        AK_RUNTIME_GRPC_STOPPED = 3,
        /// <summary>
        ///  And nothing of it is outstanding either.
        /// </summary>
        AK_RUNTIME_QUIESCENT = 4,
        /// <summary>
        ///  Quiescence impossible, destroy refused. Reported when the status itself cannot be read,
        ///  when the task driving the shutdown dies, and when that shutdown cannot get a thread of its
        ///  own: the three ways the step to QUIESCENT stops being reachable. A shutdown that is merely
        ///  slow stays GRPC_STOPPING.
        /// </summary>
        AK_RUNTIME_FAILED_UNQUIESCED = 5,
    }

    internal enum ak_event_kind : int
    {
        /// <summary>
        ///  payload = metadata blob (owned), status_code = its origin.
        /// </summary>
        AK_EVENT_INITIAL_METADATA = 1,
        /// <summary>
        ///  payload = message bytes (owned).
        /// </summary>
        AK_EVENT_MESSAGE = 2,
        /// <summary>
        ///  Terminal - payload = reason + trailers (owned).
        /// </summary>
        AK_EVENT_STATUS = 3,
        /// <summary>
        ///  An accepted send is settled; its slot is already free.
        /// </summary>
        AK_EVENT_WRITE_DONE = 4,
        /// <summary>
        ///  The runtime has stopped running.
        /// </summary>
        AK_EVENT_SHUTDOWN_COMPLETE = 5,
        /// <summary>
        ///  And now nothing of it is outstanding.
        /// </summary>
        AK_EVENT_RESOURCES_RELEASED = 6,
        /// <summary>
        ///  A release gave bytes back since this call's send was refused with AK_STATUS_BUDGET_BUSY:
        ///  try it again, once that send's downcall has returned. Every call refused since the last
        ///  release is woken, and none is promised the room: another may take it first.
        /// </summary>
        AK_EVENT_BUDGET_WAKE = 7,
    }

    /// <summary>
    ///  Carried by AK_EVENT_INITIAL_METADATA in status_code: where the head came from. The event comes
    ///  first on every call, and its metadata is empty unless the peer's headers were delivered. Zero
    ///  is the peer's headers, so a host that ignores the field takes every head for the peer's.
    /// </summary>
    internal enum ak_head_origin : int
    {
        /// <summary>
        ///  The peer's response headers.
        /// </summary>
        AK_HEAD_RECEIVED = 0,
        /// <summary>
        ///  A response came and delivered no head - the Trailers-Only shape, or an answer refused
        ///  before its body; the terminal is the call's status, the peer's unless the call was stopped
        ///  here first.
        /// </summary>
        AK_HEAD_TRAILERS_ONLY = 1,
        /// <summary>
        ///  No response reached the call.
        /// </summary>
        AK_HEAD_NO_RESPONSE = 2,
    }

    /// <summary>
    ///  Carried by AK_EVENT_SHUTDOWN_COMPLETE and by nothing else.
    /// </summary>
    internal enum ak_host_debt : int
    {
        /// <summary>
        ///  Nothing of ours is in your hands; no second event.
        /// </summary>
        AK_HOST_NOTHING_TO_RETURN = 0,
        /// <summary>
        ///  Consume the payloads, return the buffers; AK_EVENT_RESOURCES_RELEASED follows.
        /// </summary>
        AK_HOST_MUST_RETURN = 1,
    }

    /// <summary>
    ///  Where a source of ak_config is read from, in ak_config_source.kind.
    /// </summary>
    internal enum ak_source_kind : int
    {
        /// <summary>
        ///  value: the file's path, UTF-8. JSON, YAML or TOML by its extension - .json, .yaml or .yml,
        ///  .toml. The section the prefix names is judged against the schema and nothing outside it is
        ///  looked at; with an empty prefix the whole file is. A file that does not exist is refused.
        /// </summary>
        AK_SOURCE_FILE = 1,
        /// <summary>
        ///  value: the file's path, read as AK_SOURCE_FILE's, except that a file that does not exist
        ///  contributes nothing.
        /// </summary>
        AK_SOURCE_OPTIONAL_FILE = 2,
        /// <summary>
        ///  value: empty. The variables whose name starts with the prefix and `__`, the rest of the
        ///  name the key's path, its parts joined by `__` and compared without case, and the value text
        ///  read by its key's type. The variables that do not have the prefix are never looked at. Read
        ///  once, by ak_runtime_create_from. Refused with an empty prefix: every variable of the process
        ///  would be a key.
        /// </summary>
        AK_SOURCE_ENVIRONMENT = 3,
        /// <summary>
        ///  value: a JSON document, read as AK_SOURCE_FILE's is: the section the prefix names is the
        ///  engine's, in the vocabulary of runtime.schema.json, and the whole document with an empty
        ///  prefix.
        /// </summary>
        AK_SOURCE_DOCUMENT = 4,
        /// <summary>
        ///  value: a JSON object whose names are the prefix, `__` and a key's path, its parts joined by
        ///  `__`, and whose values are text, read as the environment's are. A name that does not have
        ///  the prefix is never looked at.
        /// </summary>
        AK_SOURCE_PAIRS = 5,
    }

    /// <summary>
    ///  How far along a channel's closing is. A handle this library no longer knows reads as NONE,
    ///  which is also what an unopened one reads as: neither names a channel.
    /// </summary>
    internal enum ak_channel_state : int
    {
        AK_CHANNEL_NONE = 0,
        /// <summary>
        ///  Takes calls.
        /// </summary>
        AK_CHANNEL_OPEN = 1,
        /// <summary>
        ///  Released, its calls draining.
        /// </summary>
        AK_CHANNEL_CLOSING = 2,
        /// <summary>
        ///  And nothing of it is active any more.
        /// </summary>
        AK_CHANNEL_CLOSED = 3,
    }

    /// <summary>
    ///  Why a fallible entry point refused, beyond what its status says.
    /// </summary>
    internal enum ak_error_kind : int
    {
        /// <summary>
        ///  No family: the status says what happened - backpressure, a request too large for the
        ///  ceiling, a fault this library cannot attribute. Zero, so a zero-initialized ak_error reads
        ///  as nothing more to say.
        /// </summary>
        AK_ERROR_NONE = 0,
        /// <summary>
        ///  The configuration document or the endpoint, before any socket.
        /// </summary>
        AK_ERROR_CONFIG = 1,
        /// <summary>
        ///  DNS, TCP, TLS handshake.
        /// </summary>
        AK_ERROR_CONNECTION = 2,
        /// <summary>
        ///  HTTP/2 or gRPC framing, after a connection.
        /// </summary>
        AK_ERROR_TRANSPORT = 3,
        AK_ERROR_TIMEOUT = 4,
        AK_ERROR_CANCELLED = 5,
        /// <summary>
        ///  The host used the ABI in a way it does not admit: a null pointer, a handle that names
        ///  nothing, a downcall at a moment its object refuses it.
        /// </summary>
        AK_ERROR_USAGE = 6,
    }


}
