/*
 * ArmoniK transport C ABI - GENERATED, DO NOT EDIT.
 *
 * Regenerated by `build.rs` (cbindgen) on every build of `armonik-transport-ffi`, and committed so
 * that an ABI change shows up in review rather than only in the compiled library. Edit the Rust
 * sources, not this file.
 *
 * This is an HTTP/2 transport, not a gRPC stack. It opens a request, streams bytes both ways, and
 * reports headers, data and trailers. Message framing, `grpc-status`, deadlines and retry belong to
 * whatever speaks gRPC above it.
 *
 * Conventions that the signatures alone do not convey:
 *
 *  - Result codes. 0 is success, everything else is negative; see the AK_* constants. There is no
 *    positive space: no gRPC status is reported at this level.
 *
 *  - The reactor. One event callback per request, and three rules:
 *      1. Nothing arrives unarmed. `ak_request_read` arms one read and produces exactly one event
 *         (AK_EVENT_READ_DONE, or AK_EVENT_COMPLETED); `ak_request_write` arms one write and
 *         produces AK_EVENT_WRITE_DONE. At most one read and one write may be armed at a time.
 *      2. AK_EVENT_COMPLETED arrives exactly once, and last. If `ak_request_start` returned AK_OK it
 *         always arrives, cancellation and connection failure included; if `ak_request_start`
 *         failed, no event ever arrives. Anything still armed is resolved by it. Nothing is called
 *         back afterwards, so that is where - and only there - the caller releases whatever it
 *         rooted for `ctx`. `ak_request_release` does NOT end that obligation: it gives up the
 *         handle, and the terminal event still arrives.
 *      3. No callback happens during an inbound call. Every function posts a command and returns;
 *         events are emitted from this library's own threads, serialised per request. A caller
 *         needs no lock of its own, but its callback runs on a foreign thread: it must not block,
 *         must not raise, and must not re-enter this library for the same request.
 *
 *  - Handles are reference-counted, and thread-safe. `_release` gives up one reference rather than
 *    destroying anything; the object lives until the last reference goes, so an `ak_client` or
 *    `ak_request` may be used from any thread and from several at once, `_release` included - a call
 *    already under way when another thread releases the handle finishes normally. What is not
 *    allowed is using a handle after your own `_release`.
 *
 *  - Releasing a request that has not completed cancels it. The AK_EVENT_COMPLETED event still
 *    arrives, and `ctx` must stay valid until it does. A caller that has to know no callback can
 *    reach it any more - an AppDomain being unloaded, a library being torn down - waits for the
 *    outstanding terminal events, not for `ak_request_release` to return.
 *
 *  - Event payloads are BORROWED for the duration of the callback. Copy what is needed before
 *    returning; never free one. Nothing on the event path is owned by the caller.
 *
 *  - `ak_bytes` is the opposite, and only ever comes back through a synchronous out-parameter: it is
 *    owned by the caller and must be released with exactly one `ak_bytes_free`, passing the value
 *    back unchanged. `ptr`/`len` are a read-only view; `owner` is opaque, so never dereference it.
 *    The zeroed value means "no data" and is always safe to free.
 *
 *  - `ak_bytes_in` is a view into memory this library does not own, borrowed for the duration of the
 *    call. A null pointer or zero length means "absent".
 *
 *  - Key/value blobs (request headers, response headers, trailers) are encoded as:
 *        uint32 count, then `count` times { uint32 key_len, key bytes, uint32 value_len, value bytes }
 *    Integers are in NATIVE byte order: this is an in-process ABI, not a wire format. Keys may
 *    repeat and are kept in order. Values are opaque bytes; a `-bin` header's base64 is the caller's
 *    convention and passes through untouched.
 */


#ifndef ARMONIK_TRANSPORT_FFI_H
#define ARMONIK_TRANSPORT_FFI_H

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * The operation succeeded.
 */
#define AK_OK 0

/**
 * A pointer argument that must not be null was null.
 */
#define AK_NULL_ARGUMENT -1

/**
 * A byte buffer was not valid UTF-8 where UTF-8 was required.
 */
#define AK_INVALID_UTF8 -2

/**
 * The client configuration was rejected; see the returned error message.
 */
#define AK_INVALID_CONFIG -3

/**
 * The request never reached the server: no connection, or the connection failed before any
 * response header arrived. See the message on the `COMPLETED` event.
 */
#define AK_CONNECTION_FAILED -4

/**
 * The handle passed to a call has already been freed, or was never valid.
 */
#define AK_INVALID_HANDLE -5

/**
 * The request is not in a state that allows the operation: a second read or write armed while
 * one is still outstanding, a write after `ak_request_close_send`, or an operation on a
 * request that has already completed.
 */
#define AK_INVALID_STATE -6

/**
 * Something inside this crate failed in a way that is not the caller's doing; see the message.
 */
#define AK_INTERNAL -8

/**
 * A panic was caught at the FFI boundary, or inside the task driving a request. This is always
 * a bug in this crate; the message carries whatever the panic payload could be turned into.
 */
#define AK_INTERNAL_PANIC -9

/**
 * The request was cancelled through [`crate::ak_request_cancel`], or by
 * [`crate::ak_request_release`] before it had completed.
 */
#define AK_CANCELLED -10

/**
 * The configured `Timeout` elapsed while the request was still in flight.
 */
#define AK_TIMEOUT -11

/**
 * The connection failed after the response headers had arrived: a reset stream, a broken
 * connection, a protocol error. See the message on the `COMPLETED` event.
 */
#define AK_TRANSPORT -12

/**
 * The response headers arrived. `payload` is a key/value blob; the HTTP status is in it under
 * the `:status` key, as decimal ASCII. `code` is [`crate::status::OK`].
 *
 * Always the first event of a successful request, and never emitted more than once.
 */
#define AK_EVENT_RESPONSE_HEADERS 1

/**
 * The chunk armed by [`crate::ak_request_write`] has been handed to the connection. `payload`
 * is empty, `code` is [`crate::status::OK`]. It does not mean the bytes reached the server,
 * only that this crate no longer needs the caller's buffer and one more write may be armed.
 */
#define AK_EVENT_WRITE_DONE 2

/**
 * The read armed by [`crate::ak_request_read`] produced body bytes. `payload` is the chunk,
 * borrowed for the duration of the call; `code` is [`crate::status::OK`].
 *
 * A chunk is whatever the connection delivered as one DATA frame's worth of body, not a
 * message: there is no framing at this level, so a reader must handle any split.
 */
#define AK_EVENT_READ_DONE 3

/**
 * The request is over, and no further callback will be made for it.
 *
 * `code` is [`crate::status::OK`] when the response ended cleanly, and `payload` is then the
 * trailers as a key/value blob - possibly empty, which is what a clean early end of stream
 * looks like. Otherwise `code` is one of the negative statuses and `payload` is the failure,
 * rendered as a UTF-8 message with its whole cause chain flattened into it.
 */
#define AK_EVENT_COMPLETED 4

/**
 * A connection pool, and the options every request on it inherits.
 *
 * Handed to the caller as an opaque pointer. Cloning the inner `Arc` into each request is what
 * lets a request outlive [`ak_client_release`]: the pool goes away when the last user does.
 */
typedef struct ak_client ak_client;

/**
 * A request handle.
 *
 * The task owns everything that matters; this is the caller's end of the command channel plus the
 * flags that say what is currently armed.
 */
typedef struct ak_request ak_request;

/**
 * An owned buffer handed to the caller.
 *
 * `ptr`/`len` are a read-only *view*; the actual owner of the allocation is `owner`, an opaque
 * handle the caller must pass back unchanged and never otherwise touch. Splitting it this way -
 * rather than treating `ptr` itself as the allocation to free - is what lets this type hand out a
 * [`bytes::Bytes`] this crate already owns (a decoded response message, most importantly) without
 * ever copying its content: `owner` is a boxed `Bytes`, `ptr`/`len` just describe what it derefs
 * to. Freeing then means dropping that box, which is correct regardless of what the `Bytes`
 * happens to wrap internally - a `Bytes` is not always backed by a plain allocation matching
 * `ptr`/`len` (it may be a shared, refcounted sub-slice), so reinterpreting `ptr` itself as
 * something to deallocate, the way a naive `Box<[u8]>` scheme would, is not an option here.
 *
 * Every non-null (non-zero `owner`) `ak_bytes` must be released through exactly one call to
 * [`ak_bytes_free`]. The zeroed value (`owner`/`ptr` null, `len` 0) means "no data" and is always
 * safe to pass to [`ak_bytes_free`] as a no-op.
 *
 * This is distinct from the plain `(ptr, len)` views the ABI uses for *input* buffers
 * ([`ak_bytes_in`]): those are borrowed from the caller and must never be freed by Rust. Only a
 * value that came out of this crate as an `ak_bytes` is ever appropriate to free through
 * [`ak_bytes_free`].
 *
 * `Copy`, like any plain-old-data struct crossing a C ABI is on the C side - copying the
 * `(ptr, len, owner)` triple itself is harmless. What must never happen, on either side, is
 * passing more than one copy of the *same* originally-produced value to [`ak_bytes_free`].
 */
typedef struct ak_bytes {
  /**
   * Pointer to the first byte, or null for an empty/absent buffer. Valid to read from until
   * this value is passed to [`ak_bytes_free`]; never write through it.
   */
  const uint8_t *ptr;
  /**
   * Number of bytes at `ptr`.
   */
  size_t len;
  /**
   * Opaque; pass back to [`ak_bytes_free`] unchanged, never dereference or otherwise inspect it.
   */
  void *owner;
} ak_bytes;

/**
 * A borrowed input buffer: a view into memory the *caller* owns.
 *
 * Also what an event payload travels as, in the other direction: borrowed for the duration of the
 * callback and invalid the moment it returns. Never freed by whoever received it. A null `ptr` or
 * zero `len` means "empty" or "absent".
 */
typedef struct ak_bytes_in {
  /**
   * Pointer to the first byte, or null for an empty/absent buffer.
   */
  const uint8_t *ptr;
  /**
   * Number of bytes at `ptr`.
   */
  size_t len;
} ak_bytes_in;

/**
 * The event callback. One per request, invoked only from this crate's runtime threads.
 *
 * `payload` is **borrowed** for the duration of the call: copy what is needed before returning, and
 * never free it. `code` is [`crate::status::OK`] on every event but a failed `COMPLETED`.
 *
 * The callback must not block, must not unwind, and must not call back into this crate's request
 * functions for the same request from inside itself.
 */
typedef void (*ak_request_on_event)(void *ctx,
                                    int32_t kind,
                                    struct ak_bytes_in payload,
                                    int32_t code);

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Build a client from a JSON configuration document.
 *
 * `config_json` names the flat options of `armonik_transport::HttpConfig` (`Endpoint`,
 * `AllowUnsafeConnection`, `CaCert`, `Proxy*`, `Tcp*`, `Http2*`, ...). Everything it accepts is
 * documented by the JSON schema that crate generates.
 *
 * Synchronous and lazy: this validates the options and assembles the connector, and opens no
 * connection. A failure here is a configuration failure, reported immediately with its whole cause
 * chain flattened into `out_err`. It touches no runtime, so it is callable from anywhere, an event
 * callback included.
 *
 * # Safety
 *
 * `config_json` must point to `len` readable bytes. `out` must be a writable `ak_client*`, and
 * receives a handle to be given up with exactly one [`ak_client_release`]. `out_err`, when non-null,
 * must be a writable [`ak_bytes`] and receives a message to release with [`crate::ak_bytes_free`].
 */
int32_t ak_client_create(const uint8_t *config_json,
                         size_t len,
                         struct ak_client **out,
                         struct ak_bytes *out_err);

/**
 * Give up this caller's reference to a client.
 *
 * A reference, not the object. Requests already in flight keep the pool alive and run to their
 * `COMPLETED` event, and a call already inside another entry point finishes normally; the pool goes
 * away when the last user of it does.
 *
 * # Safety
 *
 * `client` must be a handle from [`ak_client_create`] that has not been released, or null.
 */
void ak_client_release(struct ak_client *client);

/**
 * Free an [`ak_bytes`] previously returned by this crate.
 *
 * # Safety
 *
 * `bytes` must be a value this crate returned, not yet freed. Passing a borrowed input buffer, a
 * value already freed, or a value with an `owner` that was not produced by this crate, is
 * undefined behaviour. The zeroed value is always safe to pass here.
 */
void ak_bytes_free(struct ak_bytes bytes);

/**
 * Open a request and start driving it.
 *
 * `headers_blob` is a key/value blob (see the header preamble). Two pseudo-keys are required and
 * are not sent as headers:
 *
 * - `:method` - the HTTP method, e.g. `POST`.
 * - `:url` - the absolute request URL, scheme and authority included. The connection pool keys on
 *   it, so a path-only form is refused.
 *
 * Every other key is sent as a request header, in the order given, duplicates included. `-bin`
 * values are passed through untouched: base64 is the caller's convention, not this crate's.
 *
 * On [`crate::status::OK`] a `COMPLETED` event is guaranteed to follow, exactly once, and that is
 * the moment - the only moment - at which `ctx` may be released. On any other status no event will
 * ever be delivered, and `ctx` may be released at once.
 *
 * # Safety
 *
 * `client` must be a live handle from [`crate::ak_client_create`]. `headers_blob` must point to
 * `len` readable bytes for the duration of the call. `on_event` must remain callable, and `ctx`
 * valid, until the `COMPLETED` event - [`ak_request_release`] does not end that obligation, it only
 * gives up the handle. `out` must be writable.
 */
int32_t ak_request_start(const struct ak_client *client,
                         const uint8_t *headers_blob,
                         size_t len,
                         ak_request_on_event on_event,
                         void *ctx,
                         struct ak_request **out,
                         struct ak_bytes *out_err);

/**
 * Arm one write of `len` bytes.
 *
 * The bytes are copied before this returns, so the caller's buffer is free immediately; the
 * `WRITE_DONE` event says the chunk was accepted by the connection, and is what permits the next
 * write. Arming a second write while one is outstanding, or writing after
 * [`ak_request_close_send`], returns [`crate::status::INVALID_STATE`].
 *
 * # Safety
 *
 * `request` must be a live handle, and `data` readable for `len` bytes.
 */
int32_t ak_request_write(const struct ak_request *request, const uint8_t *data, size_t len);

/**
 * End the request body.
 *
 * # Safety
 *
 * `request` must be a live handle.
 */
int32_t ak_request_close_send(const struct ak_request *request);

/**
 * Arm one read.
 *
 * Exactly one event follows: `READ_DONE` with a chunk of the response body, or `COMPLETED`.
 *
 * # Safety
 *
 * `request` must be a live handle.
 */
int32_t ak_request_read(const struct ak_request *request);

/**
 * Cancel the request.
 *
 * Resets the stream with CANCEL and finishes; a `COMPLETED` event with
 * [`crate::status::CANCELLED`] follows unless the request had already completed, in which case this
 * does nothing. Calling it more than once is harmless.
 *
 * # Safety
 *
 * `request` must be a live handle.
 */
int32_t ak_request_cancel(const struct ak_request *request);

/**
 * Give up this caller's reference to a request.
 *
 * A reference, not the object: the request is reference-counted, and whatever is still using it -
 * another thread mid-call, the task driving it - keeps it alive. Nothing is deallocated until the
 * last reference goes, so releasing a handle another thread is calling into is well-defined rather
 * than a race.
 *
 * Releasing before `COMPLETED` is allowed and is how a request is abandoned: it cancels, and the
 * request runs to its `COMPLETED` event as it always does. **That event still arrives**, and it
 * remains the only point at which `ctx` may be released - this call does not end that obligation.
 * A caller that must know no callback can reach it any more, an AppDomain being unloaded for
 * instance, waits for the outstanding `COMPLETED` events rather than for this to return.
 *
 * Calling it twice, or on a handle that was never valid, does nothing.
 *
 * # Safety
 *
 * `request` must be a handle from [`ak_request_start`] that has not been released, or null.
 */
void ak_request_release(struct ak_request *request);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* ARMONIK_TRANSPORT_FFI_H */
