/* C ABI over the ArmoniK Rust gRPC engine.
 *
 * Generated by cbindgen from the Rust declarations in armonik-transport-ffi (src/abi.rs and
 * src/lib.rs) and committed. Edits here are lost: change the Rust, then write this again with
 * `cargo run -p armonik-transport-ffi-bindgen`. The build fails while the two differ.
 * `spec/armonik_grpc_ffi/abi.md` carries the reasoning; this carries the contract.
 *
 * Two rules run through all of it:
 *
 *   - A handle is a token, not a pointer. It names one object and is never handed out twice, so
 *     a downcall on something the runtime has reclaimed reports AK_STATUS_HANDLE_STALE instead of
 *     faulting - and so does one on an object of another kind.
 *   - Memory crosses in one direction at a time. What the library hands over, the host gives
 *     back exactly once - a payload through ak_event_consumed, a lent buffer through
 *     ak_call_send_message or ak_return_call_buffer, and the buffer ak_resize_call_buffer hands
 *     back in its place counts as the one owed - and the runtime cannot finish until it has.
 *     Exactly once is the host's to keep: unlike a handle, the owner in ak_bytes and ak_buffer is
 *     a pointer, so giving one back twice reads memory this library has freed. Undefined
 *     behaviour, not a refusal - there is nothing left to refuse with.
 *
 * Every entry point that can refuse takes ak_error *out_error as its last argument, which may be
 * NULL. On a refusal, and only then, a non-NULL out_error receives the refusal's family and its
 * message, which the host gives back through ak_error_release. A NULL out_error gets the status
 * alone, and no message is built for it.
 *
 * Every options struct starts with struct_size, which the host sets to sizeof of its own
 * definition, then version, flags and reserved, which it sets to zero. A struct_size smaller than
 * this library's definition is refused with AK_STATUS_INVALID_ARG rather than read; a larger one
 * is read up to this library's definition and the rest ignored, so a field appended to the end
 * is an addition rather than a break. A version, a flag or a reserved field that is not zero is
 * refused with AK_STATUS_INVALID_ARG.
 *
 * Metadata travels as a blob:
 *
 *     uint32_t count
 *     repeated count times {
 *         uint32_t key_len;   key_len bytes
 *         uint32_t value_len; value_len bytes
 *     }
 *
 * A key ending in "-bin" carries raw bytes; every other value is printable ASCII. An empty blob
 * and a blob of count zero mean the same thing.
 *
 * The AK_EVENT_STATUS payload is:
 *
 *     uint32_t message_len; message_len bytes    the reason, UTF-8
 *     the trailing metadata, as a blob
 *
 * The status code itself is ak_event.status_code, not part of the payload.
 *
 * Integers in the blobs are in native byte order. This ABI runs in-process between this library
 * and its host; it is not a wire format.
 */

#ifndef ARMONIK_TRANSPORT_FFI_H
#define ARMONIK_TRANSPORT_FFI_H

#include <stddef.h>
#include <stdint.h>

/**
 * In ak_log_record.level: 1 is the most severe and 5 the most verbose. A host maps them to its
 * own, and has no use for a value it does not know.
 */
#define AK_LOG_ERROR 1

#define AK_LOG_WARN 2

#define AK_LOG_INFO 3

#define AK_LOG_DEBUG 4

#define AK_LOG_TRACE 5

/**
 * In ak_config.flags: the configuration has no prefix, so a file's document is the whole file.
 */
#define AK_CONFIG_NO_PREFIX 1

/**
 * In ak_stats.flags, written by the library: it keeps counters. Clear, the structure is empty and
 * every field past the first four is zero.
 */
#define AK_STATS_COUNTING 1

/**
 * In ak_call_start_options.flags: timeout_ns states the call's deadline.
 */
#define AK_CALL_HAS_DEADLINE 1

/**
 * In ak_call_start_options.flags: the response is at most one message, as on a unary or a
 * client-streaming method. A server that sends a second one ends the call with the gRPC status
 * INTERNAL, and the second is neither delivered nor charged to the runtime's memory. The status
 * that follows the message is read whatever the runtime's first memory threshold says, so a host
 * may hold the message until the status is in.
 */
#define AK_CALL_ONE_RESPONSE 2

/**
 * In ak_call_start_options.flags: the request is exactly one message, as on a unary or a
 * server-streaming method. ak_call_send_message also ends the sending, ak_call_end_send is
 * refused with AK_STATUS_INVALID_STATE, and no AK_EVENT_WRITE_DONE comes: the send is settled
 * when it is committed, and an ak_get_call_buffer after it answers AK_STATUS_INVALID_STATE. The
 * call sends nothing until its commit, and nothing watches its deadline before: a commit past it
 * is accepted and the call ends DEADLINE_EXCEEDED, and a call never committed ends at its
 * cancellation.
 */
#define AK_CALL_ONE_REQUEST 4

/**
 * In ak_call_start_options.flags: the call waits for the channel to open a connection rather than
 * end UNAVAILABLE when it cannot reach its server, as gRPC's wait-for-ready has it. The channel
 * dials again, backing off as gRPC's connection backoff does, and the call goes out on the first
 * connection it opens. The wait ends at the call's deadline (DEADLINE_EXCEEDED), on its
 * cancellation, or when its channel is released; otherwise it lasts as long as the server stays
 * out of reach. A call that reached a connection is not helped: what breaks it after that ends it
 * as it ends any other.
 */
#define AK_CALL_WAIT_FOR_READY 8

#define AK_ABI_VERSION 1

/**
 * Returned by every entry point that can fail. ak_event_consumed, ak_return_call_buffer and
 * ak_channel_release are void because a wrong token is a host bug the ABI cannot report anywhere
 * useful; ak_runtime_status, ak_channel_status and ak_abi_version return their answer.
 */
enum ak_status
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    AK_STATUS_OK = 0,
    /**
     * The object is gone; the token names nothing.
     */
    AK_STATUS_HANDLE_STALE = 1,
    /**
     * This call's send window is full - backpressure, not an error; retry when a WRITE_DONE
     * arrives. That acquittal says this library has taken the message and the host's buffer is
     * free; it says nothing about the peer, and does not wait on one - the wake-up is promised,
     * its timing is not.
     */
    AK_STATUS_SLOT_BUSY = 2,
    /**
     * A null pointer, or an options struct that is too short or sets a version, a flag or a
     * reserved field.
     */
    AK_STATUS_INVALID_ARG = 3,
    /**
     * A fault the ABI cannot attribute.
     */
    AK_STATUS_INTERNAL = 4,
    /**
     * The runtime-wide byte ceiling is reached - retry at the call's next AK_EVENT_BUDGET_WAKE.
     * Until the send is served or the call ends, reads are held back for it across the whole
     * runtime, so a host woken must try again or cancel the call. A refused ak_resize_call_buffer
     * is none of this: it records no wait, and a host that waits lends again.
     */
    AK_STATUS_BUDGET_BUSY = 5,
    /**
     * A valid handle at the wrong moment: a send after the terminal, a start while stopping, a
     * destroy before quiescence. A guard refused, which is not a fault.
     */
    AK_STATUS_INVALID_STATE = 6,
    /**
     * The length exceeds the ceiling itself, so no return by anyone will ever make room.
     * Permanent; do not retry.
     */
    AK_STATUS_MESSAGE_TOO_LARGE = 7,
    /**
     * The host wrote past a buffer it was lent, or committed or kept more bytes than it was
     * lent. The memory around the buffer may be corrupted: the buffer is taken back without
     * being freed, and the runtime shuts down. Permanent.
     */
    AK_STATUS_CORRUPTED = 8,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum ak_status ak_status;
#else
typedef int32_t ak_status;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

enum ak_event_kind
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    /**
     * payload = metadata blob (owned), status_code = its origin.
     */
    AK_EVENT_INITIAL_METADATA = 1,
    /**
     * payload = message bytes (owned).
     */
    AK_EVENT_MESSAGE = 2,
    /**
     * Terminal - payload = reason + trailers (owned).
     */
    AK_EVENT_STATUS = 3,
    /**
     * An accepted send is settled; its slot is already free.
     */
    AK_EVENT_WRITE_DONE = 4,
    /**
     * The runtime has stopped running.
     */
    AK_EVENT_SHUTDOWN_COMPLETE = 5,
    /**
     * And now nothing of it is outstanding.
     */
    AK_EVENT_RESOURCES_RELEASED = 6,
    /**
     * A release gave bytes back since this call's send was refused with AK_STATUS_BUDGET_BUSY:
     * try it again. Every call refused since the last release is woken, and none is promised
     * the room: another may take it first.
     */
    AK_EVENT_BUDGET_WAKE = 7,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum ak_event_kind ak_event_kind;
#else
typedef int32_t ak_event_kind;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * Carried by AK_EVENT_SHUTDOWN_COMPLETE and by nothing else.
 */
enum ak_host_debt
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    /**
     * Nothing of ours is in your hands; no second event.
     */
    AK_HOST_NOTHING_TO_RETURN = 0,
    /**
     * Consume the payloads, return the buffers; AK_EVENT_RESOURCES_RELEASED follows.
     */
    AK_HOST_MUST_RETURN = 1,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum ak_host_debt ak_host_debt;
#else
typedef int32_t ak_host_debt;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * Why a fallible entry point refused, beyond what its status says.
 */
enum ak_error_kind
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    /**
     * No family: the status says what happened - backpressure, a request too large for the
     * ceiling, a fault this library cannot attribute. Zero, so a zero-initialized ak_error reads
     * as nothing more to say.
     */
    AK_ERROR_NONE = 0,
    /**
     * The configuration document or the endpoint, before any socket.
     */
    AK_ERROR_CONFIG = 1,
    /**
     * DNS, TCP, TLS handshake.
     */
    AK_ERROR_CONNECTION = 2,
    /**
     * HTTP/2 or gRPC framing, after a connection.
     */
    AK_ERROR_TRANSPORT = 3,
    AK_ERROR_TIMEOUT = 4,
    AK_ERROR_CANCELLED = 5,
    /**
     * The host used the ABI in a way it does not admit: a null pointer, a handle that names
     * nothing, a downcall at a moment its object refuses it.
     */
    AK_ERROR_USAGE = 6,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum ak_error_kind ak_error_kind;
#else
typedef int32_t ak_error_kind;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * Only QUIESCENT permits ak_runtime_destroy or unloading the library. The host reaches it by
 * acting, not by waiting: while it still holds something the status stays STOPPED, and the
 * AK_EVENT_SHUTDOWN_COMPLETE callback says so through its host_debt field. Polling for QUIESCENT
 * before returning what it holds is therefore a deadlock.
 *
 * NONE is what keeps a handle a token rather than a pointer: a handle this library does not
 * know - never created, or reclaimed by ak_runtime_destroy - is reported, not resolved.
 * It is not QUIESCENT, which would tell a host that passed a channel handle by mistake that it
 * may destroy the runtime and unload the library while one is running.
 */
enum ak_runtime_state
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    /**
     * This library knows no such runtime.
     */
    AK_RUNTIME_NONE = 0,
    /**
     * Operational, accepts channels and calls.
     */
    AK_RUNTIME_RUNNING = 1,
    /**
     * Start gate closed, channels closing.
     */
    AK_RUNTIME_GRPC_STOPPING = 2,
    /**
     * The gRPC side is done; the host may still hold memory.
     */
    AK_RUNTIME_GRPC_STOPPED = 3,
    /**
     * And nothing of it is outstanding either.
     */
    AK_RUNTIME_QUIESCENT = 4,
    /**
     * Quiescence impossible, destroy refused. Reported when the status itself cannot be read,
     * when the task driving the shutdown dies, and when that shutdown cannot get a thread of its
     * own: the three ways the step to QUIESCENT stops being reachable. A shutdown that is merely
     * slow stays GRPC_STOPPING.
     */
    AK_RUNTIME_FAILED_UNQUIESCED = 5,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum ak_runtime_state ak_runtime_state;
#else
typedef int32_t ak_runtime_state;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * How far along a channel's closing is. A handle this library no longer knows reads as NONE,
 * which is also what an unopened one reads as: neither names a channel.
 */
enum ak_channel_state
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    AK_CHANNEL_NONE = 0,
    /**
     * Takes calls.
     */
    AK_CHANNEL_OPEN = 1,
    /**
     * Released, its calls draining.
     */
    AK_CHANNEL_CLOSING = 2,
    /**
     * And nothing of it is active any more.
     */
    AK_CHANNEL_CLOSED = 3,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum ak_channel_state ak_channel_state;
#else
typedef int32_t ak_channel_state;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * Carried by AK_EVENT_INITIAL_METADATA in status_code: where the head came from. The event comes
 * first on every call, and its metadata is empty unless the peer's headers were delivered. Zero
 * is the peer's headers, so a host that ignores the field takes every head for the peer's.
 */
enum ak_head_origin
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    /**
     * The peer's response headers.
     */
    AK_HEAD_RECEIVED = 0,
    /**
     * A response came and delivered no head - the Trailers-Only shape, or an answer refused
     * before its body; the terminal is the call's status, the peer's unless the call was stopped
     * here first.
     */
    AK_HEAD_TRAILERS_ONLY = 1,
    /**
     * No response reached the call.
     */
    AK_HEAD_NO_RESPONSE = 2,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum ak_head_origin ak_head_origin;
#else
typedef int32_t ak_head_origin;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * Where a source of ak_config is read from, in ak_config_source.kind.
 */
enum ak_source_kind
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    /**
     * value: the file's path, UTF-8. JSON, YAML or TOML by its extension - .json, .yaml or .yml,
     * .toml - its document the section the prefix names, or the whole file with
     * AK_CONFIG_NO_PREFIX. A file that does not exist is refused.
     */
    AK_SOURCE_FILE = 1,
    /**
     * value: the file's path, read as AK_SOURCE_FILE's, except that a file that does not exist
     * contributes nothing.
     */
    AK_SOURCE_OPTIONAL_FILE = 2,
    /**
     * value: empty. The variables whose name starts with the prefix and `__`, the rest of the
     * name the key's path, its parts joined by `__` and compared without case, and the value text
     * read by its key's type. Read once, by ak_runtime_create_from. Refused with
     * AK_CONFIG_NO_PREFIX: every variable of the process would be a key.
     */
    AK_SOURCE_ENVIRONMENT = 3,
    /**
     * value: a JSON document in the vocabulary of runtime.schema.json, with no prefix around it.
     */
    AK_SOURCE_DOCUMENT = 4,
    /**
     * value: a JSON object whose names are keys' paths, their parts joined by `__` under no
     * prefix, and whose values are text, read as the environment's are.
     */
    AK_SOURCE_PAIRS = 5,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum ak_source_kind ak_source_kind;
#else
typedef int32_t ak_source_kind;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * Bytes the host lends this library for the duration of one downcall.
 */
typedef struct {
    const uint8_t *ptr;
    size_t len;
} ak_bytes_in;

/**
 * One field of a logged event: the name the engine gave it, and its value rendered as text. Both
 * views are valid for the callback alone.
 */
typedef struct {
    ak_bytes_in key;
    ak_bytes_in value;
} ak_log_field;

/**
 * An event the engine logs, as the log callback receives it. Everything it points at is valid for
 * the callback's duration only, and nothing of it is the host's to give back: a host that keeps
 * a record copies it.
 *
 * Starts with struct_size, the size of the record this library built: a host reads only the
 * fields that lie within it. The text is UTF-8, and carries neither a source location nor a
 * time, which the host's own logger stamps.
 */
typedef struct {
    /**
     * sizeof this record as this library defines it.
     */
    uint32_t struct_size;
    /**
     * An AK_LOG_ level.
     */
    uint32_t level;
    /**
     * What emitted it: the Rust module path, such as armonik_transport::grpc::channel, or h2.
     */
    ak_bytes_in target;
    /**
     * The event's text.
     */
    ak_bytes_in message;
    /**
     * How many fields `fields` points at.
     */
    size_t field_count;
    /**
     * The event's other values, in the order it names them. NULL when field_count is zero.
     */
    const ak_log_field *fields;
} ak_log_record;

/**
 * Receives the engine's logs: one call per event the runtime's filter admits, as it happens, on
 * the thread that logged it - this library's, or the host's own inside a downcall that logs, as
 * the runtime's creation does for what its configuration's load logged. Given once, when the
 * runtime is created, and never replaced or removed. Several threads may call it at once.
 *
 * It keeps the runtime callback's contract: record the event where the host's own thread will
 * find it, and return. It must not parse, take a lock the host's own code holds, run application
 * code, or call this library: an event logged from inside it is dropped. A host whose logger runs
 * application code copies the record into a queue of its own and writes it from a thread of its
 * own.
 *
 * The function and `log_ctx` stay callable until ak_runtime_destroy returns, or until the
 * creation call returns when it is refused; nothing reaches them after.
 */
typedef void (*ak_log_callback)(void *log_ctx, const ak_log_record *record);

typedef struct {
    uint32_t struct_size;
    /**
     * Zero, the one revision of this record there is.
     */
    uint32_t version;
    /**
     * Zero: no flag is defined, and a set one is refused rather than ignored.
     */
    uint32_t flags;
    /**
     * Zero.
     */
    uint32_t reserved;
    /**
     * Bytes past which work waits, counting the buffers lent and the messages received until
     * the host consumes them: a call stops reading, and a lend is refused with
     * AK_STATUS_BUDGET_BUSY. Zero, or more than this library can lend, asks for its own: four
     * gigabytes, or half the address space where that is smaller - the gRPC length prefix and the
     * allocator between them admit no more, so a budget above it is one no single lend could draw
     * on.
     */
    uint64_t memory_ceiling;
    /**
     * Bytes past which the engine stops: a received message that would take the count past it
     * ends its call with RESOURCE_EXHAUSTED. Calls admitted to read below memory_ceiling may pass
     * it together, by a message each, and this bounds them. Zero is a quarter above the first
     * threshold in force, memory_ceiling or this library's own; a value below that threshold is
     * AK_STATUS_INVALID_ARG.
     */
    uint64_t memory_hard_ceiling;
    /**
     * A channel document, in the vocabulary of ak_channel_create's config_json, whose options
     * every channel of the runtime takes where its own document states none: the two are merged
     * option by option, a struct's options within it, and the channel's win; an alternative - how
     * the server is verified, who the client is, which proxy - merges its fields over the same
     * alternative and is taken whole over another. Empty states none.
     * Refused with AK_STATUS_INVALID_ARG where ak_channel_create would refuse it.
     */
    ak_bytes_in channel_defaults_json;
    /**
     * Receives the engine's logs, filtered by `*=warn,armonik_transport*=info`: the runtime option
     * Logging.Filter, which only ak_runtime_create_from loads, is the one way to another. NULL for
     * none.
     */
    ak_log_callback log_callback;
    /**
     * Handed to `log_callback` with each record.
     */
    void *log_ctx;
} ak_runtime_config;

/**
 * Chosen by the host, returned in each callback for its call. Opaque: never dereferenced here.
 * Must stay valid until the call's terminal (AK_EVENT_STATUS).
 */
typedef void *ak_call_ctx;

/**
 * Owned by the host after reception, until ak_event_consumed.
 *
 * owner, not ptr, identifies the allocation: the view may be a slice of a larger one. owner ==
 * NULL means unowned, never "empty" - a zero-length payload that took a delivery credit carries a
 * real owner and MUST be consumed, because the credit comes back with the acquittal and not with
 * the bytes.
 */
typedef struct {
    const uint8_t *ptr;
    size_t len;
    void *owner;
} ak_bytes;

/**
 * On the callback's stack; no lifecycle of its own. The payload is owned when owner is not NULL.
 *
 * WRITE_DONE, BUDGET_WAKE, SHUTDOWN_COMPLETE and RESOURCES_RELEASED carry no payload: ptr ==
 * NULL, len == 0, owner == NULL. ak_event_consumed on such a payload is a no-op, so a host may
 * route every event through one path.
 */
typedef struct {
    ak_event_kind kind;
    ak_bytes payload;
    /**
     * gRPC status for AK_EVENT_STATUS, ak_head_origin for AK_EVENT_INITIAL_METADATA, zero on
     * every other event.
     */
    int32_t status_code;
    /**
     * AK_EVENT_SHUTDOWN_COMPLETE only.
     */
    ak_host_debt host_debt;
} ak_event;

/**
 * The function pointer must stay valid for the runtime's lifetime, and runtime_ctx until the
 * runtime's last event.
 *
 * Each callback carries `count` events, at least one, of one call or of the runtime, in delivery
 * order. The array and its events are valid for the callback's duration only; the payloads they
 * own are the host's until given back. Several events come together only when they are data
 * events (INITIAL_METADATA, MESSAGE, STATUS) of one call that were ready together, or that its
 * delivery waited to gather (Grpc.Host.Receive.CoalescingBytes); every other event comes
 * alone.
 *
 * Data callbacks are serialized per call and concurrent between calls. WRITE_DONE and
 * BUDGET_WAKE may arrive in parallel with any of them, including for the same call: a per-call
 * lock in the handler would hold the slot release hostage behind a slow message handler. Both
 * come before the call's STATUS, which stays its last event.
 *
 * A callback runs on one of this library's own threads: a call's events on its channel's
 * thread, which runs that channel's connection and every call on it; AK_EVENT_SHUTDOWN_COMPLETE
 * on the runtime's own; AK_EVENT_RESOURCES_RELEASED on the thread that finishes the shutdown.
 * Every promise made here about progress - a send reaching the wire, an acquittal, a call being
 * reclaimed, a shutdown completing - is made on those threads. So the callback must publish and
 * return: record the event where the host's own thread will find it, hand the payload on, and
 * end. It must not parse, allocate what it could have allocated earlier, take a lock the host's
 * own code holds, or run application code. A host that blocks here does not slow itself down; it
 * stops what that thread runs - a channel, or the shutdown - and the guarantees above stop with
 * it.
 */
typedef void (*ak_callback)(void *runtime_ctx,
                            ak_call_ctx call_ctx,
                            const ak_event *events,
                            size_t count);

typedef uint64_t ak_handle;

/**
 * Filled by this library, read by the host, and written only when the status is not
 * AK_STATUS_OK. Fixed layout, with no size prefix: ak_abi_version() is the agreement.
 */
typedef struct {
    ak_error_kind kind;
    /**
     * UTF-8, the cause chain flattened into one message. detail.owner == NULL means there is
     * nothing to free. Released by ak_error_release, never by ak_event_consumed.
     */
    ak_bytes detail;
} ak_error;

/**
 * One source of a configuration.
 */
typedef struct {
    /**
     * An ak_source_kind; another is AK_STATUS_INVALID_ARG.
     */
    uint32_t kind;
    /**
     * Zero; another is AK_STATUS_INVALID_ARG.
     */
    uint32_t reserved;
    /**
     * What the kind says, UTF-8; one that is not is AK_STATUS_INVALID_ARG.
     */
    ak_bytes_in value;
} ak_config_source;

/**
 * Where a runtime's configuration comes from: sources, read in order when the runtime is created,
 * a later one over an earlier one option by option. A key the vocabulary does not declare is
 * ignored rather than refused; a value that does not fit its key is refused, with its source and
 * its path, and never quoted.
 *
 * Versioned as the options structs are, but for its fourth field, which is source_count rather
 * than reserved.
 */
typedef struct {
    uint32_t struct_size;
    /**
     * Zero, the one revision of this record there is.
     */
    uint32_t version;
    /**
     * AK_CONFIG_NO_PREFIX or none. Any other flag is refused rather than ignored.
     */
    uint32_t flags;
    /**
     * How many sources `sources` points at.
     */
    uint32_t source_count;
    /**
     * The sources, in order, a later one over an earlier one. May be NULL when source_count is
     * zero.
     */
    const ak_config_source *sources;
    /**
     * The prefix, UTF-8: the section of a file, and the start of an environment variable's name,
     * the configuration is read from. Empty is `ArmoniK__Client__Grpc`; with AK_CONFIG_NO_PREFIX it
     * has to be empty.
     */
    ak_bytes_in prefix;
    /**
     * Receives the engine's logs, filtered by the runtime's option Logging.Filter; NULL for none.
     * NULL when the host's struct_size ends before this field.
     */
    ak_log_callback log_callback;
    /**
     * Handed to `log_callback` with each record.
     */
    void *log_ctx;
} ak_config;

typedef struct {
    /**
     * The buffers lent and the messages received and not yet given back, atomic snapshot. Past
     * `ceiling` by up to a message per call admitted to read, and never past the second
     * threshold. The spare arenas channels keep to lend again are not in it: they fit under
     * `ceiling` beside it, give their room to any charge that needs it, and are kept until then
     * or until their channel closes.
     */
    uint64_t bytes_used;
    /**
     * The limit in force, which is what was configured or this library's own where that is
     * smaller. Never zero.
     */
    uint64_t ceiling;
} ak_memory_usage;

/**
 * What the engine counts and reads of its own state, over every channel of a runtime, as
 * ak_runtime_stats writes it. Counters only grow; a gauge is the state at the call.
 *
 * A third kind of record, beside the options a host fills and the records this library fills
 * whole. It starts with struct_size, version, flags and reserved, and every field after them is
 * a `uint64_t`, a `double` or an array of `uint64_t`, so that its layout is the same on every
 * target whatever alignment an eight-byte integer has. The host sets struct_size to the size of
 * its definition, at least those four fields, and the rest of the head to zero; the library
 * writes the eight-byte words that lie within that size, and sets struct_size to the number of
 * bytes it wrote. A field past it reads as zero in a host that zeroed its record first. A host
 * that passes the four fields alone learns whether the library counts, from flags.
 *
 * A library built without its `metrics` feature answers AK_STATUS_OK with flags clear and every
 * counter zero: one ABI serves both builds. The structure's size and the lengths of its arrays
 * are fixed; a slot added to an array is a new array or a new ABI version, and a field is
 * appended.
 *
 * An array is indexed by its slots: calls_ended by the gRPC status number, 0 to 16, and
 * streams_reset by the HTTP/2 error code of RFC 9113, 0 to 13, the last slot being any other.
 * retries is indexed by what failed and was retried: slots 0 to 15 the gRPC statuses 1 to 16 as
 * the server stated them, 16 to 22 an HTTP status that stated none of them (408, 429, 500, 502,
 * 503, 504, then any other), 23 to 37 a reset by the slots of streams_reset, 38 a pushback, 39 a
 * dial, 40 a connection (which a GOAWAY that left a call unprocessed counts as). A retry is
 * counted when it is sent. connections_closed is indexed by the reason a session ended: 0 the
 * peer's GOAWAY, 1 a keepalive that timed out, 2 the engine's idle timeout, 3 an I/O error, 4
 * the engine closing its channel, 5 the peer closing the stream of bytes with no GOAWAY, 6 an
 * HTTP/2 protocol error, 7 something else.
 */
typedef struct {
    /**
     * In: sizeof the record the host was built with, at least 16. Out: the bytes written.
     */
    uint32_t struct_size;
    /**
     * Zero, the one revision of this record there is.
     */
    uint32_t version;
    /**
     * In: zero. Out: AK_STATS_COUNTING or none.
     */
    uint32_t flags;
    /**
     * Zero.
     */
    uint32_t reserved;
    /**
     * Calls started.
     */
    uint64_t calls_started;
    /**
     * Calls ended, by the status they ended with.
     */
    uint64_t calls_ended[17];
    /**
     * Messages taken from the calls' request streams, once whatever the attempts that send them,
     * and read off their responses.
     */
    uint64_t messages_sent;
    uint64_t messages_received;
    /**
     * Retries, by what was retried; see the slots above.
     */
    uint64_t retries[41];
    /**
     * Retries the adaptive estimate of a channel stopped.
     */
    uint64_t retries_refused;
    /**
     * Calls whose messages outgrew a replay ceiling, so that they are never tried again.
     */
    uint64_t calls_not_replayable;
    /**
     * Requests the peer's application never processed, sent again at once.
     */
    uint64_t resends;
    uint64_t dials_tried;
    uint64_t dials_succeeded;
    uint64_t dials_failed;
    /**
     * Sessions that ended, by reason; see the slots above.
     */
    uint64_t connections_closed[8];
    /**
     * Streams the peer reset, by HTTP/2 error code, whether or not a call was on them.
     */
    uint64_t streams_reset[15];
    /**
     * The HTTP/2 bytes the connections wrote and read, above TLS.
     */
    uint64_t wire_bytes_sent;
    uint64_t wire_bytes_received;
    /**
     * The bytes of the messages as their callers wrote them, and as the engine sent them, the
     * gRPC prefix of each left out: a message once, whatever the attempts that send it.
     */
    uint64_t message_bytes_raw;
    uint64_t message_bytes_sent;
    /**
     * Deliveries that found every credit of Grpc.Host.Receive.Window spent.
     */
    uint64_t host_window_waits;
    /**
     * Reads held back, and sends made to wait, by the memory ceiling.
     */
    uint64_t host_memory_waits;
    /**
     * Sends refused with AK_STATUS_BUDGET_BUSY, and received messages dropped, by the ceiling.
     */
    uint64_t host_memory_refusals;
    /**
     * Gauge: the rate of first attempts, a second, that the channels whose estimate caps them
     * allow together; zero when none does.
     */
    double throttle_cap_per_second;
    /**
     * Gauge: channels whose first attempts are capped.
     */
    uint64_t channels_capped;
    /**
     * Gauge: channels whose estimate has stopped retries.
     */
    uint64_t channels_retries_closed;
    /**
     * Gauge: calls waiting for their turn at a cap.
     */
    uint64_t calls_waiting_at_cap;
    /**
     * Gauge: calls waiting for a session to open or to have room for them.
     */
    uint64_t calls_waiting_for_stream;
} ak_stats;

typedef struct {
    /**
     * At least the offset of timeout_ns: a host built before that field passes no deadline.
     */
    uint32_t struct_size;
    /**
     * Zero, the one revision of this record there is.
     */
    uint32_t version;
    /**
     * AK_CALL_HAS_DEADLINE, AK_CALL_ONE_RESPONSE, AK_CALL_ONE_REQUEST and AK_CALL_WAIT_FOR_READY,
     * any of them or none. Any other flag is refused rather than ignored.
     */
    uint32_t flags;
    /**
     * Zero.
     */
    uint32_t reserved;
    /**
     * "/Service/Method", not NUL-terminated.
     */
    ak_bytes_in method;
    /**
     * A metadata blob - a uint32_t count, then each key and each value as a uint32_t length and
     * its bytes; may be empty.
     */
    ak_bytes_in metadata;
    /**
     * With AK_CALL_HAS_DEADLINE, the nanoseconds from ak_call_start to the call's deadline, which
     * ends it DEADLINE_EXCEEDED and is sent to the server as grpc-timeout. Zero is a deadline
     * already passed: the call ends without reaching the server. Without the flag, the
     * channel's default deadline applies, and the field is ignored.
     */
    uint64_t timeout_ns;
} ak_call_start_options;

/**
 * Lent by ak_get_call_buffer out of the call's arena. The host writes at most len bytes from its
 * start and gives it back exactly once, by ak_call_send_message, which says how many it wrote,
 * or ak_return_call_buffer. ak_resize_call_buffer exchanges it for another and does not end the
 * obligation: the one it hands back is the host's to give back in its turn. This library never
 * reclaims a lent buffer on its own - not on cancellation, not on channel close - which is what
 * removes the race between a writing thread and a cancelling one.
 */
typedef struct {
    uint8_t *ptr;
    size_t len;
    void *owner;
} ak_buffer;

typedef struct {
    /**
     * Delivered, not yet ak_event_consumed.
     */
    uint32_t payloads_owed;
    /**
     * Out of the arena, not yet given back.
     */
    uint32_t buffers_lent;
    /**
     * The runtime's own, informational.
     */
    uint32_t callbacks_in_flight;
    /**
     * 0 or 1.
     */
    int32_t terminal_delivered;
} ak_call_debt;

#define AK_HANDLE_NONE (ak_handle)0

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Creates a runtime, synchronously; it starts in AK_RUNTIME_RUNNING. One exists at a time: a
 * second create before the first is destroyed is refused with AK_STATUS_INVALID_STATE. Each
 * channel created on it runs on a thread of its own, so that a call never moves between threads.
 * AK_RUNTIME_QUIESCENT means those threads are gone too.
 *
 * # Safety
 *
 * `config` and `out` must be valid for their types, and `callback` must stay callable with
 * `runtime_ctx` until the runtime's last event. `config.log_callback`, when it is set, must stay
 * callable with `config.log_ctx` until `ak_runtime_destroy` returns, or until this call returns
 * when it refuses.
 * `out_error` must be null or writable for an `ak_error`.
 */
ak_status ak_runtime_create(const ak_runtime_config *config,
                            ak_callback callback,
                            void *runtime_ctx,
                            ak_handle *out,
                            ak_error *out_error);

/**
 * Creates a runtime, as ak_runtime_create does, from the sources `config` lists: read in order,
 * a later one over an earlier one option by option, into the vocabulary of runtime.schema.json -
 * the endpoint, the memory ceilings, and the channel defaults every channel's own document is
 * merged over.
 *
 * What is malformed in `config` itself - a kind it does not name, a reserved field or a flag it
 * does not know, a value on an environment source, a prefix beside AK_CONFIG_NO_PREFIX, a byte
 * view that is null or not UTF-8 - is AK_STATUS_INVALID_ARG before any source is read. A source
 * that is refused is AK_STATUS_INVALID_ARG too, its message naming the source and the key's path,
 * never the value; so is a loaded option the runtime cannot be created with: a ceiling of zero,
 * an Endpoint that is not a URI, or channel defaults a channel's own document would be refused
 * for.
 *
 * # Safety
 *
 * `config` and `out` must be valid for their types, `config.sources` must point at
 * `source_count` sources unless that is zero, and every byte view at its length. `callback` must
 * stay callable with `runtime_ctx` until the runtime's last event. `config.log_callback`, when it
 * is set, must stay callable with `config.log_ctx` until `ak_runtime_destroy` returns, or until
 * this call returns when it refuses.
 * `out_error` must be null or writable for an `ak_error`.
 */
ak_status ak_runtime_create_from(const ak_config *config,
                                 ak_callback callback,
                                 void *runtime_ctx,
                                 ak_handle *out,
                                 ak_error *out_error);

/**
 * The runtime's state. Synchronous, non-blocking, and callable from any thread, including from
 * inside a callback.
 */
ak_runtime_state ak_runtime_status(ak_handle runtime);

/**
 * Closes the start gate and drains. AK_EVENT_SHUTDOWN_COMPLETE follows. Idempotent.
 *
 * # Safety
 *
 * `out_error` must be null or writable for an `ak_error`.
 */
ak_status ak_runtime_begin_shutdown(ak_handle runtime, ak_error *out_error);

/**
 * Frees the runtime. Refused before AK_RUNTIME_QUIESCENT, and that is the only reason.
 *
 * Live call and channel handles do not block it: destroy stales every handle of this runtime at
 * once, and a later downcall on one returns AK_STATUS_HANDLE_STALE. A handle names runtime-owned
 * state, so the runtime may reclaim it; a payload or a lent buffer is memory the host may still
 * be reading or writing, so only the host can end it.
 *
 * # Safety
 *
 * `out_error` must be null or writable for an `ak_error`.
 */
ak_status ak_runtime_destroy(ak_handle runtime, ak_error *out_error);

/**
 * What the runtime-wide byte ceiling is holding. Synchronous, non-blocking and observational: it
 * changes nothing.
 *
 * # Safety
 *
 * `out` must be writable.
 * `out_error` must be null or writable for an `ak_error`.
 */
ak_status ak_runtime_memory_usage(ak_handle runtime, ak_memory_usage *out, ak_error *out_error);

/**
 * What the engine counts and reads of its own state, over every channel of the runtime: the
 * calls, retries, connections, bytes and waits, and the gauges of the throttle. Synchronous,
 * non-blocking and observational: it changes nothing.
 *
 * `out` is a record the host sizes and this library fills, which ak_stats describes: the host
 * sets `struct_size` to the size of its own definition, at least the first four fields, and zero
 * to the others of the head. The library writes the eight-byte words that lie within that size and
 * sets `struct_size` to what it wrote. A library built without its `metrics` feature answers
 * AK_STATUS_OK with `flags` clear and every counter zero, never a status that says it is not
 * supported, so that one host serves either build.
 *
 * An `out` whose `struct_size` is below sixteen, or whose version, flags or reserved is not zero,
 * is AK_STATUS_INVALID_ARG, as is a null `out`; a runtime handle that names nothing is
 * AK_STATUS_HANDLE_STALE.
 *
 * # Safety
 *
 * `out` must be writable for the `struct_size` it states, and its first sixteen bytes initialized.
 * `out_error` must be null or writable for an `ak_error`.
 */
ak_status ak_runtime_stats(ak_handle runtime, ak_stats *out, ak_error *out_error);

/**
 * Creates a channel on an endpoint, configured by a JSON document. Synchronous: it reads the
 * certificate files the document names, and resolves no name and opens no socket until the
 * channel's first call. A bad endpoint or a bad document is AK_STATUS_INVALID_ARG, a file that
 * cannot be read or holds nothing usable included, and so is a null out or a null slice with a
 * non-zero length; a runtime handle that names nothing is AK_STATUS_HANDLE_STALE, and one that is
 * shutting down is AK_STATUS_INVALID_STATE.
 *
 * The endpoint is its own argument, as UTF-8 - "http://host:port" in the clear, or
 * "https://host:port" over TLS. An empty one is the Endpoint of the runtime's configuration, and
 * is AK_STATUS_INVALID_ARG when that names none. Every option of the document has a default, and
 * `{}` is a valid configuration.
 *
 * The document is structured and typed, and a JSON schema states it: objects nest, and a number is
 * a number and not a string spelled like one. A key no option declares is ignored rather than
 * refused. That schema, `options.schema.json`, names each option with its type and, where it has
 * them, its range and default.
 *
 * ak_channel_delivery_window reads back the delivery window the channel ended up with.
 *
 * The two windows mirror each other. Grpc.Host.Receive.Window bounds the payloads of one call
 * outstanding at once, each taking one credit, one place of the window - the terminal status takes
 * none, so a host holds at most one more - and the host chooses it because the host is what has
 * to hold them. Grpc.Host.Send.Window
 * bounds the buffers one call may have out, counting those being filled and those awaiting their
 * WRITE_DONE. Grpc.Host.Receive.Window defaults to 4 and Grpc.Host.Send.Window to 1, and
 * the schema states the range either may take.
 *
 * A call whose payloads the host does not consume reads a few messages past its spent credits,
 * which the engine holds outside what the credits count, and then stops reading its stream; what
 * its peer sends meanwhile holds the connection's HTTP/2 window. Every call of the channel shares
 * that window, so enough unread calls stop the others receiving.
 *
 * # Safety
 *
 * `config_json` must point at its bytes for the duration of the call, and `out` must be
 * writable.
 * `out_error` must be null or writable for an `ak_error`.
 */
ak_status ak_channel_create(ak_handle runtime,
                            ak_bytes_in endpoint,
                            ak_bytes_in config_json,
                            ak_handle *out,
                            ak_error *out_error);

/**
 * Frees the channel, cancelling its calls first.
 *
 * The cancellation is not a courtesy: the channel is closing from this moment and no closing
 * channel may have an active call, so the latch is what makes the drain this library's business
 * rather than something the host must provoke. A call parked on a delivery credit is the case
 * that needs it - it is not watching the transport, so closing the session alone would never
 * reach it.
 *
 * Idempotent. The channel goes to AK_CHANNEL_CLOSING, and once its last call has reached its
 * terminal the handle is reclaimed: from then on ak_channel_status answers AK_CHANNEL_NONE and
 * ak_call_start AK_STATUS_HANDLE_STALE. Until then the channel starts no further call -
 * ak_call_start on it answers AK_STATUS_INVALID_STATE - and a host following the drain reads
 * CLOSING and then NONE, with CLOSED at most in passing. An idle channel is reclaimed before this
 * returns.
 *
 * A channel the runtime's shutdown closed is not reclaimed: it stays AK_CHANNEL_CLOSED, and
 * nameable, until this is called or the runtime is destroyed.
 */
void ak_channel_release(ak_handle channel);

/**
 * How far along a channel's closing is. Answers NONE for a handle this library does not know,
 * which a released channel is once its last call has ended.
 *
 * What ends CLOSING is this library's own bookkeeping - the last call of the channel reaching
 * its terminal - so a host watching the drain has nothing to do but read. In particular CLOSED
 * does not wait for the host to consume what it has been given: a call past its terminal still
 * owes its payloads, and the channel is closed regardless.
 */
ak_channel_state ak_channel_status(ak_handle channel);

/**
 * The delivery window a channel was created with: Grpc.Host.Receive.Window as the channel's own
 * document, the runtime's channel defaults or this library's default settled it. Fixed for the
 * life of the channel.
 *
 * A handle this library does not know is AK_STATUS_HANDLE_STALE, and a null out
 * AK_STATUS_INVALID_ARG.
 *
 * # Safety
 *
 * `out` must be writable.
 * `out_error` must be null or writable for an `ak_error`.
 */
ak_status ak_channel_delivery_window(ak_handle channel, uint32_t *out, ak_error *out_error);

/**
 * Starts a call on a channel.
 *
 * There is no ak_call_release, on purpose. Every resource a call lends out is given back through
 * something the runtime already observes, so it knows when a terminal call owes nothing and takes
 * the handle back itself. Two consequences: the handle goes stale at a moment the host does not
 * choose, and abandoning a call is still ak_call_cancel followed by consuming through to the
 * terminal - dropping a payload on the floor keeps the runtime alive.
 *
 * # Safety
 *
 * `options` must be valid for its type and its byte views, and `out` must be writable.
 * `out_error` must be null or writable for an `ak_error`.
 */
ak_status ak_call_start(ak_handle channel,
                        const ak_call_start_options *options,
                        ak_call_ctx call_ctx,
                        ak_handle *out,
                        ak_error *out_error);

/**
 * Lends a buffer out of the call's arena to serialize into, of `len` bytes at most: the host
 * writes from its start and says how many bytes it wrote when it commits it. The buffer holds
 * whatever the allocator, or the last message the channel lent it for, left there, never read:
 * only the bytes the host says it wrote are sent.
 * Writing past `len` is an overrun, which the commit or the return may detect by the bytes this
 * library put after the end: a write that changes them is AK_STATUS_CORRUPTED, and the runtime
 * shuts down. A write that leaves them as they were goes unseen.
 *
 * One unfilled buffer at a time, whatever Grpc.Host.Send.Window says: asking for a second while
 * still holding one is AK_STATUS_INVALID_STATE, a host bug rather than backpressure. The window
 * counts those being filled and those committed and awaiting their WRITE_DONE; when it is full
 * the refusal is AK_STATUS_SLOT_BUSY, whose wake-up is this call's next WRITE_DONE. That wake-up
 * is only meaningful because a host eligible to ask holds nothing. AK_STATUS_BUDGET_BUSY is the
 * runtime-wide ceiling, whose wake-up is the call's next AK_EVENT_BUDGET_WAKE.
 * AK_STATUS_MESSAGE_TOO_LARGE is permanent. A length of zero is AK_STATUS_INVALID_ARG: an empty
 * message needs no buffer, and ak_call_send_message sends one with none. An allocator failure for
 * the buffer is AK_STATUS_INTERNAL: that lend is refused, and nothing else fails. A call that is over, or whose
 * cancellation has been requested, lends nothing: AK_STATUS_INVALID_STATE; nor does a call that
 * declared AK_CALL_ONE_REQUEST once its request is committed, no WRITE_DONE coming for a
 * SLOT_BUSY to wait on. On every refusal no buffer is lent and `*out` is untouched.
 *
 * # Safety
 *
 * `out` must be writable.
 * `out_error` must be null or writable for an `ak_error`.
 */
ak_status ak_get_call_buffer(ak_handle call,
                             size_t len,
                             ak_buffer *out,
                             ak_error *out_error);

/**
 * Commits a lent buffer as the next message, the `written` bytes the host wrote from its start.
 * Ownership passes back to this library.
 *
 * More than the buffer's length, or a write past its end that changed the bytes after it, is
 * AK_STATUS_CORRUPTED: the memory around the buffer may be corrupted, so the buffer is taken
 * back without being freed, nothing of it is sent, and the runtime shuts down. The buffer is then
 * this library's: giving it back again is a use of memory the host no longer owns.
 *
 * An empty message takes no buffer: `buffer` is then the empty one, owner NULL and len 0, with
 * `written` 0, and the send takes a slot of the window as any other, AK_STATUS_SLOT_BUSY when
 * there is none. A zeroed `ak_buffer` is that empty one, so committing the zeroed `*out` of a
 * refused ak_get_call_buffer, which the refusal leaves untouched, sends an empty message.
 *
 * AK_EVENT_WRITE_DONE settles an accepted send and frees its slot from the moment the event is
 * emitted, not when the callback returns - so a host woken by it may ask for a buffer from inside
 * the callback. It says nothing about the network: the message may have been written, or
 * abandoned because the call was cancelled. It arrives exactly once per accepted send, in send
 * order, and always before the terminal - but on a call that declared AK_CALL_ONE_REQUEST, whose
 * commit also ends the sending and settles the send: no WRITE_DONE comes for it.
 *
 * Refused with AK_STATUS_INVALID_STATE once the call is over or its cancellation has been
 * requested, after ak_call_end_send, and after a one-request call's commit. The buffer then stays
 * the host's, to give back with ak_return_call_buffer.
 *
 * # Safety
 *
 * `buffer` must be one this call lent and the host has not given back, and the host must have
 * written its first `written` bytes: they are sent as they are.
 * `out_error` must be null or writable for an `ak_error`.
 */
ak_status ak_call_send_message(ak_handle call,
                               ak_buffer buffer,
                               size_t written,
                               ak_error *out_error);

/**
 * Gives a lent buffer back unused. Legal on a cancelled or terminal call: it is the only exit for
 * a buffer whose send is refused, and the call is not reclaimed until it happens.
 *
 * Takes no call handle: the buffer determines its call. A refused ak_call_send_message therefore
 * leaves the buffer with the host, except for AK_STATUS_CORRUPTED, which takes it back. A buffer
 * given back with the bytes after its end changed is an overrun, as at the commit: it is taken
 * back without being freed and the runtime shuts down, with no status to say so but the shutdown.
 *
 * # Safety
 *
 * `buffer` must be one this call lent and the host has not given back.
 */
void ak_return_call_buffer(ak_buffer buffer);

/**
 * Exchanges a lent buffer for one of `new_len` bytes, larger or smaller, carrying over the first
 * `keep` bytes the host wrote: a host that finds its buffer too small asks for another size
 * without giving the message up. It is a lend of the new length and a return of the old one, and
 * the ceiling sees one step: the charge moves by the difference, and a growth is admitted as a
 * lend of that difference would be. The ceiling counts the charge, not the instant: the old
 * arena is still allocated while the bytes are copied.
 *
 * On success `*out` is the new buffer, whose first `keep` bytes are the old one's and whose
 * others are as a lend leaves them. The host gives back `*out`, in its turn, and never `buffer`:
 * the old memory may be reused at once. The host's one buffer and its slot of the send window
 * are the new buffer's.
 *
 * On every refusal but AK_STATUS_CORRUPTED the old buffer is still lent and the host's, as it
 * was, and `*out` is untouched. AK_STATUS_BUDGET_BUSY says the ceiling has no room for the new
 * size now: it records no wait and owes no AK_EVENT_BUDGET_WAKE, and a host that waits for room
 * gives the buffer back and lends the new length, as one that waits holds none.
 * AK_STATUS_MESSAGE_TOO_LARGE is permanent. A call that is over, or whose cancellation has been
 * requested, resizes nothing, nor does one that declared AK_CALL_ONE_REQUEST and has committed
 * it: AK_STATUS_INVALID_STATE. A `new_len` of zero, a `keep` past
 * `new_len`, a null `out` and a `buffer` that is not lent are AK_STATUS_INVALID_ARG. An
 * allocator failure is AK_STATUS_INTERNAL.
 *
 * A `keep` past the length the buffer was lent at, or a write past its end that changed the bytes
 * after it, is an overrun, as it is at the commit: AK_STATUS_CORRUPTED, the buffer taken back
 * without being freed, nothing carried over, and the runtime shutting down.
 *
 * # Safety
 *
 * `buffer` must be one this call lent and the host has not given back, and the host must have
 * written its first `keep` bytes: they are carried over as they are.
 * `out` must be writable.
 * `out_error` must be null or writable for an `ak_error`.
 */
ak_status ak_resize_call_buffer(ak_buffer buffer,
                                size_t new_len,
                                size_t keep,
                                ak_buffer *out,
                                ak_error *out_error);

/**
 * Signals end of sending. No ak_call_send_message after this: a send that comes after the end,
 * and a second end, answer AK_STATUS_INVALID_STATE. So does any end on a call that declared
 * AK_CALL_ONE_REQUEST, whose commit ends the sending, and which a host that wants no request
 * cancels.
 *
 * An end that comes while an ak_call_send_message has not yet returned on another thread - from
 * inside that send's own AK_EVENT_WRITE_DONE, which may arrive first - waits for it to return, so
 * it never goes ahead of a message the host has been told left.
 *
 * # Safety
 *
 * `out_error` must be null or writable for an `ak_error`.
 */
ak_status ak_call_end_send(ak_handle call, ak_error *out_error);

/**
 * Cancels the call, which then reaches a terminal - carrying CANCELLED, unless the peer's own
 * status was already in.
 *
 * Asynchronous: the request takes effect when the call's task observes it, so callbacks already
 * committed may still arrive after this returns, and a status the peer had already sent is the
 * one delivered. INITIAL_METADATA is never skipped.
 *
 * # Safety
 *
 * `out_error` must be null or writable for an `ak_error`.
 */
ak_status ak_call_cancel(ak_handle call, ak_error *out_error);

/**
 * What the call still owes. Purely observational; it is legal never to call it. It exists because
 * without a release downcall nothing reports a forgotten ak_return_call_buffer synchronously.
 *
 * # Safety
 *
 * `out` must be writable.
 * `out_error` must be null or writable for an `ak_error`.
 */
ak_status ak_call_debt_of(ak_handle call, ak_call_debt *out, ak_error *out_error);

int32_t ak_abi_version(void);

/**
 * Signals that the host has consumed an event's payload. Two things at once:
 *
 * 1. frees the native memory;
 * 2. arms reception of the next event for that call.
 *
 * At most Grpc.Host.Receive.Window non-consumed payloads per call, four by default: while the
 * host owes them, the runtime withholds the next data event. Only a terminal still goes out with
 * every credit - every place of the window - spent.
 *
 * The host MUST give a call's payloads back in delivery order: with several outstanding, the
 * oldest is the next one consumed. Another order is not refused - this library frees whichever
 * owner it is given - but the guarantees this header states are proved for this order alone.
 *
 * Remains legal, and required, after the terminal: the call is not reclaimed until it happens.
 *
 * # Safety
 *
 * `payload` must be one this library delivered and the host has not consumed.
 */
void ak_event_consumed(ak_bytes payload);

/**
 * Gives back several payloads in one downcall, in delivery order, each as ak_event_consumed gives
 * back one: an unowned payload, owner NULL, is a no-op, and a zero-length payload with an owner is
 * given back with its credit. `payloads` may be NULL when `count` is zero.
 *
 * # Safety
 *
 * `payloads` must point at `count` payloads this library delivered and the host has not
 * consumed.
 */
void ak_events_consumed(const ak_bytes *payloads, size_t count);

/**
 * Frees an ak_error's detail. A no-op when detail.owner is NULL, so a host may route every error
 * through it. Legal in any runtime state, and after ak_runtime_destroy.
 *
 * # Safety
 *
 * `detail` must be one this library wrote into an ak_error and the host has not released.
 */
void ak_error_release(ak_bytes detail);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* ARMONIK_TRANSPORT_FFI_H */
