/* C ABI over the ArmoniK Rust gRPC engine.
 *
 * Generated by cbindgen from the Rust declarations in armonik-transport-ffi (src/abi.rs and
 * src/lib.rs) and committed. Edits here are lost: change the Rust, then write this again with
 * `cargo run -p armonik-transport-ffi-bindgen`. The build fails while the two differ.
 * `spec/armonik_grpc_ffi/design.md` carries the reasoning; this carries the contract.
 *
 * Two rules run through all of it:
 *
 *   - A handle is a token, not a pointer. It names one object and is never handed out twice, so
 *     a downcall on something the runtime has reclaimed reports AK_STATUS_HANDLE_STALE instead of
 *     faulting - and so does one on an object of another kind.
 *   - Memory crosses in one direction at a time. What the library hands over, the host gives
 *     back exactly once - a payload through ak_event_consumed, a lent buffer through
 *     ak_call_send_message or ak_return_call_buffer - and the runtime cannot finish until it has.
 *     Exactly once is the host's to keep: unlike a handle, the owner in ak_bytes and ak_buffer is
 *     a pointer, so giving one back twice reads memory this library has freed. Undefined
 *     behaviour, not a refusal - there is nothing left to refuse with.
 *
 * Every options struct starts with struct_size, which the host sets to sizeof of its own
 * definition. A size this library does not know is refused with AK_STATUS_INVALID_ARG rather than
 * read: it names a version whose fields are not the ones read here.
 *
 * Metadata travels as a blob:
 *
 *     uint32_t count
 *     repeated count times {
 *         uint32_t key_len;   key_len bytes
 *         uint32_t value_len; value_len bytes
 *     }
 *
 * A key ending in "-bin" carries raw bytes; every other value is printable ASCII. An empty blob
 * and a blob of count zero mean the same thing.
 *
 * The AK_EVENT_STATUS payload is:
 *
 *     uint32_t message_len; message_len bytes    the reason, UTF-8
 *     the trailing metadata, as a blob
 *
 * The status code itself is ak_event.status_code, not part of the payload.
 *
 * Integers in the blobs are in native byte order. This ABI runs in-process between this library
 * and its host; it is not a wire format.
 */

#ifndef ARMONIK_TRANSPORT_FFI_H
#define ARMONIK_TRANSPORT_FFI_H

#include <stddef.h>
#include <stdint.h>

#define AK_ABI_VERSION 1

/**
 * The largest worker_threads a runtime is created with; above it, AK_STATUS_INVALID_ARG.
 *
 * A worker is an OS thread, so the useful range is the machine's core count and this is far past
 * any of them. The bound exists because the failures past it are not reportable: the runtime
 * sizes a per-worker table before creating anything, and near UINT32_MAX that allocation ends the
 * process - the one failure no status can report.
 */
#define AK_MAX_WORKER_THREADS 1024

/**
 * Returned by every entry point that can fail. ak_event_consumed, ak_return_call_buffer and
 * ak_channel_release are void because a wrong token is a host bug the ABI cannot report anywhere
 * useful; ak_runtime_status, ak_channel_status and ak_abi_version return their answer.
 */
enum ak_status
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    AK_STATUS_OK = 0,
    /**
     * The object is gone; the token names nothing.
     */
    AK_STATUS_HANDLE_STALE = 1,
    /**
     * This call's send window is full - backpressure, not an error; retry when a WRITE_DONE
     * arrives. That acquittal says this library has taken the message and the host's buffer is
     * free; it says nothing about the peer, and does not wait on one - the wake-up is promised,
     * its timing is not.
     */
    AK_STATUS_SLOT_BUSY = 2,
    /**
     * A null pointer, or a struct whose size prefix does not match any known version.
     */
    AK_STATUS_INVALID_ARG = 3,
    /**
     * A fault the ABI cannot attribute.
     */
    AK_STATUS_INTERNAL = 4,
    /**
     * The runtime-wide byte ceiling is reached - poll ak_runtime_memory_usage and retry.
     */
    AK_STATUS_BUDGET_BUSY = 5,
    /**
     * A valid handle at the wrong moment: a send after the terminal, a start while stopping, a
     * destroy before quiescence. A guard refused, which is not a fault.
     */
    AK_STATUS_INVALID_STATE = 6,
    /**
     * The length exceeds the ceiling itself, so no return by anyone will ever make room.
     * Permanent; do not retry.
     */
    AK_STATUS_MESSAGE_TOO_LARGE = 7,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum ak_status ak_status;
#else
typedef int32_t ak_status;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

enum ak_event_kind
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    /**
     * payload = metadata blob (owned), status_code = its origin.
     */
    AK_EVENT_INITIAL_METADATA = 1,
    /**
     * payload = message bytes (owned).
     */
    AK_EVENT_MESSAGE = 2,
    /**
     * Terminal - payload = reason + trailers (owned).
     */
    AK_EVENT_STATUS = 3,
    /**
     * An accepted send is settled; its slot is already free.
     */
    AK_EVENT_WRITE_DONE = 4,
    /**
     * The runtime has stopped running.
     */
    AK_EVENT_SHUTDOWN_COMPLETE = 5,
    /**
     * And now nothing of it is outstanding.
     */
    AK_EVENT_RESOURCES_RELEASED = 6,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum ak_event_kind ak_event_kind;
#else
typedef int32_t ak_event_kind;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * Carried by AK_EVENT_SHUTDOWN_COMPLETE and by nothing else.
 */
enum ak_host_debt
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    /**
     * Nothing of ours is in your hands; no second event.
     */
    AK_HOST_NOTHING_TO_RETURN = 0,
    /**
     * Consume the payloads, return the buffers; AK_EVENT_RESOURCES_RELEASED follows.
     */
    AK_HOST_MUST_RETURN = 1,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum ak_host_debt ak_host_debt;
#else
typedef int32_t ak_host_debt;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * Only QUIESCENT permits ak_runtime_destroy or unloading the library. The host reaches it by
 * acting, not by waiting: while it still holds something the status stays STOPPED, and the
 * AK_EVENT_SHUTDOWN_COMPLETE callback says so through its host_debt field. Polling for QUIESCENT
 * before returning what it holds is therefore a deadlock.
 *
 * NONE is what keeps a handle a token rather than a pointer: a handle this library does not
 * know - never created, or reclaimed by ak_runtime_destroy - is reported, not resolved.
 * It is not QUIESCENT, which would tell a host that passed a channel handle by mistake that it
 * may destroy the runtime and unload the library while one is running.
 */
enum ak_runtime_state
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    /**
     * This library knows no such runtime.
     */
    AK_RUNTIME_NONE = 0,
    /**
     * Operational, accepts channels and calls.
     */
    AK_RUNTIME_RUNNING = 1,
    /**
     * Start gate closed, channels closing.
     */
    AK_RUNTIME_GRPC_STOPPING = 2,
    /**
     * The gRPC side is done; the host may still hold memory.
     */
    AK_RUNTIME_GRPC_STOPPED = 3,
    /**
     * And nothing of it is outstanding either.
     */
    AK_RUNTIME_QUIESCENT = 4,
    /**
     * Quiescence impossible, destroy refused. Reported when the status itself cannot be read,
     * when the task driving the shutdown dies, and when that shutdown cannot get a thread of its
     * own: the three ways the step to QUIESCENT stops being reachable. A shutdown that is merely
     * slow stays GRPC_STOPPING.
     */
    AK_RUNTIME_FAILED_UNQUIESCED = 5,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum ak_runtime_state ak_runtime_state;
#else
typedef int32_t ak_runtime_state;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * How far along a channel's closing is. A handle this library no longer knows reads as NONE,
 * which is also what an unopened one reads as: neither names a channel.
 */
enum ak_channel_state
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    AK_CHANNEL_NONE = 0,
    /**
     * Takes calls.
     */
    AK_CHANNEL_OPEN = 1,
    /**
     * Released, its calls draining.
     */
    AK_CHANNEL_CLOSING = 2,
    /**
     * And nothing of it is active any more.
     */
    AK_CHANNEL_CLOSED = 3,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum ak_channel_state ak_channel_state;
#else
typedef int32_t ak_channel_state;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * Carried by AK_EVENT_INITIAL_METADATA in status_code: where the head came from. The event comes
 * first on every call, and its metadata is empty unless the peer's headers were delivered. Zero
 * is the peer's headers, so a host that ignores the field takes every head for the peer's.
 */
enum ak_head_origin
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    /**
     * The peer's response headers.
     */
    AK_HEAD_RECEIVED = 0,
    /**
     * A response came and delivered no head - the Trailers-Only shape, or an answer refused
     * before its body; the terminal is the call's status, the peer's unless the call was stopped
     * here first.
     */
    AK_HEAD_TRAILERS_ONLY = 1,
    /**
     * No response reached the call.
     */
    AK_HEAD_NO_RESPONSE = 2,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum ak_head_origin ak_head_origin;
#else
typedef int32_t ak_head_origin;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

typedef struct {
    uint32_t struct_size;
    /**
     * Zero leaves the choice to the runtime; at most AK_MAX_WORKER_THREADS.
     */
    uint32_t worker_threads;
    /**
     * Bytes lent buffers may occupy at once. Zero, or more than this library can lend, asks for
     * its own ceiling: four gigabytes, or half the address space where that is smaller - the gRPC
     * length prefix and the allocator between them admit no more, so a budget above it is one no
     * single lend could draw on.
     */
    uint64_t memory_ceiling;
} ak_runtime_config;

/**
 * Chosen by the host, returned in each callback for its call. Opaque: never dereferenced here.
 * Must stay valid until the call's terminal (AK_EVENT_STATUS).
 */
typedef void *ak_call_ctx;

/**
 * Owned by the host after reception, until ak_event_consumed.
 *
 * owner, not ptr, identifies the allocation: the view may be a slice of a larger one. owner ==
 * NULL means unowned, never "empty" - a zero-length payload that took a delivery credit carries a
 * real owner and MUST be consumed, because the credit comes back with the acquittal and not with
 * the bytes.
 */
typedef struct {
    const uint8_t *ptr;
    size_t len;
    void *owner;
} ak_bytes;

/**
 * On the callback's stack; no lifecycle of its own. The payload is owned when owner is not NULL.
 *
 * WRITE_DONE, SHUTDOWN_COMPLETE and RESOURCES_RELEASED carry no payload: ptr == NULL, len == 0,
 * owner == NULL. ak_event_consumed on such a payload is a no-op, so a host may route every event
 * through one path.
 */
typedef struct {
    ak_event_kind kind;
    ak_bytes payload;
    /**
     * gRPC status for AK_EVENT_STATUS, ak_head_origin for AK_EVENT_INITIAL_METADATA, zero on
     * every other event.
     */
    int32_t status_code;
    /**
     * AK_EVENT_SHUTDOWN_COMPLETE only.
     */
    ak_host_debt host_debt;
} ak_event;

/**
 * The function pointer must stay valid for the runtime's lifetime, and runtime_ctx until the
 * runtime's last event.
 *
 * Data callbacks (INITIAL_METADATA, MESSAGE, STATUS) are serialized per call and concurrent
 * between calls. WRITE_DONE may arrive in parallel with any of them, including for the same call:
 * a per-call lock in the handler would hold the slot release hostage behind a slow message
 * handler.
 *
 * A callback runs on one of this library's own worker threads, and every promise made here about
 * progress - a send reaching the wire, an acquittal, a call being reclaimed, a shutdown
 * completing - is made on those threads. So the callback must publish and return: record the
 * event where the host's own thread will find it, hand the payload on, and end. It must not
 * parse, allocate what it could have allocated earlier, take a lock the host's own code holds,
 * or run application code. A host that blocks here does not slow itself down; it stops the
 * library, and the guarantees above stop with it.
 */
typedef void (*ak_callback)(void *runtime_ctx, ak_call_ctx call_ctx, const ak_event *event);

typedef uint64_t ak_handle;

typedef struct {
    /**
     * Occupied against the ceiling, atomic snapshot.
     */
    uint64_t bytes_used;
    /**
     * The limit in force, which is what was configured or this library's own where that is
     * smaller. Never zero.
     */
    uint64_t ceiling;
} ak_memory_usage;

/**
 * Bytes the host lends this library for the duration of one downcall.
 */
typedef struct {
    const uint8_t *ptr;
    size_t len;
} ak_bytes_in;

typedef struct {
    uint32_t struct_size;
    /**
     * "/Service/Method", not NUL-terminated.
     */
    ak_bytes_in method;
    /**
     * A metadata blob - a uint32_t count, then each key and each value as a uint32_t length and
     * its bytes; may be empty.
     */
    ak_bytes_in metadata;
} ak_call_start_options;

/**
 * Lent by ak_get_call_buffer out of the call's arena. The host writes len bytes and gives it back
 * exactly once, by ak_call_send_message or ak_return_call_buffer. This library never reclaims a
 * lent buffer on its own - not on cancellation, not on channel close - which is what removes the
 * race between a writing thread and a cancelling one.
 */
typedef struct {
    uint8_t *ptr;
    size_t len;
    void *owner;
} ak_buffer;

typedef struct {
    /**
     * Delivered, not yet ak_event_consumed.
     */
    uint32_t payloads_owed;
    /**
     * Out of the arena, not yet given back.
     */
    uint32_t buffers_lent;
    /**
     * The runtime's own, informational.
     */
    uint32_t callbacks_in_flight;
    /**
     * 0 or 1.
     */
    int32_t terminal_delivered;
} ak_call_debt;

#define AK_HANDLE_NONE (ak_handle)0

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Creates a runtime. One exists at a time: a second create before the first is destroyed is
 * refused with AK_STATUS_INVALID_STATE.
 *
 * # Safety
 *
 * `config` and `out` must be valid for their types, and `callback` must stay callable with
 * `runtime_ctx` until the runtime's last event.
 */
ak_status ak_runtime_create(const ak_runtime_config *config,
                            ak_callback callback,
                            void *runtime_ctx,
                            ak_handle *out);

ak_runtime_state ak_runtime_status(ak_handle runtime);

/**
 * Closes the start gate and drains. AK_EVENT_SHUTDOWN_COMPLETE follows. Idempotent.
 */
ak_status ak_runtime_begin_shutdown(ak_handle runtime);

/**
 * Frees the runtime. Refused before AK_RUNTIME_QUIESCENT, and that is the only reason.
 *
 * Live call and channel handles do not block it: destroy stales every handle of this runtime at
 * once, and a later downcall on one returns AK_STATUS_HANDLE_STALE. A handle names runtime-owned
 * state, so the runtime may reclaim it; a payload or a lent buffer is memory the host may still
 * be reading or writing, so only the host can end it.
 */
ak_status ak_runtime_destroy(ak_handle runtime);

/**
 * # Safety
 *
 * `out` must be writable.
 */
ak_status ak_runtime_memory_usage(ak_handle runtime, ak_memory_usage *out);

/**
 * Creates a channel on an endpoint, configured by a JSON document. Synchronous and performs no
 * I/O: no name is resolved and no socket opened until the channel's first call. A bad endpoint or
 * a bad document is AK_STATUS_INVALID_ARG, and so is a null out or a null slice with a non-zero
 * length; a runtime handle that names nothing is AK_STATUS_HANDLE_STALE, and one that is shutting
 * down is AK_STATUS_INVALID_STATE.
 *
 * The endpoint is its own argument, as UTF-8 - "http://host:port". It is the one value a channel
 * cannot be created without, so it is not an option that happens to be mandatory: every option of
 * the document has a default, and `{}` is a valid configuration.
 *
 * The document is structured and typed, and a JSON schema states it: objects nest, a number is a
 * number and not a string spelled like one, and an option spelled wrong is refused rather than
 * ignored. It carries UserAgent, MaxReceiveMessageSize, DeliveryCredits, MaxSendsInFlight, and
 * a Transport object holding ConnectTimeoutSeconds.
 *
 * The two windows mirror each other. DeliveryCredits bounds the payloads of one call outstanding
 * at once - the terminal status takes no credit, so a host holds at most one more - and the host
 * chooses it because the host is what has to hold them; MaxSendsInFlight bounds the buffers one
 * call may have out, counting those being filled and those awaiting their WRITE_DONE. Both
 * default to 1, and the schema states the range either may take.
 *
 * A call whose payloads the host does not consume reads a few messages past its spent credits,
 * which the engine holds outside what the credits count, and then stops reading its stream; what
 * its peer sends meanwhile holds the connection's HTTP/2 window. Every call of the channel shares
 * that window, so enough unread calls stop the others receiving.
 *
 * # Safety
 *
 * `config_json` must point at its bytes for the duration of the call, and `out` must be
 * writable.
 */
ak_status ak_channel_create(ak_handle runtime,
                            ak_bytes_in endpoint,
                            ak_bytes_in config_json,
                            ak_handle *out);

/**
 * Frees the channel, cancelling its calls first.
 *
 * The cancellation is not a courtesy: the channel is closing from this moment and no closing
 * channel may have an active call, so the latch is what makes the drain this library's business
 * rather than something the host must provoke. A call parked on a delivery credit is the case
 * that needs it - it is not watching the transport, so closing the session alone would never
 * reach it.
 *
 * Idempotent. The channel goes to AK_CHANNEL_CLOSING, and once its last call has reached its
 * terminal the handle is reclaimed: from then on ak_channel_status answers AK_CHANNEL_NONE and
 * ak_call_start AK_STATUS_HANDLE_STALE. Until then the channel starts no further call -
 * ak_call_start on it answers AK_STATUS_INVALID_STATE - and a host following the drain reads
 * CLOSING and then NONE, with CLOSED at most in passing. An idle channel is reclaimed before this
 * returns.
 *
 * A channel the runtime's shutdown closed is not reclaimed: it stays AK_CHANNEL_CLOSED, and
 * nameable, until this is called or the runtime is destroyed.
 */
void ak_channel_release(ak_handle channel);

/**
 * How far along a channel's closing is. Answers NONE for a handle this library does not know,
 * which a released channel is once its last call has ended.
 *
 * What ends CLOSING is this library's own bookkeeping - the last call of the channel reaching
 * its terminal - so a host watching the drain has nothing to do but read. In particular CLOSED
 * does not wait for the host to consume what it has been given: a call past its terminal still
 * owes its payloads, and the channel is closed regardless.
 */
ak_channel_state ak_channel_status(ak_handle channel);

/**
 * Starts a call on a channel.
 *
 * There is no ak_call_release, on purpose. Every resource a call lends out is given back through
 * something the runtime already observes, so it knows when a terminal call owes nothing and takes
 * the handle back itself. Two consequences: the handle goes stale at a moment the host does not
 * choose, and abandoning a call is still ak_call_cancel followed by consuming through to the
 * terminal - dropping a payload on the floor keeps the runtime alive.
 *
 * # Safety
 *
 * `options` must be valid for its type and its byte views, and `out` must be writable.
 */
ak_status ak_call_start(ak_handle channel,
                        const ak_call_start_options *options,
                        ak_call_ctx call_ctx,
                        ak_handle *out);

/**
 * Lends a buffer out of the call's arena to serialize into. The exact length is known before the
 * first byte is written, so no growable writer is needed.
 *
 * One unfilled buffer at a time, whatever max_sends_in_flight says: asking for a second while
 * still holding one is AK_STATUS_INVALID_STATE, a host bug rather than backpressure. The window
 * counts those being filled and those committed and awaiting their WRITE_DONE; when it is full
 * the refusal is AK_STATUS_SLOT_BUSY, whose wake-up is this call's next WRITE_DONE. That wake-up
 * is only meaningful because a host eligible to ask holds nothing. AK_STATUS_BUDGET_BUSY is the
 * runtime-wide ceiling, and has no single event announcing room: poll ak_runtime_memory_usage.
 * AK_STATUS_MESSAGE_TOO_LARGE is permanent. On every refusal no buffer is lent and `*out` is
 * untouched.
 *
 * # Safety
 *
 * `out` must be writable.
 */
ak_status ak_get_call_buffer(ak_handle call, size_t len, ak_buffer *out);

/**
 * Commits a lent buffer as the next message. Ownership passes back to this library.
 *
 * AK_EVENT_WRITE_DONE settles an accepted send and frees its slot from the moment the event is
 * emitted, not when the callback returns - so a host woken by it may ask for a buffer from inside
 * the callback. It says nothing about the network: the message may have been written, or
 * abandoned because the call was cancelled. It arrives exactly once per accepted send, in send
 * order, and always before the terminal.
 *
 * # Safety
 *
 * `buffer` must be one this call lent and the host has not given back.
 */
ak_status ak_call_send_message(ak_handle call, ak_buffer buffer);

/**
 * Gives a lent buffer back unused. Legal on a cancelled or terminal call: it is the only exit for
 * a buffer whose send is refused, and the call is not reclaimed until it happens.
 *
 * Takes no call handle: the buffer determines its call. A refused ak_call_send_message therefore
 * leaves the buffer with the host, exactly as it was lent.
 *
 * # Safety
 *
 * `buffer` must be one this call lent and the host has not given back.
 */
void ak_return_call_buffer(ak_buffer buffer);

/**
 * Signals end of sending. No ak_call_send_message after this: a send that comes after the end,
 * and a second end, answer AK_STATUS_INVALID_STATE.
 *
 * An end that comes while an ak_call_send_message has not yet returned on another thread - from
 * inside that send's own AK_EVENT_WRITE_DONE, which may arrive first - waits for it to return, so
 * it never goes ahead of a message the host has been told left.
 */
ak_status ak_call_end_send(ak_handle call);

/**
 * Cancels the call, which then reaches a terminal - carrying CANCELLED, unless the peer's own
 * status was already in.
 *
 * Asynchronous: the request takes effect when the call's task observes it, so callbacks already
 * committed may still arrive after this returns, and a status the peer had already sent is the
 * one delivered. INITIAL_METADATA is never skipped.
 */
ak_status ak_call_cancel(ak_handle call);

/**
 * What the call still owes. Purely observational; it is legal never to call it. It exists because
 * without a release downcall nothing reports a forgotten ak_return_call_buffer synchronously.
 *
 * # Safety
 *
 * `out` must be writable.
 */
ak_status ak_call_debt_of(ak_handle call, ak_call_debt *out);

int32_t ak_abi_version(void);

/**
 * Signals that the host has consumed an event's payload. Two things at once:
 *
 * 1. frees the native memory;
 * 2. arms reception of the next event for that call.
 *
 * At most one non-consumed payload per call by default: while the host owes it, the runtime
 * withholds the next data callback. Only a terminal still goes out with the credit spent.
 *
 * Remains legal, and required, after the terminal: the call is not reclaimed until it happens.
 *
 * # Safety
 *
 * `payload` must be one this library delivered and the host has not consumed.
 */
void ak_event_consumed(ak_bytes payload);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* ARMONIK_TRANSPORT_FFI_H */
