// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace ArmoniK.Api.Client.Native
{
    public static unsafe partial class NativeMethods
    {
        const string __DllName = "armonik_transport_ffi";

        /// <summary>
        ///  The revision of this ABI that this library implements.
        ///
        ///  A caller compiles this value in and compares it against what `ak_abi_version` answers.
        /// </summary>
        public const int AK_ABI_VERSION = 1;


        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void ak_request_start_on_event_delegate(void* ctx, int kind, ak_bytes_in payload, int code);



        /// <summary>
        ///  The revision of this ABI that the loaded library implements.
        ///
        ///  Queryable rather than only compiled in, because a host process loads one native module and every
        ///  add-in in it shares whichever was loaded first: an add-in that did not bring its own has to be
        ///  able to find out what it got. Asking turns a mismatch into a diagnosis, where reaching for an
        ///  entry point that is not there surfaces as an `EntryPointNotFoundException` from somewhere
        ///  unrelated.
        ///
        ///  Compare against `AK_ABI_VERSION`, the value this library was compiled with.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ak_abi_version", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int ak_abi_version();

        /// <summary>
        ///  Create a client from a UTF-8 JSON configuration document.
        ///
        ///  `config_json` names the flat options of the transport's vocabulary - `Endpoint`, `CaCertPath`,
        ///  `AllowUnsafeConnection`, `Tcp*`, `Http2*`, `Proxy*`, and the rest - as a single JSON object of
        ///  strings. `include/http_config.schema.json` is that vocabulary in full; an option the document
        ///  does not name reads as its own default, so a caller writes only what it changes.
        ///
        ///  Synchronous, and it opens no connection: this reads the options, loads whatever certificates they
        ///  name, and assembles the connector. A failure here is therefore a configuration failure, reported
        ///  straight away with its whole cause chain flattened into `out_err`.
        ///
        ///  Safety:
        ///
        ///  `config_json` must point to `len` readable bytes. `out` must be a writable `ak_client*`, and
        ///  receives a handle to be given up by exactly one `ak_client_release`. `out_err`, when non-null,
        ///  must be a writable `ak_bytes` and receives a message to give up with
        ///  `ak_bytes_release`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ak_client_create", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int ak_client_create(byte* config_json, System.UIntPtr len, ak_client** @out, ak_bytes* out_err);

        /// <summary>
        ///  Give up the caller's reference to a client.
        ///
        ///  Requests already under way keep the pool alive and run to completion: this gives back one
        ///  reference, not necessarily the last one. Null is accepted and does nothing.
        ///
        ///  Safety:
        ///
        ///  `client` must be a handle from `ak_client_create` that has not been released, or null.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ak_client_release", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void ak_client_release(ak_client* client);

        /// <summary>
        ///  Give up an `ak_bytes` previously returned by this library.
        ///
        ///  Safety:
        ///
        ///  `bytes` must be a value this library returned, not yet released. Passing a borrowed input buffer, a
        ///  value already released, or a value with an `owner` this library did not produce, is undefined
        ///  behaviour. The zeroed value is always safe to pass here.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ak_bytes_release", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void ak_bytes_release(ak_bytes bytes);

        /// <summary>
        ///  Open a request on `client` and start driving it.
        ///
        ///  `headers_blob` is a key/value blob. Two pseudo-keys are required and are not sent as headers:
        ///
        ///  - `:method` - the HTTP method, for instance `POST`.
        ///  - `:url` - the absolute request URL, scheme and authority included. The connection pool keys on
        ///    it, so a path-only form is refused.
        ///
        ///  Every other key is sent as a request header, in the order given, duplicates included. A `-bin`
        ///  value passes through untouched: base64 is the caller's convention, not this library's.
        ///
        ///  On `AK_OK` a completion event is guaranteed to follow, exactly once, and `ctx` may be given up
        ///  when it arrives. On any other status no event ever arrives.
        ///
        ///  Safety:
        ///
        ///  `client` must be a live handle from `ak_client_create`. `headers_blob` must point to
        ///  `len` readable bytes for the duration of the call. `on_event` must remain callable, and `ctx`
        ///  valid, until the completion event; releasing the handle does not end that, because events go on
        ///  being delivered until the completion whatever the caller does with its reference. `out` must be
        ///  a writable `ak_request*`, and receives a handle to be given up by exactly one
        ///  `ak_request_release`. `out_err`, when non-null, must be a writable `ak_bytes` and receives a
        ///  message to give up with `ak_bytes_release`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ak_request_start", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int ak_request_start(ak_client* client, byte* headers_blob, System.UIntPtr len, ak_request_start_on_event_delegate on_event, void* ctx, ak_request** @out, ak_bytes* out_err);

        /// <summary>
        ///  End the request body.
        ///
        ///  Refused with `AK_INVALID_STATE` if the body has already been ended.
        ///
        ///  Safety:
        ///
        ///  `request` must be a live handle from `ak_request_start`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ak_request_close_send", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int ak_request_close_send(ak_request* request);

        /// <summary>
        ///  Arm one read.
        ///
        ///  Exactly one event follows: a read event with a chunk of the response body, or the completion.
        ///  Arming a second read while one is outstanding is refused with `AK_INVALID_STATE`.
        ///
        ///  Safety:
        ///
        ///  `request` must be a live handle from `ak_request_start`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ak_request_read", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int ak_request_read(ak_request* request);

        /// <summary>
        ///  Give up the caller's reference to a request.
        ///
        ///  Releasing before the completion is how a caller abandons a request it no longer wants. The
        ///  driving task runs to its terminal state either way, and the completion still arrives: there is no
        ///  second ownership rule for that path. Whatever was rooted for `ctx` is given back at the
        ///  completion, on every path, and this is not that moment.
        ///
        ///  Null is accepted and does nothing.
        ///
        ///  Safety:
        ///
        ///  `request` must be a handle from `ak_request_start` that has not been released, or null.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ak_request_release", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void ak_request_release(ak_request* request);


    }

    /// <summary>
    ///  A connection pool, and the options a request on it draws from.
    ///
    ///  Handed to the caller as an opaque pointer. The registry owns it, and a request takes a counted
    ///  reference for as long as it runs, so a pool outlives an `ak_client_release` that lands while
    ///  work is still on it.
    ///
    ///  `timeout` and `rate_limit` are parsed and held, and nothing acts on them, which changes no
    ///  behaviour on its own. `tests/schema.rs` says as much, and lists them among the options this
    ///  library does not apply.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct ak_client
    {
    }

    /// <summary>
    ///  An owned buffer handed to the caller.
    ///
    ///  `ptr`/`len` are a read-only *view*; the allocation itself belongs to `owner`, an opaque handle
    ///  the caller passes back unchanged and never otherwise touches. Keeping the two apart - rather than
    ///  treating `ptr` as the thing to release - is what lets a buffer this library already holds cross
    ///  without being copied: `owner` names whatever really owns those bytes, which may be a
    ///  reference-counted view into a larger allocation, so `ptr` on its own is not something that can be
    ///  released.
    ///
    ///  Every buffer with a non-null `owner` must be given up by exactly one call to
    ///  `ak_bytes_release`. The zeroed value (`ptr` and `owner` null, `len` 0) means "no data" and is
    ///  always safe to pass there.
    ///
    ///  Input buffers travel as `ak_bytes_in` instead: those are borrowed from the caller and are never
    ///  released by this library. Only a value this library produced is ever released here.
    ///
    ///  Copying the `(ptr, len, owner)` triple is harmless, which is why this is a plain value. What must
    ///  never happen, on either side, is passing more than one copy of the same original value to
    ///  `ak_bytes_release`.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct ak_bytes
    {
        /// <summary>
        ///  Pointer to the first byte, or null for an empty or absent buffer. Readable until this value
        ///  is passed to `ak_bytes_release`; never write through it.
        /// </summary>
        public byte* ptr;
        /// <summary>
        ///  Number of bytes at `ptr`.
        /// </summary>
        public System.UIntPtr len;
        /// <summary>
        ///  Opaque; pass back to `ak_bytes_release` unchanged, never dereference or otherwise inspect
        ///  it.
        /// </summary>
        public void* owner;
    }

    /// <summary>
    ///  A borrowed input buffer: a view into memory the *caller* owns.
    ///
    ///  Also what an event payload travels as, in the other direction: borrowed for the duration of the
    ///  invocation and invalid the moment it returns. Never released by whoever received it. A null `ptr`
    ///  or a zero `len` means "empty" or "absent".
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct ak_bytes_in
    {
        /// <summary>
        ///  Pointer to the first byte, or null for an empty or absent buffer.
        /// </summary>
        public byte* ptr;
        /// <summary>
        ///  Number of bytes at `ptr`.
        /// </summary>
        public System.UIntPtr len;
    }

    /// <summary>
    ///  A request handle.
    ///
    ///  The task owns everything that matters; this is the caller's end of the command channel plus the
    ///  flags that say what is currently armed.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct ak_request
    {
    }


    /// <summary>
    ///  What a request is reporting.
    ///
    ///  Zero is not one of them, so a zeroed `kind` is never a valid event. A caller ignores a kind it
    ///  does not know: the ABI is additive, and a library newer than its caller may report events that
    ///  caller has never heard of.
    /// </summary>
    public enum ak_event : int
    {
        /// <summary>
        ///  The response headers arrived. The payload is a key/value blob, with the HTTP status in it
        ///  under the `:status` key as decimal ASCII, and the code is `AK_OK`.
        ///
        ///  At most once per request, and before any other event that carries response data.
        /// </summary>
        AK_EVENT_RESPONSE_HEADERS = 1,
        /// <summary>
        ///  The read armed by `ak_request_read` produced body bytes. The payload is the chunk, borrowed
        ///  for the duration of the call, and the code is `AK_OK`.
        ///
        ///  A chunk is whatever the connection delivered, not a message: there is no framing at this
        ///  level, so a reader copes with any split.
        /// </summary>
        AK_EVENT_READ_DONE = 2,
        /// <summary>
        ///  The request is over, and no further callback is made for it.
        ///
        ///  The code is `AK_OK` when the response ended cleanly, and the payload is then the trailers as
        ///  a key/value blob - possibly empty, which is what a clean end of stream without trailers looks
        ///  like. Otherwise the code is one of the failures and the payload is that failure as a UTF-8
        ///  message, with its whole cause chain flattened into it.
        /// </summary>
        AK_EVENT_COMPLETED = 3,
    }

    /// <summary>
    ///  The result of a call: `AK_OK` on success, and a negative code otherwise.
    /// </summary>
    public enum ak_status : int
    {
        /// <summary>
        ///  The operation succeeded.
        /// </summary>
        AK_OK = 0,
        /// <summary>
        ///  A pointer argument that must not be null was null.
        /// </summary>
        AK_NULL_ARGUMENT = -1,
        /// <summary>
        ///  A byte buffer was not valid UTF-8 where UTF-8 was required.
        /// </summary>
        AK_INVALID_UTF8 = -2,
        /// <summary>
        ///  The client configuration was rejected; the message says what in it.
        /// </summary>
        AK_INVALID_CONFIG = -3,
        /// <summary>
        ///  The request never reached the server: no connection at all, or a connection that failed
        ///  before any response header arrived.
        /// </summary>
        AK_CONNECTION_FAILED = -4,
        /// <summary>
        ///  The handle passed to a call has already been released, or was never valid.
        /// </summary>
        AK_INVALID_HANDLE = -5,
        /// <summary>
        ///  The object is not in a state that allows the operation.
        /// </summary>
        AK_INVALID_STATE = -6,
        /// <summary>
        ///  Something inside this library failed in a way that is not the caller's doing; see the message.
        /// </summary>
        AK_INTERNAL = -8,
        /// <summary>
        ///  A panic was caught at the boundary. This is always a bug in this library; the message carries
        ///  whatever the panic payload could be turned into.
        /// </summary>
        AK_INTERNAL_PANIC = -9,
        /// <summary>
        ///  The request was cancelled.
        /// </summary>
        AK_CANCELLED = -10,
        /// <summary>
        ///  The configured timeout elapsed while the request was still in flight.
        /// </summary>
        AK_TIMEOUT = -11,
        /// <summary>
        ///  The connection failed after the response headers had arrived: a reset stream, a broken
        ///  connection, a protocol error.
        /// </summary>
        AK_TRANSPORT = -12,
    }


}
