// This file is part of the ArmoniK project
//
// Copyright (C) ANEO, 2021-2026. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License")
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;

namespace ArmoniK.Api.Client.RustGrpcChannel.OptionsGenerator
{
  /// <summary>The option vocabulary as the C# a caller fills in.</summary>
  internal static class CSharpSource
  {
    private const string Indent = "  ";

    // The repository's own header, which every file it tracks carries. Emitted because this file
    // is tracked like any other, and because a tool asked to add one would edit a file that then
    // stops being what the schema renders - which the build refuses.
    private const string Licence = @"// This file is part of the ArmoniK project
//
// Copyright (C) ANEO, 2021-2026. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the ""License"")
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an ""AS IS"" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
";

    /// <summary>Renders <paramref name="groups" /> as one compilation unit.</summary>
    /// <param name="groups">The vocabulary, its root group first.</param>
    /// <param name="namespaceName">The namespace the classes are declared in.</param>
    /// <param name="schemaName">The schema file, named in the header so a reader can find it.</param>
    /// <returns>The file's whole text, ending with one newline.</returns>
    /// <exception cref="NotSupportedException">A name or a bound has no C# this can emit.</exception>
    public static string Render(IReadOnlyList<OptionGroup> groups,
                                string namespaceName,
                                string schemaName)
    {
      // Ahead of any rendering: a name reaches an identifier, a `nameof`, and two string
      // literals, and one that is not a C# name would be spliced into all four.
      var context = groups[0]
                      .Name
                    + "JsonContext";

      foreach (var group in groups)
      {
        RefuseAName(group.Name,
                    "a schema");

        // The serializer context is declared beside the classes and named after the root, so a
        // group of that name would be two types of one name in a file nobody wrote.
        if (group.Name == context)
        {
          throw new NotSupportedException($"`{group.Name}` names a schema, and it is also the serializer context this renders for `{groups[0].Name}`.");
        }

        foreach (var option in group.Options)
        {
          RefuseAName(option.Name,
                      $"an option of `{group.Name}`");

          // C# refuses a member named after the type that declares it, and the message it gives
          // names a file nobody wrote.
          if (option.Name == group.Name)
          {
            throw new NotSupportedException($"`{option.Name}` is an option of the group of the same name, and C# admits no member named after its own class.");
          }
        }
      }

      var source = new StringBuilder();

      // The marker leads, and the licence follows it. A tool recognises generated code by finding
      // `<auto-generated>` in the file's first comment, so a licence header above it would hide
      // the file's own nature; below it, the header is still a header.
      source.Append("// <auto-generated>\n")
            .Append("//     Generated from ")
            .Append(schemaName)
            .Append(" by ArmoniK.Api.Client.RustGrpcChannel.OptionsGenerator.\n")
            .Append("//     Edits here are lost. Change the Rust option types, render the schema again,\n")
            .Append("//     and build: the schema is what this file is.\n")
            .Append("// </auto-generated>\n")
            .Append('\n')
            .Append(Licence.Replace("\r\n",
                                    "\n"))
            .Append('\n')
            .Append("#nullable enable\n")
            .Append('\n')
            .Append("using System;\n")
            .Append("using System.Text.Json;\n")
            .Append("using System.Text.Json.Serialization;\n")
            .Append('\n')
            .Append("namespace ")
            .Append(namespaceName)
            .Append(";\n");

      // Rooted at the first group, which reaches every other: the context is what serializes
      // without reflection, which is what lets a trimmed or native-AOT host send a document.
      source.Append('\n')
            .Append("// Rooted at ")
            .Append(groups[0]
                      .Name)
            .Append(", which reaches every group of the vocabulary, so the whole graph is\n")
            .Append("// serialized without reflection - which is what lets a trimmed or native-AOT host use this.\n")
            .Append("[JsonSerializable(typeof(")
            .Append(groups[0]
                      .Name)
            .Append("))]\n")
            .Append("internal partial class ")
            .Append(groups[0]
                      .Name)
            .Append("JsonContext : JsonSerializerContext\n{\n}\n");

      foreach (var group in groups)
      {
        source.Append('\n');
        Append(source,
               group,
               ReferenceEquals(group,
                               groups[0]));
      }

      return source.ToString();
    }

    private static void Append(StringBuilder source,
                               OptionGroup group,
                               bool isRoot)
    {
      Document(source,
               group.Description,
               string.Empty);

      // Public, because this is what a caller fills in. Not partial: the whole surface is
      // rendered here - the properties, the bounds, the copy, the serializer context and the
      // encoding - so a second part would be something the schema does not decide, and the place
      // for that is this generator.
      source.Append("public sealed class ")
            .Append(group.Name)
            .Append("\n{\n");

      AppendConstructors(source,
                         group);

      var first = true;

      foreach (var option in group.Options)
      {
        if (!first)
        {
          source.Append('\n');
        }

        first = false;

        Document(source,
                 option.Description,
                 Indent);

        // The name is spelled rather than left to the serializer's policy: this document is a
        // contract with the engine, which refuses an option it does not know rather than
        // ignoring it, and a policy set elsewhere would be enough to break it.
        source.Append(Indent)
              .Append("[JsonPropertyName(\"")
              .Append(option.Name)
              .Append("\")]\n")
              .Append(Indent)
              .Append("[JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]\n")
              .Append(Indent)
              .Append("public ")
              .Append(option.Type)
              .Append("? ")
              .Append(option.Name)
              .Append(" { get; set; }\n");
      }

      AppendValidate(source,
                     group);

      if (isRoot)
      {
        AppendEncode(source,
                     group);
      }

      source.Append("}\n");
    }

    // Only the root group: the document the engine reads is one object, and a group of it is not
    // a document. `Validate` runs first, because the engine answers a bad one with a status that
    // names neither the option nor the bound.
    private static void AppendEncode(StringBuilder source,
                                     OptionGroup group)
    {
      source.Append('\n')
            .Append(Indent)
            .Append("/// <summary>The document the engine reads, as UTF-8.</summary>\n")
            .Append(Indent)
            .Append("/// <returns>The options as JSON, without the ones left unset.</returns>\n")
            .Append(Indent)
            .Append("/// <exception cref=\"ArgumentOutOfRangeException\">An option is outside its bounds.</exception>\n")
            .Append(Indent)
            .Append("/// <remarks>\n")
            .Append(Indent)
            .Append("///   Checked before it is written, not after it is refused: the engine answers a bad\n")
            .Append(Indent)
            .Append("///   document with a status naming neither the option nor the bound.\n")
            .Append(Indent)
            .Append("/// </remarks>\n")
            .Append(Indent)
            .Append("internal byte[] Encode()\n")
            .Append(Indent)
            .Append("{\n")
            .Append(Indent)
            .Append(Indent)
            .Append("Validate();\n")
            .Append('\n')
            .Append(Indent)
            .Append(Indent)
            .Append("return JsonSerializer.SerializeToUtf8Bytes(this,\n")
            .Append(Indent)
            .Append(Indent)
            .Append("                                           ")
            .Append(group.Name)
            .Append("JsonContext.Default.")
            .Append(group.Name)
            .Append(");\n")
            .Append(Indent)
            .Append("}\n");
    }

    // A caller's instance is theirs, and what a channel reads has to stay what it read: a value
    // taken twice from a settable property is two values if anything sets it in between. So a
    // holder takes a copy, and the copy is deep - a group left shared would be the same hole one
    // level down.
    private static void AppendConstructors(StringBuilder source,
                                           OptionGroup group)
    {
      source.Append(Indent)
            .Append("/// <summary>Options nobody has set.</summary>\n")
            .Append(Indent)
            .Append("public ")
            .Append(group.Name)
            .Append("()\n")
            .Append(Indent)
            .Append("{\n")
            .Append(Indent)
            .Append("}\n")
            .Append('\n')
            .Append(Indent)
            .Append("/// <summary>A copy of <paramref name=\"other\" />, sharing nothing with it.</summary>\n")
            .Append(Indent)
            .Append("/// <param name=\"other\">The options to copy.</param>\n")
            .Append(Indent)
            .Append("/// <exception cref=\"ArgumentNullException\"><paramref name=\"other\" /> is null.</exception>\n")
            .Append(Indent)
            .Append("public ")
            .Append(group.Name)
            .Append("(")
            .Append(group.Name)
            .Append(" other)\n")
            .Append(Indent)
            .Append("{\n")
            .Append(Indent)
            .Append(Indent)
            .Append("if (other is null)\n")
            .Append(Indent)
            .Append(Indent)
            .Append("{\n")
            .Append(Indent)
            .Append(Indent)
            .Append(Indent)
            .Append("throw new ArgumentNullException(nameof(other));\n")
            .Append(Indent)
            .Append(Indent)
            .Append("}\n");

      if (group.Options.Count > 0)
      {
        source.Append('\n');
      }

      foreach (var option in group.Options)
      {
        source.Append(Indent)
              .Append(Indent)
              .Append(option.Name)
              .Append(" = ");

        if (option.IsGroup)
        {
          source.Append("other.")
                .Append(option.Name)
                .Append(" is null\n")
                .Append(Indent)
                .Append(Indent)
                .Append(Indent)
                .Append(new string(' ', option.Name.Length + 3))
                .Append("? null\n")
                .Append(Indent)
                .Append(Indent)
                .Append(Indent)
                .Append(new string(' ', option.Name.Length + 3))
                .Append(": new ")
                .Append(option.Type)
                .Append("(other.")
                .Append(option.Name)
                .Append(");\n");
          continue;
        }

        source.Append("other.")
              .Append(option.Name)
              .Append(";\n");
      }

      source.Append(Indent)
            .Append("}\n\n");
    }

    // Every bound the schema states, checked here. The schema cannot say all of it in the type -
    // an `int` admits zero and the schema does not - so what the type lets through, this refuses.
    private static void AppendValidate(StringBuilder source,
                                       OptionGroup group)
    {
      var refused = group.Options.Where(option => option.Bounds.Count > 0 || option.IsGroup || option.Type == "double")
                         .ToList();

      source.Append('\n')
            .Append(Indent)
            .Append("/// <summary>Refuses a value the schema excludes.</summary>\n")
            .Append(Indent)
            .Append("/// <exception cref=\"ArgumentOutOfRangeException\">An option is outside its stated bounds.</exception>\n")
            .Append(Indent)
            .Append("public void Validate()\n")
            .Append(Indent)
            .Append("{\n");

      if (refused.Count == 0)
      {
        source.Append(Indent)
              .Append(Indent)
              .Append("// The schema bounds nothing here.\n");
      }

      // One check per option rather than one per keyword: two `is` patterns in a block would
      // declare the same local twice, and a caller who set a window to zero wants the range it
      // had to be in, not the first half of it.
      foreach (var option in refused.Where(option => !option.IsGroup))
      {
        var value = Local(option.Name);

        var refuses = new List<string>();
        var says = new List<string>();

        foreach (var bound in option.Bounds)
        {
          var (refusal, said) = Check(bound,
                                      value,
                                      option.Type);
          refuses.Add(refusal);
          says.Add(said);
        }

        // A JSON number is finite and a `double` is not. NaN passes every bound - each comparison
        // against it is false - and System.Text.Json refuses to write any of the three, so a
        // caller who set one would get its exception rather than one naming the option.
        if (option.Type == "double")
        {
          refuses.Add($"double.IsNaN({value})");
          refuses.Add($"double.IsInfinity({value})");
          says.Add("finite");
        }

        var condition = string.Join(" || ",
                                    refuses);

        source.Append(Indent)
              .Append(Indent)
              .Append("if (")
              .Append(option.Name)
              .Append(" is ")
              .Append(option.Type)
              .Append(' ')
              .Append(value)
              .Append(" && ")
              .Append(refuses.Count > 1
                        ? "(" + condition + ")"
                        : condition)
              .Append(")\n")
              .Append(Indent)
              .Append(Indent)
              .Append("{\n")
              .Append(Indent)
              .Append(Indent)
              .Append(Indent)
              .Append("throw new ArgumentOutOfRangeException(nameof(")
              .Append(option.Name)
              .Append("),\n")
              .Append(Indent)
              .Append(Indent)
              .Append(Indent)
              .Append("                                      ")
              .Append(value)
              .Append(",\n")
              .Append(Indent)
              .Append(Indent)
              .Append(Indent)
              .Append("                                      \"")
              .Append(option.Name)
              .Append(" has to be ")
              .Append(string.Join(" and ",
                                  says))
              .Append(".\");\n")
              .Append(Indent)
              .Append(Indent)
              .Append("}\n\n");
      }

      TrimBlankLine(source);

      var groups = refused.Where(option => option.IsGroup)
                          .ToList();

      if (groups.Count > 0 && refused.Count > groups.Count)
      {
        source.Append('\n');
      }

      // A group's own bounds are its own to state, and it says so where it is declared.
      foreach (var option in groups)
      {
        source.Append(Indent)
              .Append(Indent)
              .Append(option.Name)
              .Append("?.Validate();\n");
      }

      source.Append(Indent)
            .Append("}\n");
    }

    // A description is one paragraph of what the option is, and any others of what a caller has to
    // know about it - which is the same split `<summary>` and `<remarks>` make.
    private static void Document(StringBuilder source,
                                 string description,
                                 string indent)
    {
      // At least one paragraph, because `OptionVocabulary` refuses a description that is absent
      // or blank - so there is no case here where an option or a group gets no documentation.
      var paragraphs = Lines(description)
                       .Split(new[]
                              {
                                "\n\n",
                              },
                              StringSplitOptions.None)
                       .Select(paragraph => paragraph.Trim())
                       .Where(paragraph => paragraph.Length > 0)
                       .ToList();

      Append(source,
             indent,
             "summary",
             paragraphs[0]);

      var rest = paragraphs.Skip(1)
                           .ToList();

      if (rest.Count > 0)
      {
        Append(source,
               indent,
               "remarks",
               string.Join("\n",
                           rest));
      }
    }

    // Every line ending becomes a newline: what C# ends a line on, not what a reader would call
    // one. A terminator left inside a description puts the rest of it outside the `///` and into
    // the code, and the three Unicode ones arrive by a paste as easily as by anything else.
    //
    // `\r\n` first: normalising `\r` alone would turn `\r\r\n` into a `\r\n` that reaches the
    // file, which `--check` normalises on the committed side only and so could never match again.
    private static string Lines(string text)
      => text.Replace("\r\n",
                      "\n")
             .Replace("\r",
                      "\n")
             // C# ends a line on these three as well, and no Replace of a visible character can
             // stand for them: written as escapes so this file stays ASCII.
             .Replace("\u0085",
                      "\n")
             .Replace("\u2028",
                      "\n")
             .Replace("\u2029",
                      "\n");

    private static void Append(StringBuilder source,
                               string indent,
                               string element,
                               string text)
    {
      var lines = Xml(text)
                  .Split('\n')
                  .Select(line => line.TrimEnd())
                  .ToList();

      if (lines.Count == 1)
      {
        source.Append(indent)
              .Append("/// <")
              .Append(element)
              .Append('>')
              .Append(lines[0])
              .Append("</")
              .Append(element)
              .Append(">\n");
        return;
      }

      source.Append(indent)
            .Append("/// <")
            .Append(element)
            .Append(">\n");

      foreach (var line in lines)
      {
        // Nothing after the `///` on an empty line: .editorconfig trims trailing whitespace, so
        // an editor that honours it would rewrite a file that has to stay what is rendered.
        source.Append(indent)
              .Append(line.Length == 0
                        ? "///"
                        : "///   " + line)
              .Append('\n');
      }

      source.Append(indent)
            .Append("/// </")
            .Append(element)
            .Append(">\n");
    }

    // The text is prose written in Rust doc comments, where a backtick is code and the three XML
    // characters are themselves.
    private static string Xml(string text)
    {
      var escaped = text.Replace("&",
                                 "&amp;")
                        .Replace("<",
                                 "&lt;")
                        .Replace(">",
                                 "&gt;");

      var rendered = new StringBuilder(escaped.Length);
      var open = true;

      foreach (var character in escaped)
      {
        if (character != '`')
        {
          rendered.Append(character);
          continue;
        }

        rendered.Append(open
                          ? "<c>"
                          : "</c>");
        open = !open;
      }

      // An odd number of backticks would leave a tag open, and prose the compiler refuses to read
      // is worse than prose with a backtick in it.
      return open
               ? rendered.ToString()
               : escaped;
    }

    // What a keyword becomes: the condition that refuses a value it excludes, and the same thing
    // in words for the message.
    //
    // The type decides as much as the keyword does. Draft 2020-12 lets a schema state a keyword
    // that does not apply to its instance type - `minLength` asserts nothing about a number - and
    // emitting it anyway would be `.Length` on an `int`. So a keyword the type has no check for
    // stops the generator rather than the compiler.
    private static (string Refuses, string Says) Check(Bound bound,
                                                       string value,
                                                       string type)
    {
      var numeric = type is "int" or "long" or "double";
      var text = type is "string";

      return bound.Keyword switch
             {
               "minimum" when numeric            => ($"{value} < {bound.Literal}", $"at least {bound.Literal}"),
               "maximum" when numeric            => ($"{value} > {bound.Literal}", $"at most {bound.Literal}"),
               "exclusiveMinimum" when numeric   => ($"{value} <= {bound.Literal}", $"greater than {bound.Literal}"),
               "exclusiveMaximum" when numeric   => ($"{value} >= {bound.Literal}", $"less than {bound.Literal}"),
               "minLength" when text             => ($"{value}.Length < {bound.Literal}", $"at least {Characters(bound.Literal)} long"),
               "maxLength" when text             => ($"{value}.Length > {bound.Literal}", $"at most {Characters(bound.Literal)} long"),
               _ => throw new NotSupportedException($"`{bound.Keyword}` bounds no `{type}`, so this generator states no check for one there."),
             };
    }

    private static string Characters(string count)
      => count == "1"
           ? "1 character"
           : count + " characters";

    // A name is PascalCase, so lowercasing its first letter gives an identifier that differs from
    // the property and from every other option's - two names differing only there could not both
    // be PascalCase. What it can be is a keyword, and `@` is what makes one an identifier again.
    private static string Local(string name)
    {
      var local = char.ToLowerInvariant(name[0]) + name.Substring(1);

      return Reserved.Contains(local)
               ? "@" + local
               : local;
    }

    /// <summary>Refuses a name that is not a C# name of this vocabulary.</summary>
    /// <param name="name">The name the schema spells.</param>
    /// <param name="what">What it names, for the message.</param>
    /// <exception cref="NotSupportedException">The name has no C# form this emits.</exception>
    /// <remarks>
    ///   A name reaches an identifier, a `nameof`, a string literal in an attribute and a string
    ///   literal in a message, and none of the four is quoted on the way. PascalCase letters and
    ///   digits is what all of them take verbatim, and it is what this vocabulary produces: an
    ///   option is a Rust field renamed. Anything else is a compile error in a file nobody wrote,
    ///   which is a poor way to learn that a schema said something this cannot write.
    /// </remarks>
    private static void RefuseAName(string name,
                                    string what)
    {
      if (!PascalCase.IsMatch(name))
      {
        throw new NotSupportedException($"`{name}` names {what}, and this generator writes a name of PascalCase letters and digits.");
      }

      if (Members.Contains(name))
      {
        throw new NotSupportedException($"`{name}` names {what}, which is also a member every generated class has.");
      }
    }

    // `\A` and `\z` rather than `^` and `$`: outside multiline mode `$` still matches before a
    // single trailing newline, so `^...$` admits a name ending in one - which reaches a string
    // literal in the emitted C# and does not close it.
    private static readonly Regex PascalCase = new(@"\A[A-Z][A-Za-z0-9]*\z",
                                                   RegexOptions.CultureInvariant);

    // What a generated class already declares, or inherits and would shadow without saying so.
    // `Encode` is the root's, and a group has none - listed for every class all the same, because
    // which group is the root is no reason for an option to be spelled one way here.
    private static readonly HashSet<string> Members = new(StringComparer.Ordinal)
                                                      {
                                                        "Encode",
                                                        "Equals",
                                                        "GetHashCode",
                                                        "GetType",
                                                        "ToString",
                                                        "Validate",
                                                      };

    private static readonly HashSet<string> Reserved = new(StringComparer.Ordinal)
                                                       {
                                                         "abstract",
                                                         "as",
                                                         "base",
                                                         "bool",
                                                         "break",
                                                         "byte",
                                                         "case",
                                                         "catch",
                                                         "char",
                                                         "checked",
                                                         "class",
                                                         "const",
                                                         "continue",
                                                         "decimal",
                                                         "default",
                                                         "delegate",
                                                         "do",
                                                         "double",
                                                         "else",
                                                         "enum",
                                                         "event",
                                                         "explicit",
                                                         "extern",
                                                         "false",
                                                         "finally",
                                                         "fixed",
                                                         "float",
                                                         "for",
                                                         "foreach",
                                                         "goto",
                                                         "if",
                                                         "implicit",
                                                         "in",
                                                         "int",
                                                         "interface",
                                                         "internal",
                                                         "is",
                                                         "lock",
                                                         "long",
                                                         "namespace",
                                                         "new",
                                                         "null",
                                                         "object",
                                                         "operator",
                                                         "out",
                                                         "override",
                                                         "params",
                                                         "private",
                                                         "protected",
                                                         "public",
                                                         "readonly",
                                                         "ref",
                                                         "return",
                                                         "sbyte",
                                                         "sealed",
                                                         "short",
                                                         "sizeof",
                                                         "stackalloc",
                                                         "static",
                                                         "string",
                                                         "struct",
                                                         "switch",
                                                         "this",
                                                         "throw",
                                                         "true",
                                                         "try",
                                                         "typeof",
                                                         "uint",
                                                         "ulong",
                                                         "unchecked",
                                                         "unsafe",
                                                         "ushort",
                                                         "using",
                                                         "virtual",
                                                         "void",
                                                         "volatile",
                                                         "while",
                                                       };

    private static void TrimBlankLine(StringBuilder source)
    {
      while (source.Length >= 2 && source[source.Length - 1] == '\n' && source[source.Length - 2] == '\n')
      {
        source.Length--;
      }
    }
  }
}
