// <auto-generated>
//     Generated from options.schema.json by ArmoniK.Api.Client.RustGrpcChannel.OptionsGenerator.
//     Edits here are lost. Change the Rust option types, render the schema again,
//     and build: the schema is what this file is.
// </auto-generated>

// This file is part of the ArmoniK project
//
// Copyright (C) ANEO, 2021-2026. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License")
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ArmoniK.Api.Client.RustGrpcChannel;

// Rooted at ChannelOptions, which reaches every group of the vocabulary, so the whole graph is
// serialized without reflection - which is what lets a trimmed or native-AOT host use this.
[JsonSerializable(typeof(ChannelOptions))]
internal partial class ChannelOptionsJsonContext : JsonSerializerContext
{
}

/// <summary>What a caller may set on one channel.</summary>
public sealed class ChannelOptions
{
  /// <summary>Options nobody has set.</summary>
  public ChannelOptions()
  {
  }

  /// <summary>A copy of <paramref name="other" />, sharing nothing with it.</summary>
  /// <param name="other">The options to copy.</param>
  /// <exception cref="ArgumentNullException"><paramref name="other" /> is null.</exception>
  public ChannelOptions(ChannelOptions other)
  {
    if (other is null)
    {
      throw new ArgumentNullException(nameof(other));
    }

    DeliveryCredits = other.DeliveryCredits;
    MaxReceiveMessageSize = other.MaxReceiveMessageSize;
    MaxSendsInFlight = other.MaxSendsInFlight;
    Transport = other.Transport is null
                  ? null
                  : new TransportOptions(other.Transport);
    UserAgent = other.UserAgent;
  }

  /// <summary>How many events the engine may hold for a call the host has not read from.</summary>
  [JsonPropertyName("DeliveryCredits")]
  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
  public int? DeliveryCredits { get; set; }

  /// <summary>The largest message this client will accept, in bytes.</summary>
  /// <remarks>
  ///   No upper bound, because the largest a caller can name is a channel that refuses nothing.
  ///   Zero is refused: it is a channel that can receive no message at all.
  /// </remarks>
  [JsonPropertyName("MaxReceiveMessageSize")]
  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
  public int? MaxReceiveMessageSize { get; set; }

  /// <summary>How many messages a call may have sent and unacquitted at once.</summary>
  [JsonPropertyName("MaxSendsInFlight")]
  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
  public int? MaxSendsInFlight { get; set; }

  /// <summary>What the transport does, beyond reaching the endpoint.</summary>
  [JsonPropertyName("Transport")]
  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
  public TransportOptions? Transport { get; set; }

  /// <summary>What this client calls itself in <c>user-agent</c>. Absent for the engine's own.</summary>
  [JsonPropertyName("UserAgent")]
  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
  public string? UserAgent { get; set; }

  /// <summary>Refuses a value the schema excludes.</summary>
  /// <exception cref="ArgumentOutOfRangeException">An option is outside its stated bounds.</exception>
  public void Validate()
  {
    if (DeliveryCredits is int deliveryCredits && (deliveryCredits < 1 || deliveryCredits > 536870910))
    {
      throw new ArgumentOutOfRangeException(nameof(DeliveryCredits),
                                            deliveryCredits,
                                            "DeliveryCredits has to be at least 1 and at most 536870910.");
    }

    if (MaxReceiveMessageSize is int maxReceiveMessageSize && maxReceiveMessageSize < 1)
    {
      throw new ArgumentOutOfRangeException(nameof(MaxReceiveMessageSize),
                                            maxReceiveMessageSize,
                                            "MaxReceiveMessageSize has to be at least 1.");
    }

    if (MaxSendsInFlight is int maxSendsInFlight && (maxSendsInFlight < 1 || maxSendsInFlight > 536870910))
    {
      throw new ArgumentOutOfRangeException(nameof(MaxSendsInFlight),
                                            maxSendsInFlight,
                                            "MaxSendsInFlight has to be at least 1 and at most 536870910.");
    }

    if (UserAgent is string userAgent && userAgent.Length < 1)
    {
      throw new ArgumentOutOfRangeException(nameof(UserAgent),
                                            userAgent,
                                            "UserAgent has to be at least 1 character long.");
    }

    Transport?.Validate();
  }

  /// <summary>The document the engine reads, as UTF-8.</summary>
  /// <returns>The options as JSON, without the ones left unset.</returns>
  /// <exception cref="ArgumentOutOfRangeException">An option is outside its bounds.</exception>
  /// <remarks>
  ///   Checked before it is written, not after it is refused: the engine answers a bad
  ///   document with a status naming neither the option nor the bound.
  /// </remarks>
  internal byte[] Encode()
  {
    Validate();

    return JsonSerializer.SerializeToUtf8Bytes(this,
                                               ChannelOptionsJsonContext.Default.ChannelOptions);
  }
}

/// <summary>What the transport does, beyond reaching the endpoint it was given.</summary>
/// <remarks>
///   The endpoint is not here: it is the one value a channel cannot be created without, so it
///   crosses the ABI as its own argument rather than as an option that happens to be mandatory.
///   Everything in this document has a default, and <c>{}</c> is a valid configuration.
/// </remarks>
public sealed class TransportOptions
{
  /// <summary>Options nobody has set.</summary>
  public TransportOptions()
  {
  }

  /// <summary>A copy of <paramref name="other" />, sharing nothing with it.</summary>
  /// <param name="other">The options to copy.</param>
  /// <exception cref="ArgumentNullException"><paramref name="other" /> is null.</exception>
  public TransportOptions(TransportOptions other)
  {
    if (other is null)
    {
      throw new ArgumentNullException(nameof(other));
    }

    ConnectTimeoutSeconds = other.ConnectTimeoutSeconds;
  }

  /// <summary>How long a dial may take before it is given up on. Absent for the engine's own default.</summary>
  /// <remarks>Zero is refused: no dial could beat it, so it names a channel that can never connect.</remarks>
  [JsonPropertyName("ConnectTimeoutSeconds")]
  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
  public double? ConnectTimeoutSeconds { get; set; }

  /// <summary>Refuses a value the schema excludes.</summary>
  /// <exception cref="ArgumentOutOfRangeException">An option is outside its stated bounds.</exception>
  public void Validate()
  {
    if (ConnectTimeoutSeconds is double connectTimeoutSeconds && (connectTimeoutSeconds <= 0 || double.IsNaN(connectTimeoutSeconds) || double.IsInfinity(connectTimeoutSeconds)))
    {
      throw new ArgumentOutOfRangeException(nameof(ConnectTimeoutSeconds),
                                            connectTimeoutSeconds,
                                            "ConnectTimeoutSeconds has to be greater than 0 and finite.");
    }
  }
}
