// <auto-generated>
//     Generated from options.schema.json by ArmoniK.Api.Client.RustGrpcChannel.OptionsGenerator.
//     Edits here are lost. Change the Rust option types, render the schema again,
//     and build: the schema is what this file is.
// </auto-generated>

// This file is part of the ArmoniK project
//
// Copyright (C) ANEO, 2021-2026. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License")
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ArmoniK.Api.Client.RustGrpcChannel;

// Rooted at ChannelOptions, which reaches every group of the vocabulary, so the whole graph is
// serialized without reflection - which is what lets a trimmed or native-AOT host use this.
[JsonSerializable(typeof(ChannelOptions))]
internal partial class ChannelOptionsJsonContext : JsonSerializerContext
{
}

/// <summary>What a caller may set on one channel.</summary>
public sealed class ChannelOptions
{
  /// <summary>Options nobody has set.</summary>
  public ChannelOptions()
  {
  }

  /// <summary>A copy of <paramref name="other" />, sharing nothing with it.</summary>
  /// <param name="other">The options to copy.</param>
  /// <exception cref="ArgumentNullException"><paramref name="other" /> is null.</exception>
  public ChannelOptions(ChannelOptions other)
  {
    if (other is null)
    {
      throw new ArgumentNullException(nameof(other));
    }

    ConnectEagerly = other.ConnectEagerly;
    DefaultDeadlineSeconds = other.DefaultDeadlineSeconds;
    DeliveryCredits = other.DeliveryCredits;
    Http2 = other.Http2 is null
              ? null
              : new Http2Options(other.Http2);
    MaxReceiveMessageSize = other.MaxReceiveMessageSize;
    MaxSendsInFlight = other.MaxSendsInFlight;
    Retry = other.Retry is null
              ? null
              : new RetryOptions(other.Retry);
    Transport = other.Transport is null
                  ? null
                  : new TransportOptions(other.Transport);
    UserAgent = other.UserAgent;
  }

  /// <summary>
  ///   Whether the channel starts dialling its endpoint as it is created rather than at its first
  ///   call, which then finds the session open or joins the dial under way. A dial that fails is
  ///   not reported: the first call dials again and reports what it meets.
  /// </summary>
  /// <remarks>Defaults to false.</remarks>
  [JsonPropertyName("ConnectEagerly")]
  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
  public bool? ConnectEagerly { get; set; }

  /// <summary>
  ///   The deadline of a call that states none, counted from its start: the call ends
  ///   <c>DEADLINE_EXCEEDED</c> once it passes, and the server is told what was left of it when the
  ///   call started as <c>grpc-timeout</c>. A call's own deadline takes its place, and a call that
  ///   states none takes this one.
  /// </summary>
  /// <remarks>
  ///   Defaults to none, a call waiting as long as its answer takes; at least a nanosecond, the
  ///   finest duration the engine holds.
  /// </remarks>
  [JsonPropertyName("DefaultDeadlineSeconds")]
  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
  public double? DefaultDeadlineSeconds { get; set; }

  /// <summary>
  ///   How many of a call's payloads the host may hold at once, delivered and not yet given back.
  ///   The terminal status takes none, so a host holds at most one more.
  /// </summary>
  /// <remarks>Defaults to 1.</remarks>
  [JsonPropertyName("DeliveryCredits")]
  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
  public int? DeliveryCredits { get; set; }

  /// <summary>The HTTP/2 session the channel's calls share.</summary>
  /// <remarks>Defaults to <c>{}</c>, which leaves each of its options at its own default.</remarks>
  [JsonPropertyName("Http2")]
  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
  public Http2Options? Http2 { get; set; }

  /// <summary>The largest message this client will accept, in bytes.</summary>
  /// <remarks>
  ///   Defaults to 4194304, 4 MiB. No upper bound, because the largest a caller can name is a
  ///   channel that refuses nothing. Zero is refused: it is a channel that can receive no message
  ///   at all.
  /// </remarks>
  [JsonPropertyName("MaxReceiveMessageSize")]
  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
  public int? MaxReceiveMessageSize { get; set; }

  /// <summary>How many messages a call may have sent and unacquitted at once.</summary>
  /// <remarks>Defaults to 1.</remarks>
  [JsonPropertyName("MaxSendsInFlight")]
  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
  public int? MaxSendsInFlight { get; set; }

  /// <summary>When a failed call is sent again.</summary>
  /// <remarks>
  ///   Defaults to <c>{}</c>: five attempts in all, as <c>GrpcClient</c> has them. A call its peer never
  ///   processed goes again besides, whatever <c>MaxAttempts</c> is, while every message it sent is
  ///   kept.
  /// </remarks>
  [JsonPropertyName("Retry")]
  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
  public RetryOptions? Retry { get; set; }

  /// <summary>What the transport does, beyond reaching the endpoint.</summary>
  /// <remarks>Defaults to <c>{}</c>, which leaves each of its options at its own default.</remarks>
  [JsonPropertyName("Transport")]
  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
  public TransportOptions? Transport { get; set; }

  /// <summary>What this client calls itself in <c>user-agent</c>.</summary>
  /// <remarks>Defaults to <c>armonik-transport/</c> followed by the engine's version.</remarks>
  [JsonPropertyName("UserAgent")]
  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
  public string? UserAgent { get; set; }

  /// <summary>Refuses an option outside the range this channel accepts.</summary>
  /// <exception cref="ArgumentOutOfRangeException">An option is outside its stated bounds.</exception>
  public void Validate()
  {
    if (DefaultDeadlineSeconds is double defaultDeadlineSeconds && (defaultDeadlineSeconds < 1E-09 || defaultDeadlineSeconds >= 1.8446744073709552E+19 || double.IsNaN(defaultDeadlineSeconds) || double.IsInfinity(defaultDeadlineSeconds)))
    {
      throw new ArgumentOutOfRangeException(nameof(DefaultDeadlineSeconds),
                                            defaultDeadlineSeconds,
                                            "DefaultDeadlineSeconds has to be at least 1E-09 and less than 1.8446744073709552E+19 and finite.");
    }

    if (DeliveryCredits is int deliveryCredits && (deliveryCredits < 1 || deliveryCredits > 536870910))
    {
      throw new ArgumentOutOfRangeException(nameof(DeliveryCredits),
                                            deliveryCredits,
                                            "DeliveryCredits has to be at least 1 and at most 536870910.");
    }

    if (MaxReceiveMessageSize is int maxReceiveMessageSize && maxReceiveMessageSize < 1)
    {
      throw new ArgumentOutOfRangeException(nameof(MaxReceiveMessageSize),
                                            maxReceiveMessageSize,
                                            "MaxReceiveMessageSize has to be at least 1.");
    }

    if (MaxSendsInFlight is int maxSendsInFlight && (maxSendsInFlight < 1 || maxSendsInFlight > 536870910))
    {
      throw new ArgumentOutOfRangeException(nameof(MaxSendsInFlight),
                                            maxSendsInFlight,
                                            "MaxSendsInFlight has to be at least 1 and at most 536870910.");
    }

    if (UserAgent is string userAgent && userAgent.Length < 1)
    {
      throw new ArgumentOutOfRangeException(nameof(UserAgent),
                                            userAgent,
                                            "UserAgent has to be at least 1 character long.");
    }

    Http2?.Validate();
    Retry?.Validate();
    Transport?.Validate();
  }

  /// <summary>The document the engine reads, as UTF-8.</summary>
  /// <returns>The options as JSON, without the ones left unset.</returns>
  /// <exception cref="ArgumentOutOfRangeException">An option is outside its bounds.</exception>
  /// <remarks>
  ///   Checked before it is written, not after it is refused: the engine answers a bad
  ///   document with a status naming neither the option nor the bound.
  /// </remarks>
  internal byte[] Encode()
  {
    Validate();

    return JsonSerializer.SerializeToUtf8Bytes(this,
                                               ChannelOptionsJsonContext.Default.ChannelOptions);
  }
}

/// <summary>
///   The HTTP/2 session a channel's calls share: how it checks that the peer is there, and how much
///   it lets the peer send ahead of what is read.
/// </summary>
public sealed class Http2Options
{
  /// <summary>Options nobody has set.</summary>
  public Http2Options()
  {
  }

  /// <summary>A copy of <paramref name="other" />, sharing nothing with it.</summary>
  /// <param name="other">The options to copy.</param>
  /// <exception cref="ArgumentNullException"><paramref name="other" /> is null.</exception>
  public Http2Options(Http2Options other)
  {
    if (other is null)
    {
      throw new ArgumentNullException(nameof(other));
    }

    ConnectionWindowSize = other.ConnectionWindowSize;
    IdleTimeoutSeconds = other.IdleTimeoutSeconds;
    KeepAliveIntervalSeconds = other.KeepAliveIntervalSeconds;
    KeepAliveTimeoutSeconds = other.KeepAliveTimeoutSeconds;
    KeepAliveWhileIdle = other.KeepAliveWhileIdle;
    StreamWindowSize = other.StreamWindowSize;
  }

  /// <summary>
  ///   How many bytes the peer may send ahead of what is read, across every call of the channel.
  ///   A call its host does not read holds up to <c>StreamWindowSize</c> of it, so enough of them stop
  ///   the others receiving. At least 65535, the window every connection starts with.
  /// </summary>
  /// <remarks>Defaults to 5242880, 5 MiB.</remarks>
  [JsonPropertyName("ConnectionWindowSize")]
  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
  public int? ConnectionWindowSize { get; set; }

  /// <summary>
  ///   How long the session stays open with no call on it before it is closed, the next call
  ///   dialling a new one. A call holds the session from its dial to the end of its response.
  /// </summary>
  /// <remarks>Defaults to none: an idle session stays open.</remarks>
  [JsonPropertyName("IdleTimeoutSeconds")]
  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
  public double? IdleTimeoutSeconds { get; set; }

  /// <summary>How often a PING is sent to the peer. Defaults to none sent.</summary>
  [JsonPropertyName("KeepAliveIntervalSeconds")]
  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
  public double? KeepAliveIntervalSeconds { get; set; }

  /// <summary>How long a PING may go unanswered before the session and its calls are ended.</summary>
  /// <remarks>Defaults to 20.</remarks>
  [JsonPropertyName("KeepAliveTimeoutSeconds")]
  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
  public double? KeepAliveTimeoutSeconds { get; set; }

  /// <summary>Whether a PING is also sent while no call is open.</summary>
  /// <remarks>Defaults to false.</remarks>
  [JsonPropertyName("KeepAliveWhileIdle")]
  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
  public bool? KeepAliveWhileIdle { get; set; }

  /// <summary>How many bytes of one call the peer may send ahead of what is read.</summary>
  /// <remarks>Defaults to 2097152, 2 MiB.</remarks>
  [JsonPropertyName("StreamWindowSize")]
  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
  public int? StreamWindowSize { get; set; }

  /// <summary>Refuses an option outside the range this channel accepts.</summary>
  /// <exception cref="ArgumentOutOfRangeException">An option is outside its stated bounds.</exception>
  public void Validate()
  {
    if (ConnectionWindowSize is int connectionWindowSize && connectionWindowSize < 65535)
    {
      throw new ArgumentOutOfRangeException(nameof(ConnectionWindowSize),
                                            connectionWindowSize,
                                            "ConnectionWindowSize has to be at least 65535.");
    }

    if (IdleTimeoutSeconds is double idleTimeoutSeconds && (idleTimeoutSeconds < 1E-09 || idleTimeoutSeconds >= 1.8446744073709552E+19 || double.IsNaN(idleTimeoutSeconds) || double.IsInfinity(idleTimeoutSeconds)))
    {
      throw new ArgumentOutOfRangeException(nameof(IdleTimeoutSeconds),
                                            idleTimeoutSeconds,
                                            "IdleTimeoutSeconds has to be at least 1E-09 and less than 1.8446744073709552E+19 and finite.");
    }

    if (KeepAliveIntervalSeconds is double keepAliveIntervalSeconds && (keepAliveIntervalSeconds < 1E-09 || keepAliveIntervalSeconds >= 1.8446744073709552E+19 || double.IsNaN(keepAliveIntervalSeconds) || double.IsInfinity(keepAliveIntervalSeconds)))
    {
      throw new ArgumentOutOfRangeException(nameof(KeepAliveIntervalSeconds),
                                            keepAliveIntervalSeconds,
                                            "KeepAliveIntervalSeconds has to be at least 1E-09 and less than 1.8446744073709552E+19 and finite.");
    }

    if (KeepAliveTimeoutSeconds is double keepAliveTimeoutSeconds && (keepAliveTimeoutSeconds < 1E-09 || keepAliveTimeoutSeconds >= 1.8446744073709552E+19 || double.IsNaN(keepAliveTimeoutSeconds) || double.IsInfinity(keepAliveTimeoutSeconds)))
    {
      throw new ArgumentOutOfRangeException(nameof(KeepAliveTimeoutSeconds),
                                            keepAliveTimeoutSeconds,
                                            "KeepAliveTimeoutSeconds has to be at least 1E-09 and less than 1.8446744073709552E+19 and finite.");
    }

    if (StreamWindowSize is int streamWindowSize && streamWindowSize < 1)
    {
      throw new ArgumentOutOfRangeException(nameof(StreamWindowSize),
                                            streamWindowSize,
                                            "StreamWindowSize has to be at least 1.");
    }
  }
}

/// <summary>
///   When a failed call is sent again, as gRFC A6 has it: after a backoff drawn below a bound
///   that starts at <c>InitialBackoffSeconds</c> and grows by <c>BackoffMultiplier</c> to
///   <c>MaxBackoffSeconds</c>, for UNAVAILABLE, ABORTED and UNKNOWN, while no response head has reached
///   the reader and what the call sent is still kept for the replay.
/// </summary>
public sealed class RetryOptions
{
  /// <summary>Options nobody has set.</summary>
  public RetryOptions()
  {
  }

  /// <summary>A copy of <paramref name="other" />, sharing nothing with it.</summary>
  /// <param name="other">The options to copy.</param>
  /// <exception cref="ArgumentNullException"><paramref name="other" /> is null.</exception>
  public RetryOptions(RetryOptions other)
  {
    if (other is null)
    {
      throw new ArgumentNullException(nameof(other));
    }

    BackoffMultiplier = other.BackoffMultiplier;
    CallReplayBytes = other.CallReplayBytes;
    ChannelReplayBytes = other.ChannelReplayBytes;
    InitialBackoffSeconds = other.InitialBackoffSeconds;
    MaxAttempts = other.MaxAttempts;
    MaxBackoffSeconds = other.MaxBackoffSeconds;
  }

  /// <summary>What each bound is multiplied by; 1 retries at a fixed bound.</summary>
  /// <remarks>Defaults to 1.5.</remarks>
  [JsonPropertyName("BackoffMultiplier")]
  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
  public double? BackoffMultiplier { get; set; }

  /// <summary>The bytes one call may keep for a replay; a call that sends more is not tried again.</summary>
  /// <remarks>Defaults to 1048576, 1 MiB.</remarks>
  [JsonPropertyName("CallReplayBytes")]
  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
  public int? CallReplayBytes { get; set; }

  /// <summary>
  ///   The bytes all of the channel's calls may keep for a replay together; a call whose message
  ///   would pass it is not tried again.
  /// </summary>
  /// <remarks>Defaults to 16777216, 16 MiB.</remarks>
  [JsonPropertyName("ChannelReplayBytes")]
  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
  public int? ChannelReplayBytes { get; set; }

  /// <summary>The bound of the first backoff.</summary>
  /// <remarks>Defaults to 1.</remarks>
  [JsonPropertyName("InitialBackoffSeconds")]
  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
  public double? InitialBackoffSeconds { get; set; }

  /// <summary>
  ///   Attempts in all, the first included; 1 retries nothing. A call its peer never processed
  ///   goes again besides, whatever this is, while every message it sent is kept.
  /// </summary>
  /// <remarks>Defaults to 5.</remarks>
  [JsonPropertyName("MaxAttempts")]
  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
  public int? MaxAttempts { get; set; }

  /// <summary>What the bound grows to and no further; refused below <c>InitialBackoffSeconds</c>.</summary>
  /// <remarks>Defaults to 5.</remarks>
  [JsonPropertyName("MaxBackoffSeconds")]
  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
  public double? MaxBackoffSeconds { get; set; }

  /// <summary>Refuses an option outside the range this channel accepts.</summary>
  /// <exception cref="ArgumentOutOfRangeException">An option is outside its stated bounds.</exception>
  public void Validate()
  {
    if (BackoffMultiplier is double backoffMultiplier && (backoffMultiplier < 1 || double.IsNaN(backoffMultiplier) || double.IsInfinity(backoffMultiplier)))
    {
      throw new ArgumentOutOfRangeException(nameof(BackoffMultiplier),
                                            backoffMultiplier,
                                            "BackoffMultiplier has to be at least 1 and finite.");
    }

    if (CallReplayBytes is int callReplayBytes && callReplayBytes < 0)
    {
      throw new ArgumentOutOfRangeException(nameof(CallReplayBytes),
                                            callReplayBytes,
                                            "CallReplayBytes has to be at least 0.");
    }

    if (ChannelReplayBytes is int channelReplayBytes && channelReplayBytes < 0)
    {
      throw new ArgumentOutOfRangeException(nameof(ChannelReplayBytes),
                                            channelReplayBytes,
                                            "ChannelReplayBytes has to be at least 0.");
    }

    if (InitialBackoffSeconds is double initialBackoffSeconds && (initialBackoffSeconds < 1E-09 || initialBackoffSeconds >= 1.8446744073709552E+19 || double.IsNaN(initialBackoffSeconds) || double.IsInfinity(initialBackoffSeconds)))
    {
      throw new ArgumentOutOfRangeException(nameof(InitialBackoffSeconds),
                                            initialBackoffSeconds,
                                            "InitialBackoffSeconds has to be at least 1E-09 and less than 1.8446744073709552E+19 and finite.");
    }

    if (MaxAttempts is int maxAttempts && maxAttempts < 1)
    {
      throw new ArgumentOutOfRangeException(nameof(MaxAttempts),
                                            maxAttempts,
                                            "MaxAttempts has to be at least 1.");
    }

    if (MaxBackoffSeconds is double maxBackoffSeconds && (maxBackoffSeconds < 1E-09 || maxBackoffSeconds >= 1.8446744073709552E+19 || double.IsNaN(maxBackoffSeconds) || double.IsInfinity(maxBackoffSeconds)))
    {
      throw new ArgumentOutOfRangeException(nameof(MaxBackoffSeconds),
                                            maxBackoffSeconds,
                                            "MaxBackoffSeconds has to be at least 1E-09 and less than 1.8446744073709552E+19 and finite.");
    }
  }
}

/// <summary>What the transport does, beyond reaching the endpoint it was given.</summary>
/// <remarks>
///   The endpoint is not here: it is the one value a channel cannot be created without, so it is
///   passed when the channel is opened rather than set as an option that happens to be mandatory.
///   Every option has a default, so naming none of them is a valid configuration.
/// </remarks>
public sealed class TransportOptions
{
  /// <summary>Options nobody has set.</summary>
  public TransportOptions()
  {
  }

  /// <summary>A copy of <paramref name="other" />, sharing nothing with it.</summary>
  /// <param name="other">The options to copy.</param>
  /// <exception cref="ArgumentNullException"><paramref name="other" /> is null.</exception>
  public TransportOptions(TransportOptions other)
  {
    if (other is null)
    {
      throw new ArgumentNullException(nameof(other));
    }

    ConnectTimeoutSeconds = other.ConnectTimeoutSeconds;
    Proxy = other.Proxy is null
              ? null
              : new ProxyOptions(other.Proxy);
    TcpKeepalive = other.TcpKeepalive is null
                     ? null
                     : new TcpKeepaliveOptions(other.TcpKeepalive);
    Tls = other.Tls is null
            ? null
            : new TlsOptions(other.Tls);
  }

  /// <summary>How long a dial may take before it is given up on.</summary>
  /// <remarks>
  ///   Defaults to 60, and at least a nanosecond, the finest duration the engine holds: a shorter
  ///   one could round to zero, which no dial could beat.
  /// </remarks>
  [JsonPropertyName("ConnectTimeoutSeconds")]
  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
  public double? ConnectTimeoutSeconds { get; set; }

  /// <summary>The HTTP proxy every dial tunnels through.</summary>
  /// <remarks>Defaults to <c>{}</c>, which tunnels through the proxy the environment names, if any.</remarks>
  [JsonPropertyName("Proxy")]
  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
  public ProxyOptions? Proxy { get; set; }

  /// <summary>The socket's keepalive.</summary>
  /// <remarks>Defaults to <c>{}</c>, which sets none.</remarks>
  [JsonPropertyName("TcpKeepalive")]
  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
  public TcpKeepaliveOptions? TcpKeepalive { get; set; }

  /// <summary>How an <c>https://</c> endpoint is secured.</summary>
  /// <remarks>
  ///   Defaults to <c>{}</c>: the server verified against the system's roots under the endpoint's
  ///   host, and no client certificate. Refused for an <c>http://</c> endpoint unless it sets nothing.
  /// </remarks>
  [JsonPropertyName("Tls")]
  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
  public TlsOptions? Tls { get; set; }

  /// <summary>Refuses an option outside the range this channel accepts.</summary>
  /// <exception cref="ArgumentOutOfRangeException">An option is outside its stated bounds.</exception>
  public void Validate()
  {
    if (ConnectTimeoutSeconds is double connectTimeoutSeconds && (connectTimeoutSeconds < 1E-09 || connectTimeoutSeconds >= 1.8446744073709552E+19 || double.IsNaN(connectTimeoutSeconds) || double.IsInfinity(connectTimeoutSeconds)))
    {
      throw new ArgumentOutOfRangeException(nameof(ConnectTimeoutSeconds),
                                            connectTimeoutSeconds,
                                            "ConnectTimeoutSeconds has to be at least 1E-09 and less than 1.8446744073709552E+19 and finite.");
    }

    Proxy?.Validate();
    TcpKeepalive?.Validate();
    Tls?.Validate();
  }
}

/// <summary>
///   An HTTP proxy, which a dial tunnels through with <c>CONNECT</c>, so TLS stays end to end with the
///   server.
/// </summary>
public sealed class ProxyOptions
{
  /// <summary>Options nobody has set.</summary>
  public ProxyOptions()
  {
  }

  /// <summary>A copy of <paramref name="other" />, sharing nothing with it.</summary>
  /// <param name="other">The options to copy.</param>
  /// <exception cref="ArgumentNullException"><paramref name="other" /> is null.</exception>
  public ProxyOptions(ProxyOptions other)
  {
    if (other is null)
    {
      throw new ArgumentNullException(nameof(other));
    }

    Address = other.Address;
    Password = other.Password;
    Username = other.Username;
  }

  /// <summary>
  ///   <c>none</c> for no proxy, <c>system</c> for the one the system names, or the proxy's <c>http://</c> URL,
  ///   with no path; <c>http://</c> is assumed when no scheme is written. The URL may carry <c>user:password@</c>,
  ///   percent-encoded, when <c>Username</c> and <c>Password</c> are not set - which a serialized document
  ///   then carries too.
  /// </summary>
  /// <remarks>
  ///   The environment's proxy is <c>ALL_PROXY</c>, <c>HTTPS_PROXY</c> or <c>HTTP_PROXY</c>, in either case and
  ///   by the endpoint's scheme, unless <c>NO_PROXY</c> names the endpoint's host; it is read when the
  ///   channel is created. An <c>https://</c> or <c>socks</c> one is refused when the channel is created,
  ///   and any other value the environment cannot read as a proxy is ignored.
  ///   On Windows, when the environment names no proxy, the system's is the one the current
  ///   user's network settings name: a PAC script, detected or at the configured address, which
  ///   WinHTTP fetches and runs for each dial off the calling thread, else the manual proxy and
  ///   its bypass list. Those settings are read when the channel is created, and an <c>https://</c> or
  ///   <c>socks</c> proxy they name is refused at each dial - except a script's <c>SOCKS</c> answer, which
  ///   WinHTTP drops, leaving a direct dial. A script that cannot be found or run is not tried
  ///   again for two minutes.
  ///   The system's proxy is never used for a loopback endpoint.
  ///   Defaults to <c>system</c>.
  /// </remarks>
  [JsonPropertyName("Address")]
  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
  public string? Address { get; set; }

  /// <summary>The password that goes with <c>Username</c>.</summary>
  /// <remarks>
  ///   Refused beside credentials the <c>Address</c> URL carries; ignored beside <c>none</c>, and when the
  ///   system names no proxy. Beside the environment's proxy, it takes the place of the password
  ///   that proxy's URL carries; beside the one Windows' settings name, it is the password.
  /// </remarks>
  [JsonPropertyName("Password")]
  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
  public string? Password { get; set; }

  /// <summary>The username the proxy is authenticated to with, by <c>Basic</c>, which forbids a <c>:</c> in it.</summary>
  /// <remarks>
  ///   Refused beside credentials the <c>Address</c> URL carries; ignored beside <c>none</c>, and when the
  ///   system names no proxy. Beside the environment's proxy, it takes the place of the username
  ///   that proxy's URL carries; beside the one Windows' settings name, it is the username.
  /// </remarks>
  [JsonPropertyName("Username")]
  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
  public string? Username { get; set; }

  /// <summary>Refuses an option outside the range this channel accepts.</summary>
  /// <exception cref="ArgumentOutOfRangeException">An option is outside its stated bounds.</exception>
  public void Validate()
  {
    if (Address is string address && address.Length < 1)
    {
      throw new ArgumentOutOfRangeException(nameof(Address),
                                            address,
                                            "Address has to be at least 1 character long.");
    }
  }
}

/// <summary>The socket's keepalive, off unless <c>IdleSeconds</c> is set.</summary>
/// <remarks>Each duration is whole seconds, which is what the socket option holds: a fraction is dropped.</remarks>
public sealed class TcpKeepaliveOptions
{
  /// <summary>Options nobody has set.</summary>
  public TcpKeepaliveOptions()
  {
  }

  /// <summary>A copy of <paramref name="other" />, sharing nothing with it.</summary>
  /// <param name="other">The options to copy.</param>
  /// <exception cref="ArgumentNullException"><paramref name="other" /> is null.</exception>
  public TcpKeepaliveOptions(TcpKeepaliveOptions other)
  {
    if (other is null)
    {
      throw new ArgumentNullException(nameof(other));
    }

    IdleSeconds = other.IdleSeconds;
    IntervalSeconds = other.IntervalSeconds;
    Retries = other.Retries;
  }

  /// <summary>
  ///   How long the connection may be idle before the first probe, from a second to 32767, the
  ///   most Linux holds.
  /// </summary>
  [JsonPropertyName("IdleSeconds")]
  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
  public double? IdleSeconds { get; set; }

  /// <summary>How long between two probes, from a second to 32767. Defaults to the operating system's.</summary>
  /// <remarks>Refused without <c>IdleSeconds</c>.</remarks>
  [JsonPropertyName("IntervalSeconds")]
  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
  public double? IntervalSeconds { get; set; }

  /// <summary>
  ///   How many probes go unanswered before the connection is dropped, at most 127, the most
  ///   Linux holds. Defaults to the operating system's, and is not applied on Windows.
  /// </summary>
  /// <remarks>Refused without <c>IdleSeconds</c>.</remarks>
  [JsonPropertyName("Retries")]
  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
  public int? Retries { get; set; }

  /// <summary>Refuses an option outside the range this channel accepts.</summary>
  /// <exception cref="ArgumentOutOfRangeException">An option is outside its stated bounds.</exception>
  public void Validate()
  {
    if (IdleSeconds is double idleSeconds && (idleSeconds < 1 || idleSeconds > 32767 || idleSeconds >= 1.8446744073709552E+19 || double.IsNaN(idleSeconds) || double.IsInfinity(idleSeconds)))
    {
      throw new ArgumentOutOfRangeException(nameof(IdleSeconds),
                                            idleSeconds,
                                            "IdleSeconds has to be at least 1 and at most 32767 and less than 1.8446744073709552E+19 and finite.");
    }

    if (IntervalSeconds is double intervalSeconds && (intervalSeconds < 1 || intervalSeconds > 32767 || intervalSeconds >= 1.8446744073709552E+19 || double.IsNaN(intervalSeconds) || double.IsInfinity(intervalSeconds)))
    {
      throw new ArgumentOutOfRangeException(nameof(IntervalSeconds),
                                            intervalSeconds,
                                            "IntervalSeconds has to be at least 1 and at most 32767 and less than 1.8446744073709552E+19 and finite.");
    }

    if (Retries is int retries && (retries < 1 || retries > 127))
    {
      throw new ArgumentOutOfRangeException(nameof(Retries),
                                            retries,
                                            "Retries has to be at least 1 and at most 127.");
    }
  }
}

/// <summary>
///   How an <c>https://</c> endpoint is secured. Each file is read when the channel is created, so a
///   path that names nothing usable is refused then, by its option's name.
/// </summary>
public sealed class TlsOptions
{
  /// <summary>Options nobody has set.</summary>
  public TlsOptions()
  {
  }

  /// <summary>A copy of <paramref name="other" />, sharing nothing with it.</summary>
  /// <param name="other">The options to copy.</param>
  /// <exception cref="ArgumentNullException"><paramref name="other" /> is null.</exception>
  public TlsOptions(TlsOptions other)
  {
    if (other is null)
    {
      throw new ArgumentNullException(nameof(other));
    }

    AllowUnsafeConnection = other.AllowUnsafeConnection;
    CaCertPath = other.CaCertPath;
    CaStore = other.CaStore is null
                ? null
                : new StoreCertificate(other.CaStore);
    CertP12 = other.CertP12;
    CertP12Password = other.CertP12Password;
    CertPem = other.CertPem;
    CertStore = other.CertStore is null
                  ? null
                  : new StoreCertificate(other.CertStore);
    KeyPem = other.KeyPem;
    OverrideTargetName = other.OverrideTargetName;
  }

  /// <summary>Accept any server certificate. The connection is still encrypted, to whoever answers.</summary>
  /// <remarks>Defaults to false.</remarks>
  [JsonPropertyName("AllowUnsafeConnection")]
  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
  public bool? AllowUnsafeConnection { get; set; }

  /// <summary>
  ///   Path to a PEM file of the roots the server certificate is verified against, in place of
  ///   the system's. Every certificate the file holds is a root.
  /// </summary>
  /// <remarks>Refused together with <c>AllowUnsafeConnection</c>, which verifies nothing.</remarks>
  [JsonPropertyName("CaCertPath")]
  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
  public string? CaCertPath { get; set; }

  /// <summary>
  ///   The root the server certificate is verified against, from a Windows certificate store,
  ///   <c>Root</c> unless <c>Name</c> says otherwise, in place of the system's.
  /// </summary>
  /// <remarks>Refused together with <c>CaCertPath</c> or <c>AllowUnsafeConnection</c>, and off Windows.</remarks>
  [JsonPropertyName("CaStore")]
  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
  public StoreCertificate? CaStore { get; set; }

  /// <summary>Path to a PKCS#12 bundle of the client's certificate, the issuers it carries and the key.</summary>
  /// <remarks>Refused together with <c>CertPem</c> or <c>KeyPem</c>, which name an identity too.</remarks>
  [JsonPropertyName("CertP12")]
  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
  public string? CertP12 { get; set; }

  /// <summary>The password <c>CertP12</c> is protected by. Defaults to the empty one.</summary>
  /// <remarks>Refused without <c>CertP12</c>.</remarks>
  [JsonPropertyName("CertP12Password")]
  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
  public string? CertP12Password { get; set; }

  /// <summary>Path to a PEM file of the client's certificate, then each issuer the server may not hold.</summary>
  /// <remarks>Set together with <c>KeyPem</c>.</remarks>
  [JsonPropertyName("CertPem")]
  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
  public string? CertPem { get; set; }

  /// <summary>
  ///   The client's certificate and key from a Windows certificate store, <c>My</c> unless <c>Name</c>
  ///   says otherwise, with the issuers the store's <c>CA</c> holds. Its key has to be exportable.
  /// </summary>
  /// <remarks>Refused together with <c>CertPem</c>, <c>KeyPem</c> or <c>CertP12</c>, and off Windows.</remarks>
  [JsonPropertyName("CertStore")]
  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
  public StoreCertificate? CertStore { get; set; }

  /// <summary>Path to a PEM file of the key of the client's certificate.</summary>
  /// <remarks>Set together with <c>CertPem</c>.</remarks>
  [JsonPropertyName("KeyPem")]
  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
  public string? KeyPem { get; set; }

  /// <summary>
  ///   The host the server certificate is verified against, and sent as SNI, in place of the
  ///   endpoint's: a DNS name or an IP address, <c>[::1]</c> for IPv6, with an optional port that is
  ///   not read.
  /// </summary>
  [JsonPropertyName("OverrideTargetName")]
  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
  public string? OverrideTargetName { get; set; }

  /// <summary>Refuses an option outside the range this channel accepts.</summary>
  /// <exception cref="ArgumentOutOfRangeException">An option is outside its stated bounds.</exception>
  public void Validate()
  {
    if (CaCertPath is string caCertPath && caCertPath.Length < 1)
    {
      throw new ArgumentOutOfRangeException(nameof(CaCertPath),
                                            caCertPath,
                                            "CaCertPath has to be at least 1 character long.");
    }

    if (CertP12 is string certP12 && certP12.Length < 1)
    {
      throw new ArgumentOutOfRangeException(nameof(CertP12),
                                            certP12,
                                            "CertP12 has to be at least 1 character long.");
    }

    if (CertPem is string certPem && certPem.Length < 1)
    {
      throw new ArgumentOutOfRangeException(nameof(CertPem),
                                            certPem,
                                            "CertPem has to be at least 1 character long.");
    }

    if (KeyPem is string keyPem && keyPem.Length < 1)
    {
      throw new ArgumentOutOfRangeException(nameof(KeyPem),
                                            keyPem,
                                            "KeyPem has to be at least 1 character long.");
    }

    if (OverrideTargetName is string overrideTargetName && overrideTargetName.Length < 1)
    {
      throw new ArgumentOutOfRangeException(nameof(OverrideTargetName),
                                            overrideTargetName,
                                            "OverrideTargetName has to be at least 1 character long.");
    }

    CaStore?.Validate();
    CertStore?.Validate();
  }
}

/// <summary>
///   A certificate of a Windows certificate store, named by exactly one of <c>Thumbprint</c>,
///   <c>SubjectName</c> and <c>FriendlyName</c>.
/// </summary>
public sealed class StoreCertificate
{
  /// <summary>Options nobody has set.</summary>
  public StoreCertificate()
  {
  }

  /// <summary>A copy of <paramref name="other" />, sharing nothing with it.</summary>
  /// <param name="other">The options to copy.</param>
  /// <exception cref="ArgumentNullException"><paramref name="other" /> is null.</exception>
  public StoreCertificate(StoreCertificate other)
  {
    if (other is null)
    {
      throw new ArgumentNullException(nameof(other));
    }

    FriendlyName = other.FriendlyName;
    Location = other.Location;
    Name = other.Name;
    SubjectName = other.SubjectName;
    Thumbprint = other.Thumbprint;
  }

  /// <summary>The certificate's friendly name, exactly.</summary>
  [JsonPropertyName("FriendlyName")]
  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
  public string? FriendlyName { get; set; }

  /// <summary><c>CurrentUser</c> or <c>LocalMachine</c>.</summary>
  /// <remarks>Defaults to <c>CurrentUser</c>.</remarks>
  [JsonPropertyName("Location")]
  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
  public string? Location { get; set; }

  /// <summary>The store's name, such as <c>My</c>, <c>Root</c> or <c>CA</c>. Defaults to the one its option states.</summary>
  [JsonPropertyName("Name")]
  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
  public string? Name { get; set; }

  /// <summary>
  ///   A text the certificate's subject contains, compared without case, as .NET's
  ///   <c>FindBySubjectName</c> compares it.
  /// </summary>
  [JsonPropertyName("SubjectName")]
  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
  public string? SubjectName { get; set; }

  /// <summary>
  ///   The certificate's SHA-1 fingerprint, as 40 hexadecimal digits; spaces and colons between
  ///   them are ignored.
  /// </summary>
  [JsonPropertyName("Thumbprint")]
  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
  public string? Thumbprint { get; set; }

  /// <summary>Refuses an option outside the range this channel accepts.</summary>
  /// <exception cref="ArgumentOutOfRangeException">An option is outside its stated bounds.</exception>
  public void Validate()
  {
    if (FriendlyName is string friendlyName && friendlyName.Length < 1)
    {
      throw new ArgumentOutOfRangeException(nameof(FriendlyName),
                                            friendlyName,
                                            "FriendlyName has to be at least 1 character long.");
    }

    if (Location is string location && location.Length < 1)
    {
      throw new ArgumentOutOfRangeException(nameof(Location),
                                            location,
                                            "Location has to be at least 1 character long.");
    }

    if (Name is string name && name.Length < 1)
    {
      throw new ArgumentOutOfRangeException(nameof(Name),
                                            name,
                                            "Name has to be at least 1 character long.");
    }

    if (SubjectName is string subjectName && subjectName.Length < 1)
    {
      throw new ArgumentOutOfRangeException(nameof(SubjectName),
                                            subjectName,
                                            "SubjectName has to be at least 1 character long.");
    }

    if (Thumbprint is string thumbprint && thumbprint.Length < 1)
    {
      throw new ArgumentOutOfRangeException(nameof(Thumbprint),
                                            thumbprint,
                                            "Thumbprint has to be at least 1 character long.");
    }
  }
}
