// <auto-generated>
//     Generated from runtime.schema.json by ArmoniK.Api.Client.RustGrpcChannel.OptionsGenerator.
//     Edits here are lost. Change the Rust option types, render the schema again,
//     and build: the schema is what this file is.
// </auto-generated>

// This file is part of the ArmoniK project
//
// Copyright (C) ANEO, 2021-2026. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License")
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#nullable enable

using System;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Text.Json.Serialization;

using Microsoft.Extensions.Configuration;

namespace ArmoniK.Api.Client.RustGrpcChannel;

// Rooted at RuntimeOptions, which reaches every group of the vocabulary, so the whole graph is
// serialized without reflection - which is what lets a trimmed or native-AOT host use this.
[JsonSerializable(typeof(RuntimeOptions))]
internal partial class RuntimeOptionsJsonContext : JsonSerializerContext
{
}

/// <summary>
///   What a caller may set on the runtime: the endpoint, the memory ceilings, and the options every
///   channel takes where its own state none.
/// </summary>
public sealed class RuntimeOptions
{
  /// <summary>Options nobody has set.</summary>
  public RuntimeOptions()
  {
  }

  /// <summary>A copy of <paramref name="other" />, sharing nothing with it.</summary>
  /// <param name="other">The options to copy.</param>
  /// <exception cref="ArgumentNullException"><paramref name="other" /> is null.</exception>
  public RuntimeOptions(RuntimeOptions other)
  {
    if (other is null)
    {
      throw new ArgumentNullException(nameof(other));
    }

    Endpoint = other.Endpoint;
    MemoryCeiling = other.MemoryCeiling;
    MemoryHardCeiling = other.MemoryHardCeiling;
    ChannelDefaults = other.ChannelDefaults is null
                        ? null
                        : new ChannelOptions(other.ChannelDefaults);
  }

  /// <summary>
  ///   The server, as <c>http://host:port</c> in the clear or <c>https://host:port</c> over TLS, that a
  ///   channel created with no endpoint of its own reaches.
  /// </summary>
  /// <remarks>Defaults to none: every channel then names its own.</remarks>
  [JsonPropertyName("Endpoint")]
  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
  public string? Endpoint { get; set; }

  /// <summary>
  ///   The bytes the runtime holds before work waits, counting the buffers lent to send and the
  ///   messages received until the host gives them back: a call stops reading, and a send waits
  ///   for room.
  /// </summary>
  /// <remarks>
  ///   Defaults to 4294967295, four gigabytes, or half the address space where that is smaller;
  ///   a larger value is that too.
  /// </remarks>
  [JsonPropertyName("MemoryCeiling")]
  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
  public long? MemoryCeiling { get; set; }

  /// <summary>
  ///   The bytes past which the runtime stops: a received message that would take the count past
  ///   them ends its call with RESOURCE_EXHAUSTED. Calls admitted to read below MemoryCeiling may
  ///   pass it together, by a message each, and this bounds them. At least MemoryCeiling, or
  ///   MemoryCeiling's default when that is left out.
  /// </summary>
  /// <remarks>Defaults to a quarter above MemoryCeiling.</remarks>
  [JsonPropertyName("MemoryHardCeiling")]
  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
  public long? MemoryHardCeiling { get; set; }

  /// <summary>
  ///   Channel options every channel of the runtime takes where its own options state none: the
  ///   two are merged option by option, a struct's options within it, and the channel's win; an
  ///   alternative - how the server is verified, who the client is, which proxy - merges its fields
  ///   over the same alternative and is taken whole over another.
  /// </summary>
  /// <remarks>Defaults to none.</remarks>
  [JsonPropertyName("ChannelDefaults")]
  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
  public ChannelOptions? ChannelDefaults { get; set; }

  /// <summary>Refuses an option outside the range the engine accepts.</summary>
  /// <exception cref="ArgumentOutOfRangeException">An option is outside its stated bounds.</exception>
  public void Validate()
  {
    if (Endpoint is string endpoint && endpoint.Length < 1)
    {
      throw new ArgumentOutOfRangeException(nameof(Endpoint),
                                            endpoint,
                                            "Endpoint has to be at least 1 character long.");
    }

    if (MemoryCeiling is long memoryCeiling && memoryCeiling < 1)
    {
      throw new ArgumentOutOfRangeException(nameof(MemoryCeiling),
                                            memoryCeiling,
                                            "MemoryCeiling has to be at least 1.");
    }

    if (MemoryHardCeiling is long memoryHardCeiling && memoryHardCeiling < 1)
    {
      throw new ArgumentOutOfRangeException(nameof(MemoryHardCeiling),
                                            memoryHardCeiling,
                                            "MemoryHardCeiling has to be at least 1.");
    }

    ChannelDefaults?.Validate();
  }

  /// <summary>The options <paramref name="section" /> states, each key matched to one without case.</summary>
  /// <param name="section">The section, whose every key has to name an option.</param>
  /// <returns>The options, unset where the section states nothing.</returns>
  /// <exception cref="InvalidOperationException">A key names no option, or holds what its option does not admit.</exception>
  internal static RuntimeOptions Bind(IConfigurationSection section)
  {
    var bound = new RuntimeOptions();

    foreach (var entry in RuntimeOptionsConfiguration.Entries(section))
    {
      if (RuntimeOptionsConfiguration.Is(entry,
                                         "Endpoint"))
      {
        bound.Endpoint = RuntimeOptionsConfiguration.Text(entry);
      }
      else if (RuntimeOptionsConfiguration.Is(entry,
                                              "MemoryCeiling"))
      {
        bound.MemoryCeiling = RuntimeOptionsConfiguration.Int64(entry);
      }
      else if (RuntimeOptionsConfiguration.Is(entry,
                                              "MemoryHardCeiling"))
      {
        bound.MemoryHardCeiling = RuntimeOptionsConfiguration.Int64(entry);
      }
      else if (RuntimeOptionsConfiguration.Is(entry,
                                              "ChannelDefaults"))
      {
        bound.ChannelDefaults = RuntimeOptionsConfiguration.Holds(entry) ? ChannelOptions.Bind(entry) : null;
      }
      else
      {
        throw RuntimeOptionsConfiguration.Unknown(entry,
                                                  "RuntimeOptions");
      }
    }

    return bound;
  }

  /// <summary>The document the engine reads, as UTF-8.</summary>
  /// <returns>The options as JSON, without the ones left unset.</returns>
  /// <exception cref="ArgumentOutOfRangeException">An option is outside its bounds.</exception>
  /// <remarks>
  ///   Checked before it is written, not after it is refused: the engine answers a bad
  ///   document with a status naming neither the option nor the bound.
  /// </remarks>
  internal byte[] Encode()
  {
    Validate();

    return JsonSerializer.SerializeToUtf8Bytes(this,
                                               RuntimeOptionsJsonContext.Default.RuntimeOptions);
  }
}

/// <summary>How the text of a configuration becomes the options above, and why it may not.</summary>
internal static class RuntimeOptionsConfiguration
{
  /// <summary>Whether <paramref name="section" /> is the key <paramref name="name" />, without case.</summary>
  internal static bool Is(IConfigurationSection section,
                          string                name)
    => string.Equals(section.Key,
                     name,
                     StringComparison.OrdinalIgnoreCase);

  /// <summary>The keys of a section that holds options, a key set to null left out as unset.</summary>
  /// <exception cref="InvalidOperationException">It holds a value instead.</exception>
  internal static IConfigurationSection[] Entries(IConfigurationSection section)
    => string.IsNullOrEmpty(section.Value)
         ? section.GetChildren()
                  .Where(entry => entry.Value is not null || entry.GetChildren()
                                                                  .Any())
                  .ToArray()
         : throw new InvalidOperationException($"{section.Path} holds a value, and it names options.");

  /// <summary>Whether a key names anything, an empty one leaving its group or choice unset.</summary>
  internal static bool Holds(IConfigurationSection section)
    => !string.IsNullOrEmpty(section.Value) || section.GetChildren()
                                                      .Any();

  /// <summary>The text of a key that holds a value.</summary>
  /// <exception cref="InvalidOperationException">It holds options instead.</exception>
  internal static string Text(IConfigurationSection section)
    => section.Value ?? throw new InvalidOperationException($"{section.Path} holds options, and it names a value.");

  /// <summary>An integer, or none where the text is empty.</summary>
  internal static long? Int64(IConfigurationSection section)
  {
    var text = Text(section);

    return text.Length == 0
             ? null
             : long.TryParse(text,
                             NumberStyles.Integer,
                             CultureInfo.InvariantCulture,
                             out var value)
               ? value
               : throw Unreadable(section,
                                  "an integer");
  }

  /// <summary>A key nothing declares, refused by its path.</summary>
  internal static InvalidOperationException Unknown(IConfigurationSection section,
                                                    string                owner)
    => new($"{section.Path} names nothing {owner} declares.");

  private static InvalidOperationException Unreadable(IConfigurationSection section,
                                                      string                what)
    => new($"{section.Path} has to be {what}.");
}
