// <auto-generated>
//     Generated from runtime.schema.json by ArmoniK.Api.Client.RustGrpcChannel.OptionsGenerator.
//     Edits here are lost. Change the Rust option types, render the schema again,
//     and build: the schema is what this file is.
// </auto-generated>

// This file is part of the ArmoniK project
//
// Copyright (C) ANEO, 2021-2026. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License")
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ArmoniK.Api.Client.RustGrpcChannel;

// Rooted at RuntimeOptions, which reaches every group of the vocabulary, so the whole graph is
// serialized without reflection - which is what lets a trimmed or native-AOT host use this.
[JsonSerializable(typeof(RuntimeOptions))]
internal partial class RuntimeOptionsJsonContext : JsonSerializerContext
{
}

/// <summary>
///   What a caller may set on the runtime: the endpoint, the memory ceilings, the options every
///   channel takes where its own state none, and what the engine logs.
/// </summary>
public sealed class RuntimeOptions
{
  /// <summary>Options nobody has set.</summary>
  public RuntimeOptions()
  {
  }

  /// <summary>A copy of <paramref name="other" />, sharing nothing with it.</summary>
  /// <param name="other">The options to copy.</param>
  /// <exception cref="ArgumentNullException"><paramref name="other" /> is null.</exception>
  public RuntimeOptions(RuntimeOptions other)
  {
    if (other is null)
    {
      throw new ArgumentNullException(nameof(other));
    }

    Endpoint = other.Endpoint;
    MemoryCeiling = other.MemoryCeiling;
    MemoryHardCeiling = other.MemoryHardCeiling;
    ChannelDefaults = other.ChannelDefaults is null
                        ? null
                        : new ChannelOptions(other.ChannelDefaults);
    Logging = other.Logging is null
                ? null
                : new LoggingOptions(other.Logging);
  }

  /// <summary>
  ///   The server, as <c>http://host:port</c> in the clear or <c>https://host:port</c> over TLS, that a
  ///   channel created with no endpoint of its own reaches.
  /// </summary>
  /// <remarks>Defaults to none: every channel then names its own.</remarks>
  [JsonPropertyName("Endpoint")]
  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
  public string? Endpoint { get; set; }

  /// <summary>
  ///   The bytes the runtime holds before work waits, counting the buffers lent to send and the
  ///   messages received until the host gives them back: a call stops reading, and a send waits
  ///   for room.
  /// </summary>
  /// <remarks>
  ///   Defaults to 4294967295, four gigabytes, or half the address space where that is smaller;
  ///   a larger value is that too.
  /// </remarks>
  [JsonPropertyName("MemoryCeiling")]
  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
  public long? MemoryCeiling { get; set; }

  /// <summary>
  ///   The bytes past which the runtime stops: a received message that would take the count past
  ///   them ends its call with RESOURCE_EXHAUSTED. Calls admitted to read below MemoryCeiling may
  ///   pass it together, by a message each, and this bounds them. At least MemoryCeiling, or
  ///   MemoryCeiling's default when that is left out.
  /// </summary>
  /// <remarks>Defaults to a quarter above MemoryCeiling.</remarks>
  [JsonPropertyName("MemoryHardCeiling")]
  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
  public long? MemoryHardCeiling { get; set; }

  /// <summary>
  ///   Channel options every channel of the runtime takes where its own options state none: the
  ///   two are merged option by option, a struct's options within it, and the channel's win; an
  ///   alternative - how the server is verified, who the client is, which proxy - merges its fields
  ///   over the same alternative and is taken whole over another.
  /// </summary>
  /// <remarks>Defaults to none.</remarks>
  [JsonPropertyName("ChannelDefaults")]
  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
  public ChannelOptions? ChannelDefaults { get; set; }

  /// <summary>What the engine reports of itself to the host.</summary>
  /// <remarks>Defaults to <c>{}</c>, which leaves each of its options at its own default.</remarks>
  [JsonPropertyName("Logging")]
  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
  public LoggingOptions? Logging { get; set; }

  /// <summary>Refuses an option outside the range the engine accepts.</summary>
  /// <exception cref="ArgumentOutOfRangeException">An option is outside its stated bounds.</exception>
  public void Validate()
  {
    if (Endpoint is string endpoint && endpoint.Length < 1)
    {
      throw new ArgumentOutOfRangeException(nameof(Endpoint),
                                            endpoint,
                                            "Endpoint has to be at least 1 character long.");
    }

    if (MemoryCeiling is long memoryCeiling && memoryCeiling < 1)
    {
      throw new ArgumentOutOfRangeException(nameof(MemoryCeiling),
                                            memoryCeiling,
                                            "MemoryCeiling has to be at least 1.");
    }

    if (MemoryHardCeiling is long memoryHardCeiling && memoryHardCeiling < 1)
    {
      throw new ArgumentOutOfRangeException(nameof(MemoryHardCeiling),
                                            memoryHardCeiling,
                                            "MemoryHardCeiling has to be at least 1.");
    }

    ChannelDefaults?.Validate();
    Logging?.Validate();
  }

  /// <summary>The document the engine reads, as UTF-8.</summary>
  /// <returns>The options as JSON, without the ones left unset.</returns>
  /// <exception cref="ArgumentOutOfRangeException">An option is outside its bounds.</exception>
  /// <remarks>
  ///   Checked before it is written, not after it is refused: the engine answers a bad
  ///   document with a status naming neither the option nor the bound.
  /// </remarks>
  internal byte[] Encode()
  {
    Validate();

    return JsonSerializer.SerializeToUtf8Bytes(this,
                                               RuntimeOptionsJsonContext.Default.RuntimeOptions);
  }
}

/// <summary>Which of the engine's log events a host receives.</summary>
/// <remarks>Ignored by a Rust host.</remarks>
public sealed class LoggingOptions
{
  /// <summary>Options nobody has set.</summary>
  public LoggingOptions()
  {
  }

  /// <summary>A copy of <paramref name="other" />, sharing nothing with it.</summary>
  /// <param name="other">The options to copy.</param>
  /// <exception cref="ArgumentNullException"><paramref name="other" /> is null.</exception>
  public LoggingOptions(LoggingOptions other)
  {
    if (other is null)
    {
      throw new ArgumentNullException(nameof(other));
    }

    Filter = other.Filter;
  }

  /// <summary>
  ///   Which events are reported, as directives laid over the default's: comma-separated, each a
  ///   level for every target (<c>warn</c>, or <c>*=warn</c>), a target and its level (<c>h2=debug</c>), or a
  ///   target alone, which is all its levels. A target covers itself and the modules below it -
  ///   <c>h2</c> covers <c>h2::proto</c>, not <c>h2x</c> - and <c>target*</c> covers every target that starts with the
  ///   text: <c>hyper*</c> covers <c>hyper</c> and <c>hyper_util</c>. The most specific directive that covers an
  ///   event decides: the longest target, and at the same length the one without <c>*</c>. A directive
  ///   stated with the same text as one of the default's, both with a <c>*</c> or both without,
  ///   replaces it; every other directive of the default stands, so <c>armonik_transport*=debug</c>
  ///   raises the engine and leaves the rest at warning, where <c>armonik_transport=debug</c> leaves
  ///   the default's <c>armonik_transport*=info</c> standing for what it does not cover. To turn the logs down or off state the default's two
  ///   directives: <c>*=off,armonik_transport*=off</c>. A word that is no level is a target nothing
  ///   emits. A directive that is not understood is ignored with a warning. Read when the runtime
  ///   is created.
  /// </summary>
  /// <remarks>
  ///   Defaults to <c>*=warn,armonik_transport*=info</c>: warnings from every target, and the engine's
  ///   own events at information.
  /// </remarks>
  [JsonPropertyName("Filter")]
  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
  public string? Filter { get; set; }

  /// <summary>Refuses an option outside the range the engine accepts.</summary>
  /// <exception cref="ArgumentOutOfRangeException">An option is outside its stated bounds.</exception>
  public void Validate()
  {
    // The schema bounds nothing here.
  }
}
