------------------------- MODULE DotNetBindingTheorems -------------------------
(***************************************************************************)
(* The public level-2 interface: what the .NET binding proves, stated      *)
(* without proofs.  The proofs live in DotNetBindingTheorems_proofs,       *)
(* which does not exist yet.                                               *)
(*                                                                         *)
(* PLACEHOLDER.  The planned declarations, to be written once the spec     *)
(* converges:                                                              *)
(*                                                                         *)
(* Refinement:                                                             *)
(*  - RefinesSpec == Spec => F!Spec, established the way level 1           *)
(*    established Spec => L0!Spec: Init, [Next]_vars case by case, the     *)
(*    fairness lifts.  Everything proved at levels 0 and 1 - the send      *)
(*    bound, the credit bound, the per-object liveness, the end-of-call    *)
(*    cleanliness, both no-double-free invariants - is then inherited,     *)
(*    not restated.                                                        *)
(*                                                                         *)
(* Discharge of the six host hypotheses - the point of the level:          *)
(*  - HostConsumesEventDischarged: the binding's WF on the consumer and    *)
(*    the drain implies level 1's WF(HostConsumesEvent).                   *)
(*  - HostReturnsBufferDischarged: the using scope's WF implies            *)
(*    WF(HostReturnsBuffer).                                               *)
(*  - The four callback-return conjuncts, from the trampoline doing        *)
(*    bounded work and queueing continuations elsewhere.                   *)
(*                                                                         *)
(* Managed safety, from the _defs manifests:                               *)
(*  - SafetyTheorem == Spec => [](managed invariants).                     *)
(*                                                                         *)
(* Managed liveness:                                                       *)
(*  - BudgetCancellationStopsRetryHolds - conditional, cancellation or     *)
(*    dispose ends the wait; no unconditional termination exists to        *)
(*    prove.                                                               *)
(*  - ReleasedEventuallyHolds, BuffersAlwaysReturnedHolds.                 *)
(***************************************************************************)

EXTENDS DotNetBinding_defs

===============================================================================
